dart-lang/native

.github/ISSUE_TEMPLATE/c_compiler.md, .github/ISSUE_TEMPLATE/native_assets_cli.md, .github/workflows/c_compiler.yaml, .github/workflows/native_assets_cli.yaml, README.md, pkgs/c_compiler/.gitignore, pkgs/c_compiler/CHANGELOG.md, pkgs/c_compiler/README.md, pkgs/c_compiler/analysis_options.yaml, pkgs/c_compiler/lib/c_compiler.dart, pkgs/c_compiler/lib/src/c_compiler_base.dart, pkgs/c_compiler/pubspec.yaml, pkgs/c_compiler/test/c_compiler_test.dart, pkgs/native_assets_cli/.gitignore, pkgs/native_assets_cli/CHANGELOG.md, pkgs/native_assets_cli/README.md, pkgs/native_assets_cli/analysis_options.yaml, pkgs/native_assets_cli/lib/native_assets_cli.dart, pkgs/native_assets_cli/lib/src/native_assets_cli_base.dart, pkgs/native_assets_cli/pubspec.yaml, pkgs/native_assets_cli/test/native_assets_cli_test.dart, pkgs/placeholder.txt
Based on discussions we introduce two packages.
1. `native_assets_cli` which contains the command-line interface for building native assets.
* Named `native_assets_cli` as this is is part of the Native asset feature.
* https://github.com/dart-lang/sdk/issues/50565
* Could possibly be named something like `native_build_cli` if we'd like to connect this with `dart build` name-wise.
* https://github.com/dart-lang/sdk/issues/51165
2. `c_compiler` which can compile C files with clang/msvc/xcodebuild/etc.
* Named this way, so that a potential `rust_compiler` package can have consistent package naming.
Package names are not set in stone until we publish a first version of these packages.
This PR ensures we have the package layout, CI etc. set up correctly.
This PR mirrors the configuration from …
=> Empty packages for `native_assets_cli` and `c_compiler`

pkgs/c_compiler/README.md, pkgs/c_compiler/pubspec.yaml, pkgs/native_assets_cli/CHANGELOG.md, pkgs/native_assets_cli/README.md, pkgs/native_assets_cli/pubspec.yaml
- updates to package metadata and readme badges
(for merging into https://github.com/dart-lang/native/pull/3)
=> updates to package metadata and readme badges

.github/workflows/c_compiler.yaml, .github/workflows/native_assets_cli.yaml, pkgs/c_compiler/README.md, pkgs/c_compiler/lib/c_compiler.dart, pkgs/c_compiler/lib/src/cbuilder/cbuilder.dart, pkgs/c_compiler/lib/src/cbuilder/compiler_resolver.dart, pkgs/c_compiler/lib/src/cbuilder/run_cbuilder.dart, pkgs/c_compiler/lib/src/native_toolchain/android_ndk.dart, pkgs/c_compiler/lib/src/native_toolchain/apple_clang.dart, pkgs/c_compiler/lib/src/native_toolchain/clang.dart, pkgs/c_compiler/lib/src/native_toolchain/recognizer.dart, pkgs/c_compiler/lib/src/native_toolchain/xcode.dart, pkgs/c_compiler/lib/src/tool/tool_instance.dart, pkgs/c_compiler/lib/src/tool/tool_resolver.dart, pkgs/c_compiler/lib/src/utils/sem_version.dart, pkgs/c_compiler/pubspec.yaml, pkgs/c_compiler/test/cbuilder/cbuilder_cross_android_test.dart, pkgs/c_compiler/test/cbuilder/cbuilder_cross_ios_test.dart, pkgs/c_compiler/test/cbuilder/cbuilder_cross_linux_host_test.dart, pkgs/c_compiler/test/cbuilder/cbuilder_cross_macos_host_test.dart, pkgs/c_compiler/test/cbuilder/cbuilder_test.dart, pkgs/c_compiler/test/cbuilder/compiler_resolver_test.dart, pkgs/c_compiler/test/native_toolchain/apple_clang_test.dart, pkgs/c_compiler/test/native_toolchain/clang_test.dart, pkgs/c_compiler/test/native_toolchain/gcc_test.dart, pkgs/c_compiler/test/native_toolchain/recognizer_test.dart, pkgs/c_compiler/test/native_toolchain/xcode_test.dart, pkgs/c_compiler/test/tool/tool_instance_test.dart, pkgs/c_compiler/test/tool/tool_resolver_test.dart, pkgs/native_assets_cli/README.md
Adds support for using the `clang` on MacOS to compile for MacOS and iOS.
For iOS finds the relevant SDK using `xcrun --sdk ... --show-sdk-path`.
Uses the identical NDK setup as for Linux to cross compile to Android.
This PR modifies the workflows so that they are a matrix over OS as well.
The MacOS bots have XCode pre-installed. And the clang in xcode can cross-compile already, so no extra deps needed.
I'm not fully happy with the results yet, but lets see if this new setup + changing the settings on Coveralls to mono-repo will at least make it report coverage on both packages.
More discussion in:
* https://github.com/dart-lang/native/issues
=> MacOS support

README.md, pkgs/c_compiler/README.md, pkgs/native_assets_cli/README.md
Now that we have only one workflow, the badges can only link to that workflow instead of the per-package workflow.
We might as well add those badges to the top-level readme.
=> [infra] fix badges

.github/workflows/dart.yaml, pkgs/c_compiler/lib/src/cbuilder/cbuilder.dart, pkgs/c_compiler/lib/src/cbuilder/compiler_resolver.dart, pkgs/c_compiler/lib/src/cbuilder/run_cbuilder.dart, pkgs/c_compiler/lib/src/native_toolchain/android_ndk.dart, pkgs/c_compiler/lib/src/native_toolchain/msvc.dart, pkgs/c_compiler/lib/src/native_toolchain/recognizer.dart, pkgs/c_compiler/lib/src/tool/tool_resolver.dart, pkgs/c_compiler/lib/src/utils/env_from_bat.dart, pkgs/c_compiler/lib/src/utils/run_process.dart, pkgs/c_compiler/test/cbuilder/cbuilder_cross_windows_host_test.dart, pkgs/c_compiler/test/cbuilder/cbuilder_test.dart, pkgs/c_compiler/test/cbuilder/compiler_resolver_test.dart, pkgs/c_compiler/test/cbuilder/testfiles/add/src/add.c, pkgs/c_compiler/test/helpers.dart, pkgs/c_compiler/test/native_toolchain/msvc_test.dart, pkgs/c_compiler/test/native_toolchain/recognizer_test.dart, pkgs/c_compiler/test/tool/tool_resolver_test.dart, pkgs/native_assets_cli/lib/src/model/build_config.dart, pkgs/native_assets_cli/lib/src/model/dependencies.dart, pkgs/native_assets_cli/test/example/native_add_test.dart, pkgs/native_assets_cli/test/model/asset_test.dart, pkgs/native_assets_cli/test/model/build_config_test.dart, pkgs/native_assets_cli/test/model/dependencies_test.dart
Compilation on Windows with visual studio.
Closes:
* https://github.com/dart-lang/native/issues/15
Some more details:
* Visual studio installations can be found with https://github.com/microsoft/vswhere.
* This PR basically automates https://learn.microsoft.com/en-us/cpp/build/walkthrough-compile-a-c-program-on-the-command-line?view=msvc-170
* The compiler itself is `cl.exe`, there are two, one for each target architecture.
* In order to have the right include paths etc, a `vcvarsxxx.bat` has to be invoked. We capture the environment variables by looking at `set` before and after the batch script invocation.
This PR contains a lot of `.toFilePath()` refactorings to ensure paths are handled correctly on Windows.
Also in this PR, the `RelativePath` tool resolver now takes globs instead of …
=> Windows & MSVC support

pkgs/c_compiler/lib/src/cbuilder/compiler_resolver.dart, pkgs/c_compiler/lib/src/cbuilder/run_cbuilder.dart, pkgs/c_compiler/test/cbuilder/cbuilder_test.dart, pkgs/c_compiler/test/cbuilder/compiler_resolver_test.dart, pkgs/c_compiler/test/helpers.dart, pkgs/native_assets_cli/lib/src/model/build_config.dart, pkgs/native_assets_cli/test/example/native_add_test.dart, pkgs/native_assets_cli/test/helpers.dart, pkgs/native_assets_cli/test/model/build_config_test.dart
When using MSVCs `cl.exe` an accompanying script sets the right environment variables, such as `INCLUDE`.
In visual studio this is `vcvarsall.bat`, `vcvars64.bat` or a similar script, which can be discovered in a relative path from `cl.exe`.
However, on the Dart CI bots, we use a custom script which serves the same purpose.
See https://chromium.googlesource.com/chromium/tools/depot_tools/+/master/win_toolchain/.
We might as well make the script configurable in general, as maybe more compilers require setting the right environment variables. (Side note: on the Dart CI we also use a `clang.exe` with this same environment variables script so that the `clang.exe` can also find the Windows implementations for `printf` etc.)
Dart CL: https://dart-review.googlesource.com/c/sdk/+/298580
=> Windows dart ci

pkgs/c_compiler/lib/src/cbuilder/compiler_resolver.dart, pkgs/c_compiler/test/cbuilder/cbuilder_cross_windows_host_test.dart, pkgs/c_compiler/test/cbuilder/cbuilder_test.dart, pkgs/c_compiler/test/cbuilder/compiler_resolver_test.dart, pkgs/c_compiler/test/helpers.dart, pkgs/native_assets_cli/lib/src/model/build_config.dart, pkgs/native_assets_cli/test/example/native_add_test.dart, pkgs/native_assets_cli/test/helpers.dart, pkgs/native_assets_cli/test/model/build_config_test.dart
Changes the format for the YAML/JSON `BuildConfig` to have a nested `c_compiler` key. Example config:
```yaml
c_compiler:
ar: /tmp/MLTHBB/fake_ar
cc: /tmp/MLTHBB/fake_clang
env_script: /tmp/MLTHBB/fake_env_script.bat
env_script_args: []
ld: /tmp/MLTHBB/fake_ld
dependency_metadata:
bar:
key: value
foo:
a: 321
z:
- z
- a
link_mode_preference: prefer-static
out_dir: /tmp/MLTHBB/out1/
package_root: /tmp/MLTHBB/
target: ios_arm64
target_ios_sdk: iphoneos
version: 1.0.0
```
This changes the environment variables to set if the compiler cannot be auto-detected on `PATH` or default install locations to:
* `C_COMPILER__AR`
* `C_COMPILER__CC`
* `C_COMPILER__LD`
* `C_COMPILER__ENV_SCRIPT`
* `C_COMPILER__ENV_SCRIPT_ARGS`
These will need to be updated in the Dart SDK: …
=> [native_assets_cli] Nest `c_compiler` config

pkgs/c_compiler/lib/src/utils/env_from_bat.dart
When trying to hermetic builds downstream by not passing any environment variables except the ones I explicitly set, I encountered empty environments, these weren't handled well.
The subsequent `Process.start` invocation with that environment lead to `ProcessException: The parameter is incorrect.` (it doesn't mention the environment at all 🙈 ).
=> Prevent passing empty environment keys

pkgs/c_compiler/lib/src/cbuilder/cbuilder.dart, pkgs/c_compiler/lib/src/cbuilder/run_cbuilder.dart, pkgs/c_compiler/lib/src/utils/run_process.dart, pkgs/c_compiler/test/cbuilder/cbuilder_build_failure_test.dart, pkgs/c_compiler/test/cbuilder/testfiles/add/src/add.c
The `CBuilder` will now throw `ProcessException`s.
That way `build.dart` invocations return a non-zero exit code if compilation fails.
The logs of the compiler itself are streamed to the `logger`.
=> [c_compiler] Propagate compilation failures as exceptions

pkgs/c_compiler/lib/src/cbuilder/cbuilder.dart, pkgs/c_compiler/lib/src/cbuilder/run_cbuilder.dart, pkgs/c_compiler/lib/src/native_toolchain/android_ndk.dart, pkgs/c_compiler/lib/src/native_toolchain/msvc.dart, pkgs/c_compiler/lib/src/native_toolchain/recognizer.dart, pkgs/c_compiler/lib/src/native_toolchain/xcode.dart, pkgs/c_compiler/lib/src/tool/tool_resolver.dart, pkgs/c_compiler/lib/src/utils/run_process.dart, pkgs/c_compiler/test/native_toolchain/recognizer_test.dart, pkgs/native_assets_cli/example/native_add/build.dart
Make the `Logger? logger` parameter `required` everywhere in the code.
This means it's a conscious decision of users to _not_ install a logger, leading to no log output from the wrapped C compiler.
We do the same in our internal code, so that we don't forget threading it through.
=> [c_compiler] Make `logger` required

.github/workflows/dart.yaml, pkgs/native_assets_cli/lib/src/model/build_config.dart, pkgs/native_assets_cli/test/model/build_config_test.dart
It's most likely an error if paths are provide that don't exist.
https://dart-review.googlesource.com/c/sdk/+/300203/17/pkg/native_assets_builder/lib/src/build_runner/build_runner.dart#179
=> [native_assets_cli] Require dirs to exist

pkgs/c_compiler/lib/src/native_toolchain/msvc.dart, pkgs/c_compiler/lib/src/utils/run_process.dart
Makes `runProcess` consistent with the ones in https://dart-review.googlesource.com/c/sdk/+/267340.
=> [c_compiler] `runProcess` additions

pkgs/c_compiler/lib/src/cbuilder/run_cbuilder.dart, pkgs/c_compiler/test/cbuilder/cbuilder_cross_android_test.dart, pkgs/c_compiler/test/cbuilder/cbuilder_cross_ios_test.dart, pkgs/c_compiler/test/cbuilder/cbuilder_cross_linux_host_test.dart, pkgs/c_compiler/test/cbuilder/cbuilder_cross_macos_host_test.dart, pkgs/c_compiler/test/cbuilder/cbuilder_cross_windows_host_test.dart, pkgs/native_assets_cli/lib/src/model/build_config.dart, pkgs/native_assets_cli/test/model/asset_test.dart, pkgs/native_assets_cli/test/model/build_config_test.dart, pkgs/native_assets_cli/test/model/build_output_test.dart, pkgs/native_assets_cli/test/model/target_test.dart
Enables the launcher (Flutter SDK) to pass the Android NDK API level.
Addresses the launcher part of
* https://github.com/dart-lang/native/issues/48
Also, makes all test that expect `FormatException`s actually check the content.
=> Add Android NDK API version

pkgs/c_compiler/lib/src/cbuilder/run_cbuilder.dart, pkgs/c_compiler/test/cbuilder/cbuilder_cross_ios_test.dart, pkgs/native_assets_cli/lib/src/model/target.dart
I added the target in 3d891667678bfca9d672784d9cbcf9275bbf6594, but didn't actually try to run it on Apple clang. This PR fixes that.
=> [c_compiler] Target ios_x64

pkgs/c_compiler/lib/src/cbuilder/cbuilder.dart, pkgs/c_compiler/lib/src/cbuilder/run_cbuilder.dart, pkgs/c_compiler/lib/src/native_toolchain/apple_clang.dart, pkgs/c_compiler/pubspec.yaml, pkgs/c_compiler/test/cbuilder/cbuilder_cross_ios_test.dart, pkgs/c_compiler/test/helpers.dart, pkgs/c_compiler/test/native_toolchain/apple_clang_test.dart
Exercises the logic discussed in https://github.com/dart-lang/native/issues/54.
We might not actually want to set the install name in package:c_compiler, but instead update it inside Flutter/Dart. See the discussion in https://github.com/dart-lang/native/issues/54. However, it is still useful to have the logic be exercised here so that we know we have the right process invocations and the tools available on CI.
=> [c_compiler] Support setting the install name of dylibs

pkgs/c_compiler/lib/src/cbuilder/cbuilder.dart, pkgs/c_compiler/test/cbuilder/cbuilder_test.dart, pkgs/native_assets_cli/lib/src/model/build_config.dart, pkgs/native_assets_cli/test/example/native_add_test.dart, pkgs/native_assets_cli/test/model/build_config_test.dart
Adds a `dry_run` option to the native assets CLI, and makes the c_compiler package respect it.
Issue:
* https://github.com/dart-lang/native/issues/51
=> [native_assets_cli] Add `dry_run` option

pkgs/c_compiler/lib/src/utils/run_process.dart
Remove the `stderrCompleter` and `stdoutCompleter` variables in favor of
holding the `StreamSubscription` and using `asFuture()`. This ensures
that any errors from the stream (for instance UTF8 decodign errors) are
captured by the awaited `Future` instead of bubbling up as unhandled
async errors.
Use the `.wait` extension for records so error handlers are eagerly
added for the `exitCode` and output futures instead of not listening to
the other futures until after the exit code has completed, and errors
may have already bubbled up unhandled.
Also refactor the use of a map literal - don't use an extra `...{}`
literal, move the for-in element to the outer collection literal and use
`...?` over a conditional element with a null check. Skip the extra
intermediate variable `newEnvironment`. …
=> Handle errors from process output

pkgs/c_compiler/lib/src/cbuilder/run_cbuilder.dart, pkgs/c_compiler/test/cbuilder/cbuilder_build_failure_test.dart, pkgs/c_compiler/test/cbuilder/cbuilder_cross_android_test.dart, pkgs/c_compiler/test/cbuilder/cbuilder_cross_ios_test.dart, pkgs/c_compiler/test/cbuilder/cbuilder_cross_linux_host_test.dart, pkgs/c_compiler/test/cbuilder/cbuilder_cross_macos_host_test.dart, pkgs/c_compiler/test/cbuilder/cbuilder_cross_windows_host_test.dart, pkgs/c_compiler/test/cbuilder/cbuilder_test.dart, pkgs/c_compiler/test/cbuilder/compiler_resolver_test.dart, pkgs/c_compiler/test/cbuilder/testfiles/add/src/add.c, pkgs/c_compiler/test/cbuilder/testfiles/hello_world/src/hello_world.c, pkgs/native_assets_cli/example/native_add/src/native_add.c, pkgs/native_assets_cli/lib/native_assets_cli.dart, pkgs/native_assets_cli/lib/src/model/build_config.dart, pkgs/native_assets_cli/lib/src/model/build_mode.dart, pkgs/native_assets_cli/test/example/native_add_test.dart, pkgs/native_assets_cli/test/model/build_config_test.dart
Introduces `BuildMode` with `release` and `debug` values.
This is not an enum, but a collection with two opaque objects. (Similar to `Target`.) This way adding more values later will not be a breaking change.
BuildMode is required, this means that launchers will have to set it. (Currently, dart has no concept of build modes, we will have to default to `release` for now and add some logic to `dart run` and `dart build` later.) Since it is required, we will have to do a manual roll into the Dart SDK where we start passing `BuildMode.release` to the new required argument.
Package c_compiler picks up the configuration and sets either the `DEBUG` or `RELEASE` macro to `1`.
We should probably do the mapping from `BuildMode` to defines in `build.dart` files, because it might be project specific. …
=> Build mode

pkgs/c_compiler/lib/src/cbuilder/run_cbuilder.dart, pkgs/c_compiler/pubspec.yaml, pkgs/c_compiler/test/cbuilder/cbuilder_cross_ios_test.dart, pkgs/native_assets_builder/pubspec.yaml, pkgs/native_assets_cli/example/native_add/pubspec.yaml
We were not passing the right SDK for iossimulator compilations. This only led to warnings which weren't checked in the tests. Trying to actually pass a dylib to iOS didn't work. The unit test now contains some `otool` checks to see that we're building the right thing.
The non-path dependencies in this PR are needed to make pub resolve things downstream:
* https://github.com/dart-lang/pub/issues/3343#issuecomment-1623935798
The messiness with dependencies should go away once we publish a v0.1 for each package. (Also, then we cannot have relative path dependencies anymore, and PRs that involve multiple packages will need to be stacked on top of each other.)
=> [c_compiler] Pass the correct SDK for iOS simulator builds

pkgs/native_assets_cli/CHANGELOG.md, pkgs/native_assets_cli/pubspec.yaml
https://github.com/dart-lang/native/issues/71
This package needs to be published before the other two.
=> [native_assets_cli] Bump version to v0.1.0

pkgs/native_assets_builder/test/data/native_add/pubspec.yaml, pkgs/native_assets_builder/test/data/native_add_add_source/pubspec.yaml, pkgs/native_assets_builder/test/data/native_subtract/pubspec.yaml, pkgs/native_assets_cli/example/native_add_library/pubspec.yaml
After this PR, all examples and integration test projects also build against published versions of the packages.
This means we do not run tests against path dependencies at all anymore.  Testing this is tracked in https://github.com/dart-lang/native/issues/80.
=> [infra] Remove the last path dependencies

pkgs/native_assets_builder/pubspec.yaml, pkgs/native_assets_cli/CHANGELOG.md, pkgs/native_assets_cli/pubspec.yaml, pkgs/native_toolchain_c/CHANGELOG.md, pkgs/native_toolchain_c/pubspec.yaml
No version bump, the topics will be pushed to pub.dev next time we have the need to publish a package version.
=> Add topics

pkgs/native_assets_builder/CHANGELOG.md, pkgs/native_assets_builder/lib/src/build_runner/build_runner.dart, pkgs/native_assets_builder/test/build_runner/build_runner_asset_id_test.dart, pkgs/native_assets_builder/test/data/manifest.yaml, pkgs/native_assets_builder/test/data/wrong_namespace_asset/build.dart, pkgs/native_assets_builder/test/data/wrong_namespace_asset/pubspec.yaml
Closes:
* https://github.com/dart-lang/native/issues/96
=> Package name spacing

pkgs/native_assets_builder/CHANGELOG.md, pkgs/native_assets_builder/lib/src/build_runner/build_planner.dart, pkgs/native_assets_builder/lib/src/build_runner/build_runner.dart, pkgs/native_assets_builder/test/build_runner/build_planner_test.dart, pkgs/native_assets_builder/test/build_runner/build_runner_asset_id_test.dart, pkgs/native_assets_builder/test/build_runner/build_runner_build_output_format_test.dart, pkgs/native_assets_builder/test/build_runner/build_runner_cycle_test.dart, pkgs/native_assets_builder/test/build_runner/build_runner_failure_test.dart, pkgs/native_assets_builder/test/build_runner/helpers.dart, pkgs/native_assets_builder/test/data/cyclic_package_1/build.dart, pkgs/native_assets_builder/test/data/cyclic_package_1/pubspec.yaml, pkgs/native_assets_builder/test/data/cyclic_package_2/build.dart, pkgs/native_assets_builder/test/data/cyclic_package_2/pubspec.yaml, pkgs/native_assets_builder/test/data/manifest.yaml, pkgs/native_assets_builder/test/data/wrong_build_output/build.dart, pkgs/native_assets_builder/test/data/wrong_build_output/pubspec.yaml, pkgs/native_assets_builder/test/data/wrong_build_output_2/build.dart, pkgs/native_assets_builder/test/data/wrong_build_output_2/pubspec.yaml, pkgs/native_assets_builder/test/data/wrong_build_output_3/build.dart, pkgs/native_assets_builder/test/data/wrong_build_output_3/pubspec.yaml, pkgs/native_assets_builder/test/helpers.dart
Closes #106.
* Streams errors to the logger.
* Returns a `success` boolean.
Closes #111.
* Deletes `build_output.yaml` to prevent caching on build failures. (See issue for alternative solutions.)
=> [native_assets_builder] Stop throwing from BuildRunner

pkgs/native_toolchain_c/CHANGELOG.md, pkgs/native_toolchain_c/lib/src/cbuilder/cbuilder.dart, pkgs/native_toolchain_c/pubspec.yaml, pkgs/native_toolchain_c/test/cbuilder/cbuilder_build_failure_test.dart, pkgs/native_toolchain_c/test/cbuilder/cbuilder_cross_android_test.dart, pkgs/native_toolchain_c/test/cbuilder/cbuilder_cross_ios_test.dart, pkgs/native_toolchain_c/test/cbuilder/cbuilder_cross_linux_host_test.dart, pkgs/native_toolchain_c/test/cbuilder/cbuilder_cross_macos_host_test.dart, pkgs/native_toolchain_c/test/cbuilder/cbuilder_cross_windows_host_test.dart, pkgs/native_toolchain_c/test/cbuilder/cbuilder_test.dart
Bug https://github.com/dart-lang/native/issues/100.
1. This PR: Roll rename into `package:native_toolchain_c` and rename param.
2. Then publish native_toolchain_c.
3. Then a PR that rolls both native_toolchain_c and native_assets_cli into native_assets_builder.
=> [native_toolchain_c] Rename `assetName` to `assetId`

pkgs/native_toolchain_c/CHANGELOG.md, pkgs/native_toolchain_c/lib/src/cbuilder/cbuilder.dart, pkgs/native_toolchain_c/lib/src/cbuilder/run_cbuilder.dart, pkgs/native_toolchain_c/pubspec.yaml, pkgs/native_toolchain_c/test/cbuilder/cbuilder_test.dart, pkgs/native_toolchain_c/test/cbuilder/testfiles/defines/src/defines.c
This PR adds `CBuilder.defines` which can be used to specify definitions for preprocessor macros. Providing a value for a macro is optional.
Whether a macro with the name of the current `BuildMode` is defined is now configurable through `CBuilder.buildModeDefine`. Per default, this option is enabled.
Additionally, the standard `NDEBUG` macro is now being defined when _not_ building with `BuildMode.debug`. This behavior is also configurable (`CBuilder.ndebugDefine`) and enabled by default.
Closes https://github.com/dart-lang/native/issues/61
=> [native_toolchain_c] Add support for configuring preprocessor macro defines

pkgs/native_toolchain_c/CHANGELOG.md, pkgs/native_toolchain_c/lib/src/cbuilder/cbuilder.dart, pkgs/native_toolchain_c/lib/src/cbuilder/run_cbuilder.dart, pkgs/native_toolchain_c/pubspec.yaml, pkgs/native_toolchain_c/test/cbuilder/cbuilder_cross_android_test.dart, pkgs/native_toolchain_c/test/cbuilder/cbuilder_cross_ios_test.dart, pkgs/native_toolchain_c/test/cbuilder/cbuilder_cross_linux_host_test.dart, pkgs/native_toolchain_c/test/cbuilder/cbuilder_cross_macos_host_test.dart, pkgs/native_toolchain_c/test/cbuilder/cbuilder_cross_windows_host_test.dart, pkgs/native_toolchain_c/test/cbuilder/cbuilder_test.dart, pkgs/native_toolchain_c/test/helpers.dart
The rust `cc` crate provides [defaults for passing `-fPIC`](https://docs.rs/cc/latest/cc/struct.Build.html#method.pic) to the compiler that simplify configuration for most use cases. This PR adapts this behavior for `CBuilder`.
Closes https://github.com/dart-lang/native/issues/119
=> [native_toolchain_c] Default handling for PIC/PIE compiler flags

pkgs/native_toolchain_c/CHANGELOG.md, pkgs/native_toolchain_c/lib/src/native_toolchain/msvc.dart, pkgs/native_toolchain_c/pubspec.yaml
Closes: https://github.com/dart-lang/native/issues/123
=> [native_toolchain_c] Fix MSVC x86 toolchain resolution

pkgs/native_assets_builder/CHANGELOG.md, pkgs/native_assets_builder/lib/src/package_layout/package_layout.dart, pkgs/native_assets_builder/pubspec.yaml, pkgs/native_assets_builder/test/build_runner/package_layout_test.dart
Provide a constructor for `PackageLayout` that does not require reading and reparsing the package config file.
Context:
* https://github.com/flutter/flutter/issues/134427
=> `PackageLayout` constructor for already parsed `PackageConfig`

pkgs/native_assets_builder/CHANGELOG.md, pkgs/native_assets_builder/lib/src/build_runner/build_runner.dart, pkgs/native_assets_builder/pubspec.yaml, pkgs/native_assets_builder/test/build_runner/build_runner_test.dart, pkgs/native_assets_builder/test/build_runner/helpers.dart
Enable using `PackageLayout` in `build` and `run` from `NativeAssetsBuildRunner`, so that does not require reading and reparsing the package config file.
Follow up of:
* https://github.com/dart-lang/native/pull/126
That PR only covered the code paths in flutter_tools using `PackageLayout.packagesWithNativeAssets`, this also should cover the paths doing the actual builds.
(Note that flutter_tools requires published dependencies, hence we just land small PRs here and publish right away.)
Context:
* https://github.com/flutter/flutter/issues/134427
=> [native_assets_builder] Take packageLayout for build and dryRun

pkgs/native_toolchain_c/lib/src/cbuilder/run_cbuilder.dart
Closes: https://github.com/dart-lang/native/issues/130
Revving pubspec version isn't necessary, this is mostly to enable to roll to the Dart SDK. (Users can get this after a next version is merged.)
=> [native_toolchain_c] Enable relocations in RO sections on clang

pkgs/native_toolchain_c/CHANGELOG.md, pkgs/native_toolchain_c/lib/src/cbuilder/cbuilder.dart, pkgs/native_toolchain_c/lib/src/cbuilder/run_cbuilder.dart, pkgs/native_toolchain_c/lib/src/native_toolchain/xcode.dart, pkgs/native_toolchain_c/pubspec.yaml, pkgs/native_toolchain_c/test/cbuilder/cbuilder_build_failure_test.dart, pkgs/native_toolchain_c/test/cbuilder/cbuilder_cross_android_test.dart, pkgs/native_toolchain_c/test/cbuilder/cbuilder_cross_ios_test.dart, pkgs/native_toolchain_c/test/cbuilder/cbuilder_cross_linux_host_test.dart, pkgs/native_toolchain_c/test/cbuilder/cbuilder_cross_macos_host_test.dart, pkgs/native_toolchain_c/test/cbuilder/cbuilder_cross_windows_host_test.dart, pkgs/native_toolchain_c/test/cbuilder/cbuilder_test.dart, pkgs/native_toolchain_c/test/cbuilder/compiler_resolver_test.dart, pkgs/native_toolchain_c/test/cbuilder/testfiles/hello_world_cpp/src/hello_world_cpp.cc, pkgs/native_toolchain_c/test/cbuilder/testfiles/includes/include/includes.h, pkgs/native_toolchain_c/test/cbuilder/testfiles/includes/src/includes.c, pkgs/native_toolchain_c/test/helpers.dart, pkgs/native_toolchain_c/test/native_toolchain/recognizer_test.dart, pkgs/native_toolchain_c/test/tool/tool_resolver_test.dart, pkgs/native_toolchain_c/test/utils/run_process_test.dart
This PR adds a few more options to `CBuilder` that are commonly useful. 
The `flags` option allows users to accomplish most things, even if `CBuilder` does support the specific use case.
The added options follow the example set by the [`cc` crate](https://docs.rs/cc/latest/cc/struct.Build.html).
=> Add `includes`, `flags`, `std`, `language`, `cppLinkStdLib` options

.github/workflows/dart.yaml
Brings clang slightly closer to the one pinned in the Dart SDK (which is bleeding edge).
Unfortunately, we can't easily use unstable clang versions on the CI here. So Clang 16 and 17 are not available yet. https://github.com/dart-lang/native/issues/131#issuecomment-1720742490
=> [CI] Bump clang to newer version

pkgs/native_toolchain_c/CHANGELOG.md, pkgs/native_toolchain_c/pubspec.yaml
It looks like the auto-publisher doesn't pick up on semantic versions with `+x`, so bump from 0.2.4+1 to 0.2.5.
=> [native_toolchain_c] Bump version

pkgs/native_assets_cli/example/native_add_library/ffigen.yaml
<details>
<summary>
Some minor context how I got here:
</summary>
Been fighting with ffigen for about a week now to get a project called `llama_cpp` ported over to Dart as a convenient package. I've got ffi working in a side project of mine (shady.ai) but creating a plugin_ffi package has been troublesome.
</details>
Before this PR, upon checking out the repository, things seemed to work at first glance. No compile errors. I was able to execute the `test` and `run` commands with success in the `native_add_library` package.
However, I was unable to re-generate Dart code from the native header (specified in `ffigen.yaml`), turns out it's due to a typo in the [headers] section.
Steps I had taken prior this PR:
1. Navigate to `dart_lang_native/pkgs/native_assets_cli/example/native_add_library` …
=> fix: Header filename mismatch causing ffigen to produce empty output

pkgs/native_assets_cli/CHANGELOG.md, pkgs/native_assets_cli/lib/src/model/build_config.dart, pkgs/native_assets_cli/pubspec.yaml, pkgs/native_assets_cli/test/model/build_config_test.dart
Bug: https://github.com/dart-lang/native/issues/142
=> [native_assets_cli] `BuildConfig.packageName`

pkgs/native_toolchain_c/CHANGELOG.md, pkgs/native_toolchain_c/pubspec.yaml, pkgs/native_toolchain_c/test/cbuilder/cbuilder_build_failure_test.dart, pkgs/native_toolchain_c/test/cbuilder/cbuilder_cross_android_test.dart, pkgs/native_toolchain_c/test/cbuilder/cbuilder_cross_ios_test.dart, pkgs/native_toolchain_c/test/cbuilder/cbuilder_cross_linux_host_test.dart, pkgs/native_toolchain_c/test/cbuilder/cbuilder_cross_macos_host_test.dart, pkgs/native_toolchain_c/test/cbuilder/cbuilder_cross_windows_host_test.dart, pkgs/native_toolchain_c/test/cbuilder/cbuilder_test.dart, pkgs/native_toolchain_c/test/cbuilder/compiler_resolver_test.dart
native_assets_builder's tests use native_toolchain_c, so we need to roll this first.
* https://github.com/dart-lang/native/issues/142
=> [native_toolchain_c] Bump deps

.github/workflows/dart.yaml, pkgs/native_assets_builder/CHANGELOG.md, pkgs/native_assets_builder/lib/src/build_runner/build_runner.dart, pkgs/native_assets_builder/pubspec.yaml, pkgs/native_assets_builder/test/build_runner/build_runner_asset_id_test.dart, pkgs/native_assets_builder/test/data/cyclic_package_1/pubspec.yaml, pkgs/native_assets_builder/test/data/cyclic_package_2/pubspec.yaml, pkgs/native_assets_builder/test/data/native_add/manifest.yaml, pkgs/native_assets_builder/test/data/native_add/pubspec.yaml, pkgs/native_assets_builder/test/data/native_add_add_source/pubspec.yaml, pkgs/native_assets_builder/test/data/native_subtract/pubspec.yaml, pkgs/native_assets_builder/test/data/package_reading_metadata/pubspec.yaml, pkgs/native_assets_builder/test/data/package_with_metadata/pubspec.yaml, pkgs/native_assets_builder/test/data/wrong_build_output/pubspec.yaml, pkgs/native_assets_builder/test/data/wrong_build_output_2/pubspec.yaml, pkgs/native_assets_builder/test/data/wrong_build_output_3/pubspec.yaml, pkgs/native_assets_builder/test/data/wrong_namespace_asset/pubspec.yaml, pkgs/native_assets_cli/example/native_add_library/pubspec.yaml, pkgs/native_assets_cli/test/example/native_add_library_test.dart
Closes: https://github.com/dart-lang/native/issues/142
=> [native_assets_builder] Pass packageName in to builds

pkgs/native_assets_cli/CHANGELOG.md, pkgs/native_assets_cli/lib/src/model/build_output.dart, pkgs/native_assets_cli/lib/src/model/dependencies.dart, pkgs/native_assets_cli/pubspec.yaml, pkgs/native_assets_cli/test/model/build_output_test.dart
The issue in https://github.com/dart-lang/native/issues/168 was not caught due to the packages depending on each through through pub rather than as path dependencies. It was the `native_toolchain_c` tests that failed which earlier on CI depended on a version of `native_assets_cli` during test.
The core issue here is that `Dependencies` should likely be properly immutable (as indicated by its `const` constructor that's always been there) and its `dependencies` property should instead be exposed as an `Iterable` or not at all directly. 
Since making those changes is a breaking change, I will instead follow-up with those changes as part of a `0.4.0` release. This fix removes the const lists/maps that the depending packages are not currently expecting.
Fixes …
=> Temporarily allow modification of a BuildOutput's raw dependencies

pkgs/native_toolchain_c/CHANGELOG.md, pkgs/native_toolchain_c/lib/src/cbuilder/compiler_resolver.dart, pkgs/native_toolchain_c/lib/src/native_toolchain/msvc.dart, pkgs/native_toolchain_c/pubspec.yaml, pkgs/native_toolchain_c/test/native_toolchain/msvc_test.dart
This PR adds support to be able to compile native-assets on windows-arm64.
It seems to be what is needed to compile windows-arm64 flutter apps, as discussed initially [here](https://github.com/flutter/flutter/issues/129807#issuecomment-1778949427).
@dcharkes I'm not sure which tests to update exactly. Since windows-arm64 runners are not available for this repository, will we still be able to test this? In more, do existing x64 runners have installed msvc arm64 toolchain?
=> [native_toolchain_c] Support MSVC arm64 toolchain

pkgs/native_toolchain_c/test/cbuilder/cbuilder_cross_android_test.dart
https://docs.flutter.dev/reference/supported-platforms now lists 34 instead of 30.
Update our testing to cover this.
=> [native_toolchain_c] Bump highest tested NDK version to 34

pkgs/native_toolchain_c/lib/src/cbuilder/run_cbuilder.dart
Addresses: https://github.com/dart-lang/native/pull/165#discussion_r1375048853
This is in line with what CMake does, so it's probably a more reasonable thing to do than `-nostartfiles`.
The documentation says the sysroot should be auto-discovered on NDKs newer than 22, but it doesn't seem to break the newer versions, so maybe lets just keep the logic consistent for various NDK versions.
We probably need a workaround for https://github.com/dart-lang/native/pull/165 temporarily.
=> [native_toolchain_c] Use sysroot on Android

.github/workflows/native.yaml, .github/workflows/native_toolchain_c.yaml
It looks like the CI didn't run the sysroot and minSdkVersion against each other and merged them both.
=> [infra] Bump NDK version

pkgs/native_toolchain_c/lib/src/cbuilder/run_cbuilder.dart, pkgs/native_toolchain_c/test/cbuilder/cbuilder_cross_android_test.dart
Closes: https://github.com/dart-lang/native/issues/171
Uses the workaround that the Android Gradle plugin uses: https://github.com/dart-lang/native/issues/171#issuecomment-1789064713.
=> [native_toolchain_c] Add workaround for minSdkVersion 19 and 20

.github/workflows/ffigen.yml, .github/workflows/jnigen.yaml, pkgs/jni/.gitignore, pkgs/jnigen/example/notification_plugin/.gitignore
Try to fix the first issue mentioned in: https://github.com/dart-lang/native/issues/812
=> [infra] Try fix coveralls

.github/workflows/ffigen.yml, .github/workflows/jnigen.yaml, .github/workflows/native.yaml
Try to fix the first issue from https://github.com/dart-lang/native/issues/812.
Documentation from Coveralls: https://coveralls.io/better-monorepo-support
=> [infra] Try to use `carryforward`

.github/workflows/native.yaml, pkgs/jni/example/pubspec.lock, tools/.gitignore, tools/bin/change_dependencies.dart, tools/pubspec.yaml
This PR adds a script that rewrites pubspecs to use path dependencies between the `native_*` packages in this repo.
This might be too strict if we ever need to breaking changes across multiple packages, in that case we can temporarily disable this.
Closes: https://github.com/dart-lang/native/issues/80
=> [infra] script to change deps to path dependencies

.github/labeler.yml, pkgs/jni/example/pubspec.lock, pkgs/jni/test/jobject_test.dart, pkgs/jnigen/test/jackson_core_test/generated_files_test.dart, pkgs/jnigen/test/test_util/test_util.dart
* Actually awaiting `Isolate.run`
* Increasing the time limit for binding generation tests
=> [jnigen] Fix flaky tests

pkgs/ffigen/analysis_options.yaml, pkgs/jni/analysis_options.yaml, pkgs/jnigen/analysis_options.yaml, pkgs/native_assets_builder/analysis_options.yaml, pkgs/native_assets_cli/analysis_options.yaml, pkgs/native_toolchain_c/analysis_options.yaml
Neat trick from https://dart-review.googlesource.com/c/sdk/+/338589.
=> [infra] Hide TODOs from problems view in VSCode

pkgs/native_assets_builder/test/build_runner/build_runner_asset_id_test.dart, pkgs/native_assets_builder/test/build_runner/build_runner_non_root_package_test.dart, pkgs/native_assets_builder/test/data/manifest.yaml, pkgs/native_assets_builder/test/data/native_add/pubspec.yaml, pkgs/native_assets_builder/test/data/some_dev_dep/bin/some_dev_dep.dart, pkgs/native_assets_builder/test/data/some_dev_dep/pubspec.yaml
The Windows bots on the Dart SDK CI don't have libclang installed:
https://dart-review.googlesource.com/c/sdk/+/339124 -> https://dart-ci.firebaseapp.com/cl/339124/5 -> https://logs.chromium.org/logs/dart/buildbucket/cr-buildbucket/8762986001033204401/+/u/test_results/new_test_failures__logs_
This test does not need to use FFIgen, we can use some other package with a bin script.
=> [native_assets_builder] Don't use FFIgen in test

pkgs/native_assets_builder/lib/src/build_runner/build_planner.dart, pkgs/native_assets_builder/test/build_runner/build_planner_test.dart
With `dart/flutter run dont_exist`, dartdev or flutter_tools might pass a package name to `runPackageName` that is not in the package graph.
=> [native_assets_builder] Handle non-existing package names

.github/workflows/ffigen.yml, .github/workflows/ffigen_weekly.yml
The mac arm64 bot isn't free, so we'll just run it once a week, rather than on every PR. CPU specific bugs don't come up very often, so this should be sufficient.
Fixes #845
=> [ffigen] Run ffigen CI less often on Apple silicon

.github/workflows/health.yaml
We already have coveralls check coverage for the various packages.
The coverage check is blocking various PRs on this repo:
- https://github.com/dart-lang/native/pull/861
- https://github.com/dart-lang/native/pull/858
=> [infra] Skip coverage in health check

pkgs/native_toolchain_c/CHANGELOG.md, pkgs/native_toolchain_c/lib/native_toolchain_c.dart, pkgs/native_toolchain_c/lib/src/cbuilder/run_cbuilder.dart, pkgs/native_toolchain_c/lib/src/utils/env_from_bat.dart, pkgs/native_toolchain_c/pubspec.yaml, pkgs/native_toolchain_c/test/native_toolchain/msvc_test.dart
* https://github.com/dart-lang/native/issues/856#issuecomment-1857645843
=> [native_toolchain_c] Export `environmentFromBatchFile`

pkgs/jni/src/dartjni.c
- Fix clang errors when compiled with `-Werror -Wunused-variable -Wsometimes-uninitialized`
---
<details>
- Changes to packages require [corresponding tests](https://github.com/dart-lang/.github/blob/main/CONTRIBU …
=> Fix clang "sometimes-uninitialized" and "unused-variable" warnings

pkgs/ffigen/CHANGELOG.md, pkgs/ffigen/lib/src/config_provider/spec_utils.dart
- Search 'libclang.so' in conda environment, use any version clang without ungrading system's. A feature request in https://github.com/dart-lang/native/issues/868
---
<details>
- Changes to packages require …
=> [ffigen] Search dylib in conda env path

.github/workflows/health.yaml, pkgs/native_assets_builder/dart_test.yaml, pkgs/native_assets_builder/lib/native_assets_builder.dart, pkgs/native_assets_builder/lib/src/model/asset.dart, pkgs/native_assets_builder/lib/src/utils/yaml.dart, pkgs/native_assets_builder/pubspec.yaml, pkgs/native_assets_builder/test/model/asset_test.dart, pkgs/native_assets_cli/CHANGELOG.md, pkgs/native_assets_cli/lib/src/model/asset.dart, pkgs/native_assets_cli/pubspec.yaml, pkgs/native_assets_cli/test/example/native_add_library_test.dart, pkgs/native_assets_cli/test/helpers.dart, pkgs/native_assets_cli/test/model/asset_test.dart, pkgs/native_assets_cli/test/model/build_output_test.dart
Classes/methods that are not used in writing `build.dart` scripts, should not be part of `package:native_assets_cli`.
This PR moves code to `package:native_assets_builder` or deletes it entirely.
This PR will likely need to be manually rolled into Dart and Flutter to fix imports.
Issues:
* https://github.com/dart-lang/native/issues/882
=> [native_assets_cli] Move non-`build.dart` code to `package:native_assets_builder`

pkgs/ffigen/CHANGELOG.md, pkgs/ffigen/pubspec.yaml
I believe `-wip` is the new normal.
'wip' indicates something that will not be released until the version number is changed.
'dev' can be released as a dev release.
=> [ffigen] Use `-wip` instead of `-dev` semantic versioning

pkgs/native_assets_cli/CHANGELOG.md, pkgs/native_assets_cli/lib/native_assets_cli_internal.dart, pkgs/native_assets_cli/pubspec.yaml
Introduces `pkg/native_assets_cli/native_assets_cli_internal.dart` and bumps the version.
* https://github.com/dart-lang/native/pull/885#issuecomment-1885284368
=> [native_assets_cli] v0.4.0

pkgs/native_toolchain_c/CHANGELOG.md, pkgs/native_toolchain_c/pubspec.yaml
This is needed before we can bump `native_assets_cli` in any packages using `native_toolchain_c`.
=> [native_toolchain_c] Bump native_assets_cli to 0.4.0

pkgs/native_assets_cli/CHANGELOG.md, pkgs/native_assets_cli/lib/src/api/build_output.dart, pkgs/native_assets_cli/pubspec.yaml
Release a version with a smaller API before starting to do breaking changes to the API.
=> [native_assets_cli] Release 0.4.1

.github/workflows/native.yaml, pkgs/native_assets_builder/test/data/dart_app/pubspec_overrides.yaml, pkgs/native_assets_builder/test/data/manifest.yaml, pkgs/native_assets_builder/test/data/some_dev_dep/pubspec_overrides.yaml, pkgs/native_assets_cli/example/native_add_app/pubspec_overrides.yaml, pkgs/native_toolchain_c/CHANGELOG.md, pkgs/native_toolchain_c/pubspec.yaml, tools/check_pubspec_overrides.dart
I probably should not have used 'skip-breaking-change' on https://github.com/dart-lang/native/pull/885. 🤓 
```
SEVERE: 2024-01-15 10:29:49.412987: /home/runner/.pub-cache/hosted/pub.dev/native_toolchain_c-0.3.4/lib/src/cbuilder/compiler_resolver.dart:36:23: Error: Member not found: 'ccConfigKeyFull'.
SEVERE: 2024-01-15 10:29:49.413145:       CCompilerConfig.ccConfigKeyFull,
```
Creating a patch release to patch this up.
Probably the CI will keep failing until we hit merge and then publish.
=> [native_toolchain_c] Remove private dependency use

.github/workflows/ffi.yaml, pkgs/ffi/.gitignore, pkgs/ffi/AUTHORS, pkgs/ffi/CHANGELOG.md, pkgs/ffi/LICENSE, pkgs/ffi/README.md, pkgs/ffi/analysis_options.yaml, pkgs/ffi/example/main.dart, pkgs/ffi/lib/ffi.dart, pkgs/ffi/lib/src/allocation.dart, pkgs/ffi/lib/src/arena.dart, pkgs/ffi/lib/src/utf16.dart, pkgs/ffi/lib/src/utf8.dart, pkgs/ffi/pubspec.yaml, pkgs/ffi/test/allocation_test.dart, pkgs/ffi/test/arena_test.dart, pkgs/ffi/test/utf16_test.dart, pkgs/ffi/test/utf8_test.dart
> [!CAUTION]
> _Do NOT squash merge!_
Followed the instructions from https://github.com/dart-lang/tools/pull/100 and https://github.com/dart-lang/native/pull/545.
Executed commands:
1. Move everything to `pkgs/ffi/`
```
git filter-repo --path-rename :pkgs/ffi/
```
2. Move `.github` related files to their correct path and remove existing files.
```
git filter-repo --path-rename-match pkgs/ffi/.github/:.github/
git filter-repo --path .github/dependabot.yml --invert-path
```
3. Change the workflow name.
```
git filter-repo --path-rename-match .github/workflows/test-package.yml:.github/workflows/ffi.yaml
```
4. Add `[ffi] ` to the beginning of every commit message and change the issue/PR numbers to the correct link in the `jnigen` repo.
```
git filter-repo --replace-message msgreplacement
``` …
=> Merge ffi package

.github/workflows/ffi.yaml, README.md, pkgs/ffi/CHANGELOG.md, pkgs/ffi/README.md, pkgs/ffi/pubspec.yaml
* Update repository in pubspec.yaml to point to the new location.
* Bump version so we can release to pub so the readme there points to this repo.
* Add to toplevel readme
* Update badge urls
* Fix workflow name
* Add issue template
=> [ffi] Cleanup after move and bump to v2.1.2

pkgs/native_assets_builder/CHANGELOG.md, pkgs/native_assets_builder/lib/src/model/asset.dart, pkgs/native_assets_builder/pubspec.yaml, pkgs/native_assets_builder/test/model/asset_test.dart
It's being used in the Dart SDK, which I forgot about when deleting it. (It was deleted in https://github.com/dart-lang/native/pull/881, rather than moved.)
We need it back in order to roll.
=> [native_assets_builder] Add `AssetRelativePath` back in

pkgs/native_assets_cli/.gitignore, pkgs/native_assets_cli/CHANGELOG.md, pkgs/native_assets_cli/dartdoc_options.yaml, pkgs/native_assets_cli/lib/native_assets_cli_internal.dart, pkgs/native_assets_cli/pubspec.yaml
Both the internal library and the public one had the same name, confusing API doc generation.
This PR fixes the library name.
Moreover, this PR removes the API docs for the internal API so that users don't see it at all.
This should fix https://pub.dev/documentation/native_assets_cli/latest/ after merging.
I've run `dart doc` locally to verify.
=> [native_assets_cli] Fix dartdoc generation

pkgs/native_assets_cli/dartdoc_options.yaml, pkgs/native_assets_cli/lib/native_assets_cli_internal.dart
Turns out that `@nodoc` is supposed to be in the comment, not an annotation.
=> [native_assets_cli] Better fix for dartdoc

pkgs/native_assets_builder/doc/build-hook-specification.md, pkgs/native_assets_builder/doc/protocol/v1.md
=> Build hook spec

pkgs/native_assets_builder/CHANGELOG.md, pkgs/native_assets_builder/pubspec.yaml, pkgs/native_assets_builder/test_data/cyclic_package_1/pubspec.yaml, pkgs/native_assets_builder/test_data/cyclic_package_2/pubspec.yaml, pkgs/native_assets_builder/test_data/native_add/pubspec.yaml, pkgs/native_assets_builder/test_data/native_add_add_source/pubspec.yaml, pkgs/native_assets_builder/test_data/native_subtract/pubspec.yaml, pkgs/native_assets_builder/test_data/package_reading_metadata/pubspec.yaml, pkgs/native_assets_builder/test_data/package_with_metadata/pubspec.yaml, pkgs/native_assets_builder/test_data/wrong_build_output/pubspec.yaml, pkgs/native_assets_builder/test_data/wrong_build_output_2/pubspec.yaml, pkgs/native_assets_builder/test_data/wrong_build_output_3/pubspec.yaml, pkgs/native_assets_builder/test_data/wrong_namespace_asset/pubspec.yaml, pkgs/native_assets_cli/CHANGELOG.md, pkgs/native_assets_cli/example/native_add_library/pubspec.yaml, pkgs/native_assets_cli/example/use_dart_api/pubspec.yaml
Bumps native_assets_cli dependency back to 0.4.2 (0.4.3-wip only has example pubspec changes).
Also removes all the example stable versions of dependencies. I think we probably only want to support running the examples with path dependencies.
=> [native_assets_builder] Publish v0.4.0

pkgs/native_assets_builder/CHANGELOG.md, pkgs/native_assets_builder/lib/src/model/kernel_assets.dart, pkgs/native_assets_builder/pubspec.yaml
Some cleanup of the last PR that will make the Flutter PR https://github.com/flutter/flutter/pull/143472 slightly cleaner.
Changes the constructor to take an optional iterable instead of a required list.
=> [native_assets_builder] Hide `KernelAssets` field

pkgs/jni/example/pubspec.lock, pkgs/jni/lib/src/jni.dart, pkgs/jni/lib/src/jvalues.dart
Changed `elementAt` to `operator +` for `Pointer`s.
=> [jni] Fix analysis

.github/workflows/jnigen.yaml, pkgs/jnigen/CHANGELOG.md, pkgs/jnigen/example/in_app_java/lib/android_utils.dart, pkgs/jnigen/example/in_app_java/src/android_utils/android_utils.c, pkgs/jnigen/java/src/main/java/com/github/dart_lang/jnigen/apisummarizer/Main.java, pkgs/jnigen/java/src/main/java/com/github/dart_lang/jnigen/apisummarizer/disasm/AsmClassVisitor.java, pkgs/jnigen/java/src/main/java/com/github/dart_lang/jnigen/apisummarizer/disasm/AsmSummarizer.java, pkgs/jnigen/java/src/main/java/com/github/dart_lang/jnigen/apisummarizer/doclet/SummarizerDoclet.java, pkgs/jnigen/java/src/main/java/com/github/dart_lang/jnigen/apisummarizer/util/ClassFinder.java, pkgs/jnigen/java/src/main/java/com/github/dart_lang/jnigen/apisummarizer/util/JsonWriter.java, pkgs/jnigen/lib/src/elements/elements.dart, pkgs/jnigen/lib/src/summary/summary.dart, pkgs/jnigen/test/jackson_core_test/third_party/c_based/c_bindings/jackson_core.c, pkgs/jnigen/test/jackson_core_test/third_party/c_based/dart_bindings/com/fasterxml/jackson/core/JsonFactory.dart, pkgs/jnigen/test/jackson_core_test/third_party/c_based/dart_bindings/com/fasterxml/jackson/core/JsonParser.dart, pkgs/jnigen/test/jackson_core_test/third_party/dart_only/dart_bindings/com/fasterxml/jackson/core/JsonFactory.dart, pkgs/jnigen/test/jackson_core_test/third_party/dart_only/dart_bindings/com/fasterxml/jackson/core/JsonParser.dart, pkgs/jnigen/test/simple_package_test/c_based/c_bindings/simple_package.c, pkgs/jnigen/test/simple_package_test/c_based/dart_bindings/simple_package.dart, pkgs/jnigen/test/simple_package_test/dart_only/dart_bindings/simple_package.dart, pkgs/jnigen/test/summary_generation_test.dart
Fix a bug where the package would either be fully resolved by sources or classes but not by both.
Fix CI.
=> [jnigen] FixCI

pkgs/native_assets_builder/lib/src/model/kernel_assets.dart, pkgs/native_assets_builder/test/model/kernel_assets_test.dart
=> [native_assets_builder] Implement equals and hashCode on asset paths

.github/workflows/health_jnigen.yaml
Due to https://github.com/bmw-tech/dart_apitool/issues/177, every PR on JNIgen is currently failing. This is causing noise.
This PR removes the breaking change check from JNIgen and JNI.
=> [infra] Remove broken breaking bot from jnigen

pkgs/ffigen/CHANGELOG.md, pkgs/ffigen/example/objective_c/avf_audio_bindings.dart, pkgs/ffigen/example/swift/swift_api_bindings.dart, pkgs/ffigen/lib/src/code_generator/objc_block.dart, pkgs/ffigen/lib/src/code_generator/objc_built_in_functions.dart, pkgs/ffigen/lib/src/code_generator/objc_interface.dart, pkgs/ffigen/test/native_objc_test/automated_ref_count_test.dart, pkgs/ffigen/test/native_objc_test/block_test.dart
`retainAndReturnPointer` was private before, and used for passing around objects in blocks. `castFromPointer` already exists for `ObjCObject`s, I'm just adding it to blocks. I found these useful when prototyping https://github.com/liamappelbe/web_kit_plugin. I didn't end up using them in the final demo, but they're good escape hatches to have anyway.
=> [ffigen] Expose retainAndReturnPointer and add castFromPointer to Blocks

pkgs/jni/CHANGELOG.md, pkgs/jni/lib/src/errors.dart, pkgs/jni/lib/src/jobject.dart, pkgs/jni/test/jobject_test.dart
Alternative considered:
Instead of assertion, we could add a `unsafe = false` named parameter to `castTo` and throw an `JClassCastError` instead.
Reason against going with it: This forcefully adds a call to `instanceof` but with assertion, we don't have any overhead in production while still getting the benefit while development.
Closes #986.
=> Add assert to castTo

pkgs/jni/CHANGELOG.md, pkgs/jni/src/dartjni.c
`jniEnv` could be null before calling `attachThread`, even for getting the function pointer.
Might fix https://github.com/dart-lang/http/issues/1152.
=> Fix getID bug

pkgs/native_assets_cli/example/local_asset/hook/build.dart, pkgs/native_assets_cli/example/native_add_library/hook/build.dart, pkgs/native_assets_cli/example/use_dart_api/hook/build.dart, pkgs/native_assets_cli/test/example/local_asset_test.dart, pkgs/native_assets_cli/test/example/native_add_library_test.dart
The changes rolled into the Dart SDK, so we can now update the examples.
(The changes have not yet been rolled into Flutter, so the examples will fail in Flutter until we do.)
* https://github.com/dart-lang/native/issues/823
=> [native_assets_cli] Examples `build.dart` -> `hook/build.dart`

pkgs/native_toolchain_c/CHANGELOG.md, pkgs/native_toolchain_c/lib/src/cbuilder/cbuilder.dart, pkgs/native_toolchain_c/pubspec.yaml
* https://github.com/dart-lang/native/issues/1049
=> [native_toolchain_c] Output an `Asset.file` in dry run

pkgs/native_assets_cli/CHANGELOG.md, pkgs/native_assets_cli/lib/src/api/native_code_asset.dart, pkgs/native_assets_cli/pubspec.yaml
Closes: https://github.com/dart-lang/native/issues/1049
=> [native_assets_cli] Improve documentation for `DynamicLoadingBundled`

pkgs/ffigen/README.md
That instruction is unnecessary, and can lead to version skew: https://github.com/dart-lang/native/issues/1075
=> Remove `brew install llvm` instruction from mac setup

pkgs/jnigen/CHANGELOG.md, pkgs/jnigen/pubspec.yaml
The [0.2.0 release](https://pub.dev/packages/cli_config/changelog#020) didn't change anything that jnigen depends on.
=> [jnigen] Expand cli_config constraint

pkgs/ffigen/CHANGELOG.md, pkgs/ffigen/example/libclang-example/config.yaml, pkgs/ffigen/lib/src/config_provider/config_types.dart, pkgs/ffigen/test/config_tests/compiler_opts_test.dart, pkgs/ffigen/test/native_test/config.yaml, pkgs/ffigen/tool/libclang_config.yaml
Closes: https://github.com/dart-lang/native/issues/1073
=> [ffigen] Add compiler option `-Wno-nullability-completeness` by default

pkgs/jni/example/pubspec.lock, pkgs/jni/ffigen.yaml, pkgs/jni/lib/src/jni.dart, pkgs/jni/src/third_party/global_jni_env.c, pkgs/jni/src/third_party/global_jni_env.h, pkgs/jni/tool/wrapper_generators/generate_c_extensions.dart, pkgs/jnigen/example/in_app_java/lib/android_utils.dart, pkgs/jnigen/example/pdfbox_plugin/lib/src/third_party/org/apache/pdfbox/pdmodel/PDDocument.dart, pkgs/jnigen/example/pdfbox_plugin/lib/src/third_party/org/apache/pdfbox/pdmodel/PDDocumentInformation.dart, pkgs/jnigen/example/pdfbox_plugin/lib/src/third_party/org/apache/pdfbox/text/PDFTextStripper.dart, pkgs/jnigen/lib/src/bindings/dart_generator.dart, pkgs/jnigen/test/jackson_core_test/third_party/c_based/dart_bindings/com/fasterxml/jackson/core/JsonFactory.dart, pkgs/jnigen/test/jackson_core_test/third_party/c_based/dart_bindings/com/fasterxml/jackson/core/JsonParser.dart, pkgs/jnigen/test/jackson_core_test/third_party/c_based/dart_bindings/com/fasterxml/jackson/core/JsonToken.dart, pkgs/jnigen/test/jackson_core_test/third_party/dart_only/dart_bindings/com/fasterxml/jackson/core/JsonFactory.dart, pkgs/jnigen/test/jackson_core_test/third_party/dart_only/dart_bindings/com/fasterxml/jackson/core/JsonParser.dart, pkgs/jnigen/test/jackson_core_test/third_party/dart_only/dart_bindings/com/fasterxml/jackson/core/JsonToken.dart, pkgs/jnigen/test/kotlin_test/dart_only/dart_bindings/kotlin.dart, pkgs/jnigen/test/simple_package_test/c_based/dart_bindings/simple_package.dart, pkgs/jnigen/test/simple_package_test/dart_only/dart_bindings/simple_package.dart
This is part one of #660. 
Ignore the numerous `if (!isCBased)`s, I didn't separate the concerns much, since I wanted to remove C based bindings anyways.
For now I'm using the larger types like `Int64` and `Double`, for this to work on my machine. Once the fix for https://github.com/dart-lang/sdk/issues/55471 lands in stable, we can change this. Not sure if this workaround works everywhere, will wait for CI run. – Seems to be working!
I will add to the changelog in the second PR when removing the C based bindings completely.
=> [jnigen] Use varargs for dartonly method calls

.github/workflows/jnigen.yaml, pkgs/jni/CHANGELOG.md, pkgs/jni/lib/src/jarray.dart, pkgs/jni/lib/src/third_party/global_env_extensions.dart, pkgs/jni/lib/src/third_party/jni_bindings_generated.dart, pkgs/jni/src/dartjni.c, pkgs/jni/src/dartjni.h, pkgs/jni/test/jarray_test.dart
* Close #990
* Convert the return type of `operator []` of `JArray<jchar>` to `int`, to be more consistent with the `getRange` return type. Similarly `operator []=` gets an `int` now
* Remove some unused functions in `dartjni.c`
* Use `.asTypedList(len).setRange` in `setRange` to be more efficient (~5x faster on my machine)
* Close #1097 – Improve the performance of`JArray`'s `operator []=` (~70% faster on my machine)
=> [jnigen] Add `getRange` method to `JArray<JPrimitive>` and change the dart equivalent type for `JArray<jchar>` to `int`

pkgs/jnigen/CHANGELOG.md, pkgs/jnigen/java/src/main/java/com/github/dart_lang/jnigen/apisummarizer/SummarizerOptions.java, pkgs/jnigen/lib/src/summary/summary.dart
Close #877
Character `;` in Windows with `ja-JP` locale was treated as the end of the command. This was not the case in `en-US` locale so we didn't catch that. Thanks to @glanium for reporting this.
The fix is to wrap the paths in double quotes.
Also printing the errors in `stderr` instead of `stdout` so users can actually see what is wrong.
=> [jnigen] Fix summarizer and improve errors

pkgs/objective_c/lib/objective_c.dart, pkgs/objective_c/lib/src/ns_data.dart, pkgs/objective_c/test/nsdata_test.dart
---
<details>
Note that many Dart repos have a weekly cadence for reviewing PRs - …
=> Add helper methods for NSData

.github/workflows/ffigen_weekly.yml
`macos-latest` is now arm64. So in order to also have x64 coverage, swap the weekly bot to be an `x64` bot.
* https://github.com/dart-lang/native/issues/1115#issuecomment-2088093374
=> [infra] Swap weekly bot to x64

.github/workflows/native.yaml, pkgs/native_assets_builder/test_data/dart_app/bin/dart_app.dart, pkgs/native_assets_cli/example/use_dart_api/test/use_dart_api_test.dart
The CI is currently red, this should fix it.
* Some analysis errors (not sure why example are now checked but weren't before)
* https://github.com/dart-lang/native/issues/1115
=> [infra] Fix CI

pkgs/jni/CHANGELOG.md, pkgs/jnigen/CHANGELOG.md, pkgs/jnigen/lib/src/summary/summary.dart
Trying again, this time using an environment variable. This seems to be working on my machine.
Closes #1118
@glanium Please check if this works for you.
**The branch is now `fix-encoding-2`**
Use this dev dependency to test:
```yaml
jnigen:
git:
url: https://github.com/dart-lang/native
ref: fix-encoding-2
path: pkgs/jnigen/
```
=> [jnigen] Use utf-8 for standard error and standard out encoding

pkgs/jni/android/src/main/java/com/github/dart_lang/jni/JniPlugin.java, pkgs/jni/example/lib/main.dart
Some functionalities were broken after the refactor. This fixes it.
We need to add emulator tests to catch this in the future, I see that flutter samples and `package:http` have this setup in their CI. Tracking this in #1155.
=> [jni] Fix android example

pkgs/native_assets_builder/CHANGELOG.md, pkgs/native_assets_builder/lib/native_assets_builder.dart, pkgs/native_assets_builder/lib/src/build_runner/build_runner.dart, pkgs/native_assets_builder/lib/src/model/build_dry_run_result.dart, pkgs/native_assets_builder/lib/src/model/build_result.dart, pkgs/native_assets_builder/lib/src/model/hook_result.dart, pkgs/native_assets_builder/lib/src/model/link_dry_run_result.dart, pkgs/native_assets_builder/lib/src/model/link_result.dart, pkgs/native_assets_builder/test/build_runner/build_runner_build_dry_run_test.dart, pkgs/native_assets_builder/test/build_runner/build_runner_cycle_test.dart, pkgs/native_assets_builder/test/build_runner/build_runner_reusability_test.dart, pkgs/native_assets_builder/test/build_runner/helpers.dart, pkgs/native_assets_builder/test/build_runner/link_dry_run_test.dart, pkgs/native_assets_builder/test_data/manifest.yaml, pkgs/native_assets_builder/test_data/no_asset_for_link/hook/link.dart, pkgs/native_assets_builder/test_data/no_asset_for_link/pubspec.yaml, pkgs/native_assets_cli/lib/src/model/hook.dart, pkgs/native_assets_cli/lib/src/model/hook_config.dart, pkgs/native_assets_cli/lib/src/model/hook_output.dart, pkgs/native_assets_cli/test/model/link_config_test.dart
In order to support link hooks in Flutter (https://github.com/flutter/flutter/issues/146263), we need dry run support for link hooks.
`package:native_assets_builder`
* added `NativeAssetsBuildRunner.linkDryRun` https://github.com/dart-lang/native/issues/1134
* `NativeAssetsBuildRunner.link` add missing `linkModePreference` param.
* `NativeAssetsBuildRunner.dryRun` renamed to `buildDryRun`
* Link hooks that do not have any assets for them to be linked, are no longer run.
* Link hooks are no longer run in the same topological order as build hooks, they are unordered.
`package:native_assets_cli`
* Removed `HookConfig.configFile`. It's perfectly fine for the native_assets_builder to give an arbitrary file name. (It defaults to `config.json` both for link and build hooks. They are in separate …
=> [native_assets_builder] Add dry run for link.dart

pkgs/native_assets_cli/CHANGELOG.md, pkgs/native_assets_cli/pubspec.yaml
We need a publishing round of the `native_*` packages for Flutter.
* https://github.com/flutter/flutter/issues/146263
=> [native_assets_cli] Publish 0.6.0

.github/workflows/ffigen.yml, .github/workflows/jnigen.yaml, .github/workflows/native.yaml, .github/workflows/objective_c.yaml
Unify the coverage flag names:
* Remove `_test`.
* Only mention OS if run on multiple OSes.
* Sort carryforward flag names alphabetically.
I didn't make any logic changes in this PR. So likely coverage is still broken.
=> [infra] Unify coveralls flag names

pkgs/ffigen/lib/src/header_parser/parser.dart, pkgs/ffigen/lib/src/header_parser/sub_parsers/compounddecl_parser.dart, pkgs/ffigen/lib/src/header_parser/sub_parsers/enumdecl_parser.dart, pkgs/ffigen/lib/src/header_parser/sub_parsers/function_type_param_parser.dart, pkgs/ffigen/lib/src/header_parser/sub_parsers/functiondecl_parser.dart, pkgs/ffigen/lib/src/header_parser/sub_parsers/macro_parser.dart, pkgs/ffigen/lib/src/header_parser/sub_parsers/objcinterfacedecl_parser.dart, pkgs/ffigen/lib/src/header_parser/sub_parsers/unnamed_enumdecl_parser.dart, pkgs/ffigen/lib/src/header_parser/translation_unit_parser.dart, pkgs/ffigen/lib/src/header_parser/utils.dart
Now that `NativeCallable.isolateLocal` supports lambdas, we can greatly simplify all the cursor visitors.
- Added `CXCursor.visitChildren`, `visitChildrenMayBreak`, and `visitChildrenMayRecurse`. Which are thin wrappers around `clang_visitChildren`, accepting Dart functions rather than native function pointers.
- Also added `findChildWithKind` and `hasChildWithKind`, which are built on top of those.
- Replaced all existing `clang_visitChildren` calls with calls to these new visitors.
- Since the new visitors take arbitrary Dart functions, we can delete all the globals and stacks that were used to pass args and get results from the old static visitor functions.
- I was also able to delete some of the helper classes that only existed to pass around these args and returns.
=> Refactor cursor visitors

.github/ISSUE_TEMPLATE/swift2objc.md, .github/ISSUE_TEMPLATE/swiftgen.md, .github/labeler.yml, .github/workflows/objective_c.yaml, .github/workflows/swift2objc.yaml, pkgs/swiftgen/swift2objc/lib/src/ast/_core/interfaces/enum_declaration.dart, pkgs/swiftgen/swift2objc/pubspec.yaml
Workflow that checks formatting and runs analysis. We'll add a job to run tests when we have some.
Also added auto-labeler rules and issue templates for both swift2objc and swiftgen.
Fixes https://github.com/dart-lang/native/issues/1176
=> Infra for swift2objc

pkgs/jni/android/src/main/java/com/github/dart_lang/jni/JniPlugin.java
Fixes #1204.
Tested with `flutter run --debug` in the `jni` example app with the changes in https://github.com/flutter/engine/pull/52022 applied. 
---
<details>
- Changes to packages require …
=> Remove un-needed registerWith method from `jni`

pkgs/jni/lib/internal_helpers_for_jnigen.dart, pkgs/jni/tool/wrapper_generators/generate_dart_extensions.dart, pkgs/jnigen/CHANGELOG.md, pkgs/jnigen/example/in_app_java/lib/android_utils.dart, pkgs/jnigen/example/notification_plugin/lib/notifications.dart, pkgs/jnigen/example/pdfbox_plugin/lib/src/third_party/org/apache/pdfbox/pdmodel/PDDocument.dart, pkgs/jnigen/example/pdfbox_plugin/lib/src/third_party/org/apache/pdfbox/text/PDFTextStripper.dart, pkgs/jnigen/lib/src/bindings/dart_generator.dart, pkgs/jnigen/lib/src/elements/elements.dart, pkgs/jnigen/pubspec.yaml, pkgs/jnigen/test/jackson_core_test/third_party/bindings/com/fasterxml/jackson/core/JsonFactory.dart, pkgs/jnigen/test/jackson_core_test/third_party/bindings/com/fasterxml/jackson/core/JsonParser.dart, pkgs/jnigen/test/simple_package_test/bindings/simple_package.dart
Closes #1191. The issue was that using types shorter than int32 in varargs is undefined behavior. Also float is not supported; defaulting to double.
Fixed the macOS arm64 problem in the mean time by introducing an `AbiSpecificInteger` in `package:jni`.
=> [jnigen] Fix generated vararg types

.github/workflows/native.yaml
Workaround for:
* https://github.com/dart-lang/native/issues/1232
So that the CI can be green in the meantime.
Also, let's run dev builds for Windows and MacOS as well! It might catch OS-specific issues on Dart SDK changes.
=> [infra] pin dev release for `package:native_x`

pkgs/native_toolchain_c/CHANGELOG.md, pkgs/native_toolchain_c/lib/src/cbuilder/cbuilder.dart, pkgs/native_toolchain_c/lib/src/cbuilder/run_cbuilder.dart, pkgs/native_toolchain_c/test/cbuilder/cbuilder_cross_ios_test.dart, pkgs/native_toolchain_c/test/cbuilder/cbuilder_cross_macos_host_test.dart, pkgs/native_toolchain_c/test/cbuilder/objective_c_test.dart, pkgs/native_toolchain_c/test/cbuilder/testfiles/add_objective_c/src/add.m
Adds Apple clang flags for compiling Objective-C with the `CBuilder`.
Issue:
* https://github.com/dart-lang/native/issues/1227
Also pins the dev CI to the latest working version:
* https://github.com/dart-lang/sdk/issues/56080
=> [native_toolchain_c] `CBuilder` Objective-C clang flags

pkgs/ffigen/lib/src/code_generator/compound.dart, pkgs/ffigen/lib/src/code_generator/library.dart, pkgs/ffigen/lib/src/code_generator/objc_block.dart, pkgs/ffigen/lib/src/code_generator/objc_nullable.dart, pkgs/ffigen/lib/src/code_generator/struct.dart, pkgs/ffigen/lib/src/code_generator/union.dart, pkgs/ffigen/lib/src/code_generator/writer.dart, pkgs/ffigen/lib/src/config_provider/spec_utils.dart, pkgs/ffigen/lib/src/header_parser/parser.dart, pkgs/ffigen/lib/src/header_parser/sub_parsers/compounddecl_parser.dart, pkgs/ffigen/test/native_objc_test/block_config.yaml, pkgs/ffigen/test/native_objc_test/block_test.dart, pkgs/ffigen/test/native_objc_test/block_test.h, pkgs/ffigen/test/native_objc_test/block_test.m
#1203 added a small ObjC trampoline to some listener blocks. This PR fixes 3 bugs in that generated ObjC code that were found while working on the [large ObjC integration test](https://github.com/dart-lang/native/pull/1183), and also reported by @brianquinlan.
- For listener blocks with nullable arguments, the `_Nullable` annotation was being placed in the wrong spot (`DummyObject* arg0 _Nullable` instead of `DummyObject*  _Nullable arg0`). Fixes #1230.
- If a struct is declared like `struct Foo {}` instead of `typedef struct {} Foo`, we have to refer to it (in ObjC code) as `struct Foo` instead of just `Foo`. Same for unions. This distinction wasn't surfaced at all in the existing `Struct`/`Union` class.
- The type spelling string of the declaration contains this distinction, being …
=> Fixes and tests for listener block native bindings

pkgs/native_assets_cli/CHANGELOG.md, pkgs/native_assets_cli/pubspec.yaml
Publishing a version so that it can be used by `native_toolchain_rust`.
=> [native_assets_cli] Publish 0.6.1

pkgs/ffigen/lib/src/code_generator/objc_protocol.dart, pkgs/ffigen/test/native_objc_test/protocol_test.dart, pkgs/objective_c/lib/src/internal.dart, pkgs/objective_c/lib/src/protocol_builder.dart
Fixes #1231 by implementing 2 ergonomic improvements:
- Add an `implement`/`implementAsListener` method to `ObjCProtocolMethod`/`ObjCProtocolListenableMethod` that takes the correct function type. The function type is now a type param of the method class.
- This means the function type is checked/inferred at compile time rather than just checked at runtime.
- From the caller's perspective, they basically just have to swap the builder and method objects: `builder.implementMethod(MyProtocol.myMethod, function)` -> `MyProtocol.myMethod.implement(builder, function)`
- Also moved the method classes to the same file as `ObjCProtocolBuilder`, since they're closely related.
- Implemented @brianquinlan's suggestion of adding a `implementAsListener`/`addToBuilderAsListener` method that implements …
=> Improve ergonomics of protocol bindings

pkgs/ffigen/CHANGELOG.md, pkgs/ffigen/README.md, pkgs/ffigen/ffigen.schema.json, pkgs/ffigen/lib/src/code_generator/typealias.dart, pkgs/ffigen/lib/src/config_provider/config.dart, pkgs/ffigen/lib/src/header_parser/translation_unit_parser.dart, pkgs/ffigen/lib/src/strings.dart, pkgs/ffigen/test/collision_tests/expected_bindings/_expected_decl_decl_collision_bindings.dart, pkgs/ffigen/test/header_parser_tests/expected_bindings/_expected_typedef_bindings.dart, pkgs/ffigen/test/header_parser_tests/typedef.h, pkgs/ffigen/test/header_parser_tests/typedef_test.dart
---
<details>
- Most changes should add an entry to the changelog and may need to [rev the pubspec package version](https://github.com/dart-lang/sdk/blob/main/docs/External-Package-Maintenance.md#making-a- …
=> [ffigen] support generate unused typedefs

pkgs/native_assets_cli/CHANGELOG.md, pkgs/native_assets_cli/pubspec.yaml
Another round of rolling so we can update flutter_tools to address:
* https://github.com/dart-lang/native/issues/1252
=> [native_assets_cli] Publish 0.7.0

pkgs/native_assets_builder/pubspec.yaml, pkgs/native_assets_builder/test_data/add_asset_link/pubspec.yaml, pkgs/native_assets_builder/test_data/complex_link/pubspec.yaml, pkgs/native_assets_builder/test_data/complex_link_helper/pubspec.yaml, pkgs/native_assets_builder/test_data/cyclic_package_1/pubspec.yaml, pkgs/native_assets_builder/test_data/cyclic_package_2/pubspec.yaml, pkgs/native_assets_builder/test_data/drop_dylib_link/pubspec.yaml, pkgs/native_assets_builder/test_data/fail_on_os_sdk_version/pubspec.yaml, pkgs/native_assets_builder/test_data/fail_on_os_sdk_version_link/pubspec.yaml, pkgs/native_assets_builder/test_data/fail_on_os_sdk_version_linker/pubspec.yaml, pkgs/native_assets_builder/test_data/native_add/pubspec.yaml, pkgs/native_assets_builder/test_data/native_add_add_source/pubspec.yaml, pkgs/native_assets_builder/test_data/native_subtract/pubspec.yaml, pkgs/native_assets_builder/test_data/no_asset_for_link/pubspec.yaml, pkgs/native_assets_builder/test_data/package_reading_metadata/pubspec.yaml, pkgs/native_assets_builder/test_data/package_with_metadata/pubspec.yaml, pkgs/native_assets_builder/test_data/simple_data_asset/pubspec.yaml, pkgs/native_assets_builder/test_data/simple_link/pubspec.yaml, pkgs/native_assets_builder/test_data/wrong_build_output/pubspec.yaml, pkgs/native_assets_builder/test_data/wrong_build_output_2/pubspec.yaml, pkgs/native_assets_builder/test_data/wrong_build_output_3/pubspec.yaml, pkgs/native_assets_builder/test_data/wrong_namespace_asset/pubspec.yaml, pkgs/native_assets_cli/CHANGELOG.md, pkgs/native_assets_cli/example/build/local_asset/pubspec.yaml, pkgs/native_assets_cli/example/build/native_add_library/pubspec.yaml, pkgs/native_assets_cli/example/build/use_dart_api/pubspec.yaml, pkgs/native_assets_cli/example/link/package_with_assets/pubspec.yaml, pkgs/native_assets_cli/pubspec.yaml, pkgs/native_toolchain_c/CHANGELOG.md, pkgs/native_toolchain_c/pubspec.yaml
Another round of rolling so we can update flutter_tools to address:
* https://github.com/dart-lang/native/issues/1252
=> [native_toolchain_c] Publish 0.5.1

pkgs/native_assets_builder/CHANGELOG.md, pkgs/native_assets_builder/pubspec.yaml, pkgs/native_assets_builder/test_data/add_asset_link/pubspec.yaml, pkgs/native_assets_builder/test_data/drop_dylib_link/pubspec.yaml, pkgs/native_assets_builder/test_data/native_add/pubspec.yaml, pkgs/native_assets_builder/test_data/native_add_add_source/pubspec.yaml, pkgs/native_assets_builder/test_data/native_subtract/pubspec.yaml, pkgs/native_assets_cli/example/build/native_add_library/pubspec.yaml, pkgs/native_assets_cli/example/build/use_dart_api/pubspec.yaml
Another round of rolling so we can update flutter_tools to address:
* https://github.com/dart-lang/native/issues/1252
=> [native_assets_builder] Publish 0.8.0

pkgs/ffi/analysis_options.yaml, pkgs/ffigen/analysis_options.yaml, pkgs/ffigen/lib/src/config_provider/config.dart, pkgs/ffigen/lib/src/config_provider/config_spec.dart, pkgs/objective_c/example/pubspec.lock
Stop inferring dynamic type arguments.
This PR makes `ConfigValue` default to `Object?` as it already was doing in various places. And `Map` to `Map<dynamic, dynamic>` as it already was in various places.
=> [ffigen] Enable strict types

pkgs/native_assets_builder/CHANGELOG.md, pkgs/native_assets_builder/test/build_runner/link_dry_run_test.dart, pkgs/native_assets_builder/test/build_runner/link_test.dart, pkgs/native_assets_builder/test_data/complex_link/hook/build.dart, pkgs/native_assets_builder/test_data/complex_link_helper/hook/build.dart, pkgs/native_assets_builder/test_data/drop_dylib_link/hook/build.dart, pkgs/native_assets_builder/test_data/native_add/hook/build.dart, pkgs/native_assets_builder/test_data/native_add_add_source/hook/build.dart, pkgs/native_assets_builder/test_data/native_subtract/hook/build.dart, pkgs/native_assets_builder/test_data/simple_data_asset/bin/deep_modify_data_asset.dart.debug, pkgs/native_assets_builder/test_data/simple_data_asset/bin/modify_data_asset.dart.debug, pkgs/native_assets_builder/test_data/simple_data_asset/bin/simple_data_asset.dart.debug, pkgs/native_assets_builder/test_data/simple_data_asset/hook/build.dart, pkgs/native_assets_builder/test_data/simple_link/hook/build.dart, pkgs/native_assets_cli/CHANGELOG.md, pkgs/native_assets_cli/example/build/local_asset/hook/build.dart, pkgs/native_assets_cli/example/build/use_dart_api/hook/build.dart, pkgs/native_assets_cli/example/link/package_with_assets/hook/build.dart, pkgs/native_assets_cli/lib/src/api/build.dart, pkgs/native_assets_cli/lib/src/api/builder.dart, pkgs/native_assets_cli/pubspec.yaml, pkgs/native_assets_cli/test/example/local_asset_test.dart
While working on https://github.com/dart-lang/native/issues/1208, I released that most likely you'd want to report all files from the `assets/` directory as `DataAsset`s in a hook. (This also means that there's implicitly a `dependency` on the directory itself.)
This PR also cleans up the remaining dart files listed in `dependencies`.
=> [native_*] Hooks with `DataAsset`s read from disk

pkgs/ffigen/CHANGELOG.md, pkgs/ffigen/pubspec.yaml, pkgs/objective_c/CHANGELOG.md, pkgs/objective_c/pubspec.yaml
These need to be published at about the same time as ffigen 13.0.0 generates ObjC bindings that depend on new features in objective_c 1.1.0.
=> Prepare to publish ffigen 13.0.0 and objective_c 1.1.0

pkgs/native_toolchain_c/CHANGELOG.md, pkgs/native_toolchain_c/lib/src/cbuilder/linker_options.dart
Having a set swallowed all the necessary `-u`s for each symbol.
---
<details>
- Changes to packages require [corresponding tests](https://github.com/dart-lang/.github/blob/main/CONTRIBUTING.md#Testing …
=> Fix internal bug in `LinkerOptions`

pkgs/native_assets_cli/lib/src/locking/locking.dart
Addresses these comments:
* https://github.com/dart-lang/native/pull/1384#pullrequestreview-2221149994
=> [native_assets_builder] Lock the build directory - fixes

pkgs/ffi/CHANGELOG.md, pkgs/ffi/lib/src/allocation.dart, pkgs/ffi/pubspec.yaml
Closes: https://github.com/dart-lang/native/issues/1401
I don't think we want to fix the API leak, rather we'd like the public API be `Allocator` which has a `nativeFree`:
* https://github.com/dart-lang/sdk/issues/55571
=> [ffi] Use `@Native`s for process lookup

pkgs/jnigen/CHANGELOG.md, pkgs/jnigen/README.md, pkgs/jnigen/example/in_app_java/lib/android_utils.dart, pkgs/jnigen/example/kotlin_plugin/lib/kotlin_bindings.dart, pkgs/jnigen/example/notification_plugin/lib/notifications.dart, pkgs/jnigen/example/pdfbox_plugin/lib/src/third_party/org/apache/pdfbox/pdmodel/PDDocument.dart, pkgs/jnigen/example/pdfbox_plugin/lib/src/third_party/org/apache/pdfbox/pdmodel/PDDocumentInformation.dart, pkgs/jnigen/example/pdfbox_plugin/lib/src/third_party/org/apache/pdfbox/text/PDFTextStripper.dart, pkgs/jnigen/lib/src/bindings/dart_generator.dart, pkgs/jnigen/pubspec.yaml, pkgs/jnigen/test/jackson_core_test/third_party/bindings/com/fasterxml/jackson/core/JsonFactory.dart, pkgs/jnigen/test/jackson_core_test/third_party/bindings/com/fasterxml/jackson/core/JsonParser.dart, pkgs/jnigen/test/jackson_core_test/third_party/bindings/com/fasterxml/jackson/core/JsonToken.dart, pkgs/jnigen/test/kotlin_test/bindings/kotlin.dart, pkgs/jnigen/test/simple_package_test/bindings/simple_package.dart
Fixes https://github.com/dart-lang/native/issues/1408
---
<details>
- Most changes should add an entry to the changelog and may need to [rev the pubspec package …
=> Correctly escape comments that may contain tags

pkgs/ffigen/CHANGELOG.md, pkgs/ffigen/lib/src/code_generator/global.dart, pkgs/ffigen/test/native_objc_test/global_config.yaml, pkgs/ffigen/test/native_objc_test/global_native_config.yaml, pkgs/ffigen/test/native_objc_test/global_native_test.dart, pkgs/ffigen/test/native_objc_test/global_native_test.m, pkgs/ffigen/test/native_objc_test/global_test.dart, pkgs/ffigen/test/native_objc_test/global_test.h, pkgs/ffigen/test/native_objc_test/global_test.m
Global variables using ObjC types (interfaces or blocks) will now use the correct Dart wrapper types, instead of the raw C-style pointers.
Fixes https://github.com/dart-lang/native/issues/1418
=> [ffigen] Support ObjC objects in global variables

pkgs/ffigen/CHANGELOG.md, pkgs/ffigen/lib/src/code_generator/imports.dart, pkgs/ffigen/lib/src/code_generator/objc_block.dart, pkgs/ffigen/lib/src/code_generator/objc_built_in_functions.dart, pkgs/ffigen/lib/src/code_generator/objc_interface.dart, pkgs/ffigen/lib/src/code_generator/objc_protocol.dart, pkgs/ffigen/lib/src/code_generator/type.dart, pkgs/ffigen/lib/src/code_generator/typealias.dart, pkgs/ffigen/lib/src/code_generator/writer.dart, pkgs/ffigen/test/native_objc_test/block_inherit_config.yaml, pkgs/ffigen/test/native_objc_test/block_inherit_test.dart, pkgs/ffigen/test/native_objc_test/block_inherit_test.m, pkgs/ffigen/test/native_objc_test/block_test.dart, pkgs/ffigen/test/native_objc_test/global_native_config.yaml, pkgs/ffigen/test/native_objc_test/global_native_test.dart, pkgs/ffigen/test/native_objc_test/global_native_test.h, pkgs/ffigen/test/native_objc_test/global_test.dart, pkgs/ffigen/test/native_objc_test/protocol_test.dart, pkgs/ffigen/test/native_objc_test/static_func_native_test.dart, pkgs/ffigen/test/native_objc_test/static_func_test.dart, pkgs/ffigen/test/native_objc_test/util.dart, pkgs/objective_c/CHANGELOG.md, pkgs/objective_c/lib/objective_c.dart, pkgs/objective_c/lib/src/block.dart, pkgs/objective_c/lib/src/c_bindings_generated.dart, pkgs/objective_c/lib/src/internal.dart, pkgs/objective_c/lib/src/protocol_builder.dart, pkgs/objective_c/src/objective_c.c, pkgs/objective_c/src/objective_c.h, pkgs/objective_c/src/objective_c_runtime.h
If an ObjC class `Child` inherits from `Base`, and overrides a method that accepts or returns a block, it may use a different type of block than `Base`'s method, according to certain subtyping rules. The issue is that when ffigen codegens those methods, it uses the Dart wrapper objects to represent the blocks in the method signatures, but those wrappers are essentially unrelated, so this breaks Dart's method overriding rules.
The basic idea of the fix is to add a new class to package:objective_c, `ObjCBlock`, which extends `ObjCBlockBase` and includes the block's signature as a type param. Then anywhere we were previously passing a generated block wrapper through an API, we instead pass a `ObjCBlock<signature>`. That way the subtyping rules are enforced by Dart's ordinary subtyping rules. …
=> [ffigen] Fix block inheritance issue

pkgs/ffigen/lib/src/config_provider/path_finder.dart
Use dart:io operations to list contents of a directory instead of using Process.run('ls').
---
<details> …
=> [ffigen] use listSync instead of running ls

pkgs/native_toolchain_c/test/clinker/treeshake_test.dart
We cannot assume that tests are run from the root of the package. This leads to:
```
SEVERE: 2024-08-23 06:22:38.618901: /usr/bin/arm-linux-gnueabihf-ld: cannot open linker script file test/clinker/testfiles/linker/symbols.lds: No such file or directory
```
From [log](https://logs.chromium.org/logs/dart/buildbucket/cr-buildbucket/8738809276935778721/+/u/test_results/new_test_failures__logs_).
=> [native_toolchain_c] Fix test to not assume working dir

pkgs/native_toolchain_c/test/clinker/treeshake_cross_test.dart, pkgs/native_toolchain_c/test/clinker/treeshake_helper.dart
The Dart SDK CI does not have cross-compilation toolchains installed.
We do want to run the tests that are not cross-compilation on the Dart CI, because we want to run the dartdev tests for the host OS on the Dart SDK CI.
=> [native_toolchain_c] Move cross architecture compilation into separate test

CONTRIBUTING.md
When this repo rolls into the Dart SDK, the tests are run on the Dart CI which has a bunch of extra constraints.
Unfortunately, we can't run on the Dart CI from a GitHub action, so we can't see violating those constraints on the CI here.
The next best thing is to document the constraints.
=> [doc] Document testing constraints for Dart SDK

pkgs/native_assets_builder/test/build_runner/concurrency_test.dart, pkgs/native_assets_cli/test/locking/locking_test.dart
Make locking tests way less sensitive to timing:
* Reduce the timeout time _inside_ helper processes for the locking test.
* Give the test a 10x to timeout. (We don't technically need the timeout, as normal test flow should cancel the timer. But it's nice that tests fail at some point instead of hanging.)
This should fix the flakiness on the Dart SDK CI when attempting to roll these tests in.
Additionally, add more debug prints for if the tests fail.
Flaky failures: https://dart-ci.firebaseapp.com/cl/381984/7
Success run with this PR: https://dart-ci.firebaseapp.com/cl/382180/3
=> [native_*] Make locking tests less timing sensitive

pkgs/native_toolchain_c/test/cbuilder/cbuilder_build_failure_test.dart, pkgs/native_toolchain_c/test/cbuilder/cbuilder_test.dart, pkgs/native_toolchain_c/test/cbuilder/objective_c_test.dart, pkgs/native_toolchain_c/test/clinker/build_testfiles.dart, pkgs/native_toolchain_c/test/clinker/objects_test.dart, pkgs/native_toolchain_c/test/clinker/treeshake_helper.dart, pkgs/native_toolchain_c/test/helpers.dart
After this the linker is found on the Dart SDK CI. (Unfortunately, the test then fails with https://github.com/dart-lang/native/issues/1460)
Dart SDK Run _with_ this PR:
* https://dart-ci.firebaseapp.com/cl/382181/1
=> [native_toolchain_c] Pass in archiver from environment in test - take 2

.github/workflows/native.yaml
Closes: https://github.com/dart-lang/native/issues/1154
=> Revert "[infra] Use Dart 3.3.0 as stable on Windows (#1160)"

pkgs/native_toolchain_c/lib/src/cbuilder/linker_options.dart, pkgs/native_toolchain_c/lib/src/cbuilder/run_cbuilder.dart, pkgs/native_toolchain_c/lib/src/native_toolchain/gcc.dart
Closes: https://github.com/dart-lang/native/issues/1460
* Allows any kind of gnu-like linker. (We use Clangs' `ld.lld` instead of the GCC linker on the Dart SDK CI)
* Passes the PIC/PIE flags as expected to the linker
* `-f` means forward to linker, but if we invoke linker directly, we don't need that.
* only PIE makes sense, PIC only has an effect on the compilation as far as I understand (not on linking).
Testing:
* We don't have `ld.ldd` on the GitHub CI, so we can't run a unit test here.
* If we'd do mocking of process and file system, we could have an invocation expectation: https://github.com/dart-lang/native/issues/90
* We run the test on the Dart CI [failing invocation](https://dart-ci.firebaseapp.com/cl/382384/3) -> [succeeding linking, failing on a …
=> [native_toolchain_c] Support `ld.ldd` as linker on Linux

pkgs/native_toolchain_c/test/clinker/objects_test.dart, pkgs/native_toolchain_c/test/clinker/treeshake_helper.dart, pkgs/native_toolchain_c/test/helpers.dart
We were using both `nm` and `readelf` to inspect symbols of dylibs. Apparently the `readelf` on the Dart SDK CI is pretty old and doesn't have `-C`.
```
SEVERE: 2024-08-27 06:21:38.923027: readelf: invalid option -- 'C'
```
[log](https://logs.chromium.org/logs/dart/buildbucket/cr-buildbucket/8738447274147496209/+/u/test_results/new_test_failures__logs_)
Green run on Dart CI with this PR: https://dart-ci.firebaseapp.com/cl/382384/5
=> [native_toolchain_c] Only use `nm` to inspect symbols

pkgs/ffigen/test/native_objc_test/arc_test.dart, pkgs/ffigen/test/native_objc_test/global_native_test.dart, pkgs/ffigen/test/native_objc_test/global_test.dart, pkgs/ffigen/test/native_objc_test/ref_count_test.dart
=> [ffigen] Fix flaky tests

pkgs/jni/CHANGELOG.md, pkgs/jni/android/build.gradle, pkgs/jni/pubspec.yaml, pkgs/jnigen/CHANGELOG.md, pkgs/jnigen/pubspec.yaml
Closes #1135.
Everything seems to still work without these dependencies and we don't have to keep updating them every time flutter updates them.
=> Remove Kotlin and Gradle dependencies from jnigen / publish 0.11.0

pkgs/ffigen/lib/src/code_generator/func.dart, pkgs/ffigen/lib/src/code_generator/func_type.dart, pkgs/ffigen/lib/src/code_generator/objc_block.dart, pkgs/ffigen/lib/src/code_generator/objc_built_in_functions.dart, pkgs/ffigen/lib/src/code_generator/objc_interface.dart, pkgs/ffigen/lib/src/code_generator/objc_methods.dart, pkgs/ffigen/lib/src/code_generator/objc_protocol.dart, pkgs/ffigen/lib/src/header_parser/sub_parsers/functiondecl_parser.dart, pkgs/ffigen/lib/src/header_parser/sub_parsers/objcinterfacedecl_parser.dart, pkgs/ffigen/lib/src/header_parser/type_extractor/extractor.dart, pkgs/ffigen/test/code_generator_tests/code_generator_test.dart, pkgs/ffigen/test/collision_tests/reserved_keyword_collision_test.dart, pkgs/ffigen/test/header_parser_tests/function_n_struct_test.dart, pkgs/ffigen/test/native_objc_test/arc_test.dart, pkgs/ffigen/test/native_objc_test/arc_test.m, pkgs/ffigen/test/native_objc_test/ref_count_test.dart, pkgs/ffigen/test/native_objc_test/ref_count_test.m, pkgs/ffigen/test/native_objc_test/static_func_config.yaml, pkgs/ffigen/test/native_objc_test/static_func_native_config.yaml, pkgs/ffigen/test/native_objc_test/static_func_native_test.dart, pkgs/ffigen/test/native_objc_test/static_func_test.dart, pkgs/ffigen/test/native_objc_test/static_func_test.m, pkgs/ffigen/test/rename_tests/rename_test.dart
The [`__attribute((ns_consumed))`](https://clang.llvm.org/docs/AutomaticReferenceCounting.html#consumed-parameters) annotation indicates that the method will decrement the refcount of the argument. To balance this, we have to retain the argument as we pass it into the method.
Part of #1446
=> [ffigen] Handle the argument consumed annotation

pkgs/ffigen/lib/src/code_generator/global.dart, pkgs/ffigen/lib/src/code_generator/objc_block.dart, pkgs/ffigen/lib/src/code_generator/objc_interface.dart, pkgs/ffigen/test/native_objc_test/arc_test.dart, pkgs/ffigen/test/native_objc_test/block_test.dart, pkgs/ffigen/test/native_objc_test/cast_test.dart, pkgs/ffigen/test/native_objc_test/global_native_test.dart, pkgs/ffigen/test/native_objc_test/global_test.dart, pkgs/ffigen/test/native_objc_test/isolate_test.dart, pkgs/ffigen/test/native_objc_test/protocol_test.dart, pkgs/ffigen/test/native_objc_test/ref_count_test.dart, pkgs/ffigen/test/native_objc_test/static_func_native_test.dart, pkgs/ffigen/test/native_objc_test/static_func_test.dart, pkgs/ffigen/test/native_objc_test/typedef_test.dart, pkgs/objective_c/CHANGELOG.md, pkgs/objective_c/lib/src/internal.dart, pkgs/objective_c/lib/src/objective_c_bindings_generated.dart, pkgs/objective_c/lib/src/protocol_builder.dart, pkgs/objective_c/pubspec.yaml, pkgs/objective_c/test/ns_mutable_data_test.dart, pkgs/objective_c/test/nsdata_test.dart
Remove convenience getters on `_ObjCRefHolder`, forcing `obj.pointer` etc to go through `ref` like `obj.ref.pointer`. This solves potential early GC issues where `obj` is collected while the pointer is still in use.
=> [objective_c] Force `.pointer` to go through `.ref`

pkgs/native_assets_cli/tool/dependencies.dart
Since we need a stack of PRs every time we publish, this step takes a package name as argument.
=> [tool] Swap dependencies to published at specific version

pkgs/native_assets_builder/CHANGELOG.md, pkgs/native_assets_builder/lib/src/build_runner/build_runner.dart, pkgs/native_assets_builder/test/build_runner/helpers.dart, pkgs/native_assets_builder/test/build_runner/link_dry_run_test.dart, pkgs/native_assets_builder/test/build_runner/link_test.dart, pkgs/native_assets_builder/test/build_runner/wrong_linker_test.dart, pkgs/native_assets_builder/test_data/manifest.yaml, pkgs/native_assets_builder/test_data/wrong_linker/hook/build.dart, pkgs/native_assets_builder/test_data/wrong_linker/pubspec.yaml, pkgs/native_assets_cli/CHANGELOG.md, pkgs/native_assets_cli/lib/native_assets_cli_internal.dart, pkgs/native_assets_cli/lib/src/api/build.dart, pkgs/native_assets_cli/lib/src/api/link.dart, pkgs/native_assets_cli/lib/src/validator/validator.dart, pkgs/native_assets_cli/test/example/local_asset_test.dart, pkgs/native_assets_cli/test/example/native_add_library_test.dart, pkgs/native_assets_cli/test/example/native_dynamic_linking_test.dart, pkgs/native_assets_cli/test/validator/validator_test.dart
This PR adds validation to the hook outputs in two places:
1. In the `build` and `link` methods used in hook implementations.
2. In the `native_assets_builder` after invoking the hook.
In the native assets builder we also validate that assets for linking are routed to packages that have link hooks.
Also, fixes some bugs, some tests, and examples that were violating the invariants.
Closes: https://github.com/dart-lang/native/issues/1409
Closes: https://github.com/dart-lang/native/issues/1411
=> [native_assets_*] Validator

.github/workflows/native.yaml, pkgs/native_assets_builder/CHANGELOG.md, pkgs/native_assets_builder/lib/src/build_runner/build_runner.dart, pkgs/native_assets_builder/test/build_runner/conflicting_dylib_test.dart, pkgs/native_assets_builder/test_data/manifest.yaml, pkgs/native_assets_builder/test_data/native_add_duplicate/hook/build.dart, pkgs/native_assets_builder/test_data/native_add_duplicate/pubspec.yaml, pkgs/native_assets_builder/test_data/native_add_duplicate/src/native_add.c, pkgs/native_assets_builder/test_data/native_add_duplicate/src/native_add.h, pkgs/native_assets_cli/lib/native_assets_cli_internal.dart, pkgs/native_assets_cli/lib/src/validator/validator.dart, pkgs/native_assets_cli/test/validator/validator_test.dart
On not all OSes it's easy to rename dylibs.
So, let's throw an error for now, to make it explicit that we do not allow conflicting dylib names.
Context:
* https://github.com/dart-lang/native/issues/1425
Some design decisions
* Only take file name into account. We can't rely on subdirectories, because the dylib files might not be in the output dir they might be somewhere predownloaded on disk or in the project. (Unless we mandate that dylibs always be in the output dir.) @blaugold I don't presume any of our dynamic linking use cases tries to link dylibs in different subdirectories?
* Conflicts between dylibs introduced in the build and link hook need to be done in the embedder (Dart standalone, Flutter), because `native_assets_builder` is invoked per hook by the embedder.
=> [native_assets_*] Error on conflict dylib names

pkgs/native_assets_builder/test/helpers.dart, pkgs/native_assets_builder/test/test_data/native_dynamic_linking_test.dart, pkgs/native_assets_cli/test/example/local_asset_test.dart, pkgs/native_assets_cli/test/example/native_add_library_test.dart, pkgs/native_assets_cli/test/example/native_dynamic_linking_test.dart, pkgs/native_assets_cli/test/helpers.dart
This prevents us manually having to update the command-line invocations in tests when things change.
=> [native_*] Unify `CCompilerConfig` handling in tests

pkgs/native_assets_builder/test/build_runner/conflicting_dylib_test.dart, pkgs/native_assets_builder/test_data/manifest.yaml, pkgs/native_assets_builder/test_data/native_add_duplicate/bin/native_add_duplicate.dart, pkgs/native_assets_builder/test_data/native_add_duplicate/hook/build.dart, pkgs/native_assets_builder/test_data/native_add_duplicate/hook/link.dart
A test case to be used in dartdev in https://dart-review.googlesource.com/c/sdk/+/383986.
=> [native_assets_builder] Test data for dylib name conflict

pkgs/ffigen/CHANGELOG.md, pkgs/ffigen/lib/src/code_generator/objc_nullable.dart, pkgs/ffigen/pubspec.yaml, pkgs/ffigen/test/native_objc_test/block_test.dart, pkgs/ffigen/test/native_objc_test/block_test.h, pkgs/ffigen/test/native_objc_test/block_test.m
Nullable block args were being represented as `Pointer<ObjCObject>`, so if you have multiple blocks that have the same signature after this conversion, their extension methods will collide. The fix is to represent these args as `DartWrapper?`
Fixes https://github.com/dart-lang/native/issues/1537
=> [ffigen] Fix bug in nullable block arguments

pkgs/jnigen/CHANGELOG.md, pkgs/jnigen/docs/java_differences.md, pkgs/jnigen/example/in_app_java/lib/android_utils.dart, pkgs/jnigen/example/in_app_java/lib/main.dart, pkgs/jnigen/example/kotlin_plugin/lib/kotlin_bindings.dart, pkgs/jnigen/example/notification_plugin/lib/notifications.dart, pkgs/jnigen/example/pdfbox_plugin/dart_example/bin/pdf_info.dart, pkgs/jnigen/example/pdfbox_plugin/lib/src/third_party/org/apache/pdfbox/pdmodel/PDDocument.dart, pkgs/jnigen/example/pdfbox_plugin/lib/src/third_party/org/apache/pdfbox/pdmodel/PDDocumentInformation.dart, pkgs/jnigen/example/pdfbox_plugin/lib/src/third_party/org/apache/pdfbox/text/PDFTextStripper.dart, pkgs/jnigen/lib/src/bindings/dart_generator.dart, pkgs/jnigen/lib/src/bindings/excluder.dart, pkgs/jnigen/lib/src/bindings/renamer.dart, pkgs/jnigen/lib/src/bindings/unnester.dart, pkgs/jnigen/lib/src/elements/elements.dart, pkgs/jnigen/pubspec.yaml, pkgs/jnigen/test/jackson_core_test/runtime_test_registrant.dart, pkgs/jnigen/test/jackson_core_test/third_party/bindings/com/fasterxml/jackson/core/JsonFactory.dart, pkgs/jnigen/test/jackson_core_test/third_party/bindings/com/fasterxml/jackson/core/JsonParser.dart, pkgs/jnigen/test/kotlin_test/bindings/kotlin.dart, pkgs/jnigen/test/kotlin_test/runtime_test_registrant.dart, pkgs/jnigen/test/renamer_test.dart, pkgs/jnigen/test/simple_package_test/bindings/simple_package.dart, pkgs/jnigen/test/simple_package_test/runtime_test_registrant.dart
Closes #571. 
Adding a `$K` to the end of the `K`–th overload of a method. 
To be consistent, instead of adding a zero to the end of the keywords such as `new` we add a `$`.
In short, the renaming becomes:
`foo`, `foo`, foo1`, foo1` -> `foo`, `foo$1`, `foo1`, `foo1$1`
`yield`, `yield`,  -> `yield$`, `yield$1`
Wrote a doc in `java_differences.md` explaining the renaming for method overloading.
=> Fix numeric suffix rename

pkgs/jnigen/CHANGELOG.md, pkgs/jnigen/docs/java_differences.md, pkgs/jnigen/lib/src/bindings/renamer.dart, pkgs/jnigen/lib/src/elements/elements.dart, pkgs/jnigen/test/renamer_test.dart
Address @lrhn's comments in https://github.com/dart-lang/native/pull/1530. 
Now we replace each dollar sign with two to prevent name collisions between original names and the JNIgen-renamed ones as JNIgen uses single dollar signs to address syntactic and semantic changes.
=> [jnigen] Rename names with dollar signs

pkgs/ffigen/CHANGELOG.md, pkgs/ffigen/lib/src/code_generator/utils.dart, pkgs/ffigen/lib/src/config_provider/spec_utils.dart, pkgs/ffigen/lib/src/header_parser/sub_parsers/macro_parser.dart, pkgs/ffigen/pubspec.yaml, pkgs/ffigen/test/unit_tests/normalize_path_test.dart
When I added Dart API to ffigen (#1372) I switched a bunch of strings to be Uris. This started inserting `.` into the paths in some circumstances, causing some file matching checks to fail. The fix is just to add a `p.normalize` call to our existing `normalizePath` function (we probably should have been doing this already).
I'll publish ffigen 14.0.1 after this fix, since it's a regression.
Fixes #1543
=> [ffigen] Fix path normalization bug

pkgs/jnigen/CHANGELOG.md, pkgs/jnigen/lib/src/elements/elements.dart, pkgs/jnigen/lib/src/elements/elements.g.dart
Close #1354.
Synthetic bridge methods are not generated. Relax the JSON parsing to not require a non-null name for the parameters as sometimes they might not have any name.
=> [jnigen] Do not fail when synthetic parameters don't have names

pkgs/ffigen/CHANGELOG.md, pkgs/ffigen/lib/src/code_generator/objc_built_in_functions.dart, pkgs/ffigen/lib/src/code_generator/objc_interface.dart, pkgs/ffigen/lib/src/header_parser/sub_parsers/objcinterfacedecl_parser.dart, pkgs/ffigen/pubspec.yaml, pkgs/ffigen/test/large_integration_tests/large_objc_test.dart, pkgs/ffigen/test/native_objc_test/protocol_config.yaml, pkgs/ffigen/test/native_objc_test/protocol_test.dart, pkgs/ffigen/test/native_objc_test/protocol_test.h, pkgs/ffigen/test/native_objc_test/protocol_test.m, pkgs/objective_c/CHANGELOG.md, pkgs/objective_c/lib/src/internal.dart, pkgs/objective_c/lib/src/objective_c_bindings_generated.dart, pkgs/objective_c/pubspec.yaml
If an interface implements a protocol, but doesn't declare or implement the protocol's methods in the same file, then they won't appear as methods directly on the interface in the AST. This is actually the typical case in most APIs, where the implementation is in a separate file to the interface. This means we don't codegen those methods, so they aren't invocable from Dart, even though they do have implementations and are invocable from ObjC.
The fix is just to parse all the protocols that the interface implements, and copy their methods to the interface.
The only wrinkle is that protocols can have optional methods, which the interface might not implement. If we generate the same Dart bindings for optional methods as we do for required methods, then invoking these methods may cause a …
=> [ffigen] Add protocol methods to interfaces

pkgs/jni/CHANGELOG.md, pkgs/jni/example/lib/main.dart, pkgs/jni/lib/_internal.dart, pkgs/jni/lib/jni.dart, pkgs/jni/lib/src/accessors.dart, pkgs/jni/lib/src/jarray.dart, pkgs/jni/lib/src/jni.dart, pkgs/jni/lib/src/jreference.dart, pkgs/jni/lib/src/method_invocation.dart, pkgs/jni/lib/src/third_party/global_env_extensions.dart, pkgs/jni/lib/src/types.dart, pkgs/jni/pubspec.yaml, pkgs/jni/tool/wrapper_generators/generate_c_extensions.dart, pkgs/jni/tool/wrapper_generators/generate_dart_extensions.dart, pkgs/jnigen/CHANGELOG.md, pkgs/jnigen/example/in_app_java/lib/android_utils.dart, pkgs/jnigen/example/kotlin_plugin/lib/kotlin_bindings.dart, pkgs/jnigen/example/notification_plugin/lib/notifications.dart, pkgs/jnigen/example/pdfbox_plugin/lib/src/third_party/org/apache/pdfbox/pdmodel/PDDocument.dart, pkgs/jnigen/example/pdfbox_plugin/lib/src/third_party/org/apache/pdfbox/pdmodel/PDDocumentInformation.dart, pkgs/jnigen/example/pdfbox_plugin/lib/src/third_party/org/apache/pdfbox/text/PDFTextStripper.dart, pkgs/jnigen/lib/jnigen.dart, pkgs/jnigen/lib/src/bindings/dart_generator.dart, pkgs/jnigen/pubspec.yaml, pkgs/jnigen/test/jackson_core_test/third_party/bindings/com/fasterxml/jackson/core/JsonFactory.dart, pkgs/jnigen/test/jackson_core_test/third_party/bindings/com/fasterxml/jackson/core/JsonParser.dart, pkgs/jnigen/test/jackson_core_test/third_party/bindings/com/fasterxml/jackson/core/JsonToken.dart, pkgs/jnigen/test/kotlin_test/bindings/kotlin.dart, pkgs/jnigen/test/simple_package_test/bindings/simple_package.dart, pkgs/jnigen/test/simple_package_test/generate.dart
Updated the dependencies including lints.
Fixed new lint errors.
Added `@internal` annotation on elements that should only be exported from `_internal.dart`.
Ignore the correct lints in the JNIgen generated code.
=> Update dependencies and use `@internal` annotation

.github/workflows/ffigen.yml, .github/workflows/ffigen_weekly.yml, pkgs/ffigen/pubspec.yaml, pkgs/ffigen/test/header_parser_tests/dart_handle_test.dart, pkgs/ffigen/test/large_integration_tests/large_objc_test.dart, pkgs/ffigen/test/native_objc_test/arc_test.dart, pkgs/ffigen/test/native_objc_test/block_annotation_test.dart, pkgs/ffigen/test/native_objc_test/block_test.dart, pkgs/ffigen/test/native_objc_test/global_native_test.dart, pkgs/ffigen/test/native_objc_test/global_test.dart, pkgs/ffigen/test/native_objc_test/isolate_test.dart, pkgs/ffigen/test/native_objc_test/protocol_test.dart, pkgs/ffigen/test/native_objc_test/ref_count_test.dart, pkgs/ffigen/test/native_objc_test/static_func_native_test.dart, pkgs/ffigen/test/native_objc_test/static_func_test.dart, pkgs/ffigen/test/native_objc_test/util.dart, pkgs/ffigen/test/test_utils.dart
#1570, #1571, and #1470 are only reproducible/testable in flutter, so we need to run the tests under `flutter test`. But the GC tests don't work reliably in flutter, so we still need to run the tests in `dart test` as well, and skip the GC tests on flutter.
The issue with the GC tests is that `Dart_ExecuteInternalCommand` doesn't exist in the flutter tester. I tried package:leak_tracker's `forceGC` function, but it broke the autorelease tests, had general flakiness issues.
=> [ffigen] Run ObjC tests on flutter test

pkgs/ffigen/CHANGELOG.md, pkgs/ffigen/lib/src/code_generator/objc_protocol.dart, pkgs/ffigen/lib/src/header_parser/sub_parsers/objcinterfacedecl_parser.dart, pkgs/ffigen/lib/src/header_parser/sub_parsers/objcprotocoldecl_parser.dart, pkgs/ffigen/test/native_objc_test/protocol_test.dart, pkgs/ffigen/test/native_objc_test/protocol_test.h, pkgs/ffigen/test/native_objc_test/protocol_test.m
The current (buggy) behavior is that, when parsing an interface's conforming protocols to include their methods in the interface, the protocols are only parsed if they're included by the config filters. The typical approach in ffigen for this sort of thing is to bypass the filters when a entity is being included transitively (this is already the case for super protocols for example). But that would lead to the generation of a ton of protocol bindings (boilerplate for implementing those protocols from Dart) that the user probably doesn't want.
So I'm bypassing the filters when parsing transitively included protocols, but then only generating implementation bindings for the protocol if it is included by the config filters. This is technically a breaking change because it affects super …
=> [ffigen] Fix protocol inclusion rules

pkgs/jni/example/lib/main.dart, pkgs/jni/java/src/main/java/com/github/dart_lang/jni/PortProxyBuilder.java, pkgs/jni/lib/jni.dart, pkgs/jni/lib/src/accessors.dart, pkgs/jni/lib/src/jimplementer.dart, pkgs/jni/lib/src/jni.dart, pkgs/jni/lib/src/third_party/jni_bindings_generated.dart, pkgs/jni/src/dartjni.c, pkgs/jni/src/dartjni.h, pkgs/jni/test/global_env_test.dart, pkgs/jnigen/CHANGELOG.md, pkgs/jnigen/docs/interface_implementation.md, pkgs/jnigen/example/in_app_java/lib/android_utils.dart, pkgs/jnigen/example/kotlin_plugin/lib/kotlin_bindings.dart, pkgs/jnigen/example/notification_plugin/lib/notifications.dart, pkgs/jnigen/example/pdfbox_plugin/lib/src/third_party/org/apache/pdfbox/pdmodel/PDDocument.dart, pkgs/jnigen/example/pdfbox_plugin/lib/src/third_party/org/apache/pdfbox/pdmodel/PDDocumentInformation.dart, pkgs/jnigen/example/pdfbox_plugin/lib/src/third_party/org/apache/pdfbox/text/PDFTextStripper.dart, pkgs/jnigen/lib/src/bindings/dart_generator.dart, pkgs/jnigen/lib/src/bindings/renamer.dart, pkgs/jnigen/test/jackson_core_test/third_party/bindings/com/fasterxml/jackson/core/JsonFactory.dart, pkgs/jnigen/test/jackson_core_test/third_party/bindings/com/fasterxml/jackson/core/JsonParser.dart, pkgs/jnigen/test/jackson_core_test/third_party/bindings/com/fasterxml/jackson/core/JsonToken.dart, pkgs/jnigen/test/kotlin_test/bindings/kotlin.dart, pkgs/jnigen/test/renamer_test.dart, pkgs/jnigen/test/simple_package_test/bindings/simple_package.dart, pkgs/jnigen/test/simple_package_test/generate.dart, pkgs/jnigen/test/simple_package_test/runtime_test_registrant.dart
Close #1579. Close #1021.
**Feel free to suggest better names for the classes and methods!**
For the full guide, read `pkgs/jnigen/docs/interface_implementation.md`.
* Added a `JImplementer` which is basically a proxy object builder. You add the implementations to it using `Foo.implementIn(implementer, implementation)`, and once you're done, you can create an instance via `implementer.implement()`. Implementing a single interface is still done via `Foo.implement(impl)`.
- This classes reuses the same `PortProxy` class – now called `PortProxyBuilder` – which now has a map of interfaces to the pair of function pointer and port.  (function pointer is used to invoke when on the same thread, port is used when on different threads. Once the Java object is GC'd, a cleanup message is sent to all …
=> [jnigen] Implement multiple interfaces

pkgs/ffigen/lib/src/code_generator/objc_block.dart, pkgs/ffigen/lib/src/header_parser/sub_parsers/objc_block_parser.dart, pkgs/ffigen/test/large_integration_tests/large_objc_test.dart
- Caught a real bug where synthetic blocks created by protocol bindings would use the protocol method's arg names, which could conflict with arg names used by the trampolines etc. Fix is to explicitly rename all the args to `arg0`, `arg1` etc.
- Added another disallowed method
=> [ffigen] More fixes for large integration test

pkgs/native_assets_builder/CHANGELOG.md, pkgs/native_assets_builder/test_data/drop_dylib_link/lib/src/drop_dylib_link.dart, pkgs/native_assets_builder/test_data/drop_dylib_link/pubspec.yaml, pkgs/native_assets_cli/CHANGELOG.md, pkgs/native_assets_cli/example/link/package_with_assets/hook/link.dart, pkgs/native_assets_cli/example/link/package_with_assets/lib/package_with_assets.dart, pkgs/native_assets_cli/example/link/package_with_assets/pubspec.yaml
Fixes #1586 
---
<details>
Note that many Dart repos have a weekly cadence …
=> Fix errors with new package:meta

pkgs/native_assets_cli/CHANGELOG.md, pkgs/native_assets_cli/lib/src/api/build_config.dart, pkgs/native_assets_cli/lib/src/api/hook_config.dart, pkgs/native_assets_cli/lib/src/api/link_config.dart, pkgs/native_assets_cli/lib/src/args_parser.dart, pkgs/native_assets_cli/lib/src/json_utils.dart, pkgs/native_assets_cli/lib/src/model/build_config.dart, pkgs/native_assets_cli/lib/src/model/hook_config.dart, pkgs/native_assets_cli/lib/src/model/link_config.dart, pkgs/native_assets_cli/pubspec.yaml
Originally the idea that probably led to this `package:cli_config` dependency was my thought that we should allow end-users to be able to override specific build config defines. For example to be able to say
```
% flutter build apk --build-config compiler.cc=<path-to-cc> ...
% flutter build apk --build-config package.bar.enable_asserts=true
```
But the idea was that the **bundling tool** will be responsible for changing the `config.json` by patching in those key/value pairs into the json tree **before** giving it to the `hook/build.dart` (the `hook/build.dart` isn't invoked by end users and therefore doesn't have to deal with the complexity - it can be encapsulated by the bundling tool). This would also allow an end user to make specific settings for a particular package and only that …
=> Remove `package:cli_config` & `package:args` dependencies in `package:native_asset_cli`

pkgs/native_assets_builder/CHANGELOG.md, pkgs/native_assets_builder/lib/src/build_runner/build_runner.dart, pkgs/native_assets_builder/test/build_runner/build_runner_run_in_isolation_test.dart, pkgs/native_assets_builder/test/helpers.dart, pkgs/native_assets_cli/CHANGELOG.md, pkgs/native_assets_cli/lib/src/model/hook_config.dart, pkgs/native_assets_cli/test/helpers.dart, pkgs/native_toolchain_c/test/helpers.dart
This removes the somewhat ugly piece of recognition of environment variables in `HookConfig.fromJson()` to the
`package:native_assets_builder`. This makes a round-trip from hook config to json and back to hook config
equal again.
We also rename those variables to prefix them with `DART_HOOK_TESTING`. This way we make it clear that this isn't intended to be used by end-users.
=> Rolling this to Dart SDK will require updating the test runner to also do this prefixing.
Issue https://github.com/dart-lang/native/issues/1599
=> Make the `package:native_assets_builder` have special logic to create C Compiler configuration for testing on Dart CI

pkgs/native_assets_cli/CHANGELOG.md, pkgs/native_assets_cli/example/link/package_with_assets/hook/link.dart, pkgs/native_assets_cli/lib/src/json_utils.dart, pkgs/native_assets_cli/lib/src/model/build_config.dart, pkgs/native_assets_cli/lib/src/model/hook_config.dart, pkgs/native_assets_cli/lib/src/model/hook_output.dart, pkgs/native_assets_cli/lib/src/model/link_config.dart, pkgs/native_assets_cli/lib/src/model/resource_identifiers.dart, pkgs/native_toolchain_c/CHANGELOG.md, pkgs/native_toolchain_c/lib/src/cbuilder/compiler_resolver.dart
This makes a `hook/{build,link}.dart` no longer resolve uris encoded in the `config.json`. It still validates that the uris that are encoded exist when it decodes the json.
The creator of `config.json` has to ensure that the uris it encodes in that config are existing file urls that the `hook/{build,link}.dart` scripts can open as-is (i.e. without resolving against any base uri).
In many cases that means that an invoker should encode absolute uris in there - or if it encodes relative uris - guarantees that they are relative to the working directory the `hook/{build,link}.dart` is invoked.
Issue https://github.com/dart-lang/native/issues/1605
=> Stop resolving Uris encoded in the build protocol

pkgs/jni/java/src/main/java/com/github/dart_lang/jni/PortProxyBuilder.java, pkgs/jni/lib/_internal.dart, pkgs/jni/lib/src/jimplementer.dart, pkgs/jni/lib/src/jni.dart, pkgs/jni/src/dartjni.c, pkgs/jnigen/CHANGELOG.md, pkgs/jnigen/docs/interface_implementation.md, pkgs/jnigen/lib/src/bindings/dart_generator.dart, pkgs/jnigen/test/simple_package_test/bindings/simple_package.dart, pkgs/jnigen/test/simple_package_test/java/com/github/dart_lang/jnigen/interfaces/MyRunnableRunner.java, pkgs/jnigen/test/simple_package_test/runtime_test_registrant.dart
Closes #1568.
Added a boolean `<method name>$async` for each given void method in an interface that defaults to `false`. If set to `true`, it will treat the method as a listener.
=> [jnigen] Implement void interface methods as listeners

.github/workflows/native.yaml, .github/workflows/native_toolchain_c.yaml, pkgs/native_toolchain_c/test/cbuilder/cbuilder_cross_android_test.dart
Android NDK r27 has been released, which means we can now test RISC-V on Android.
=> [native_toolchain_c] Enable Android RISC-V testing

pkgs/jni/CHANGELOG.md, pkgs/jni/pubspec.yaml, pkgs/jnigen/CHANGELOG.md, pkgs/jnigen/example/in_app_java/lib/android_utils.dart, pkgs/jnigen/lib/src/bindings/dart_generator.dart, pkgs/jnigen/lib/src/config/experiments.dart, pkgs/jnigen/pubspec.yaml, pkgs/jnigen/test/jackson_core_test/generate.dart, pkgs/jnigen/test/jackson_core_test/jnigen.yaml, pkgs/jnigen/test/kotlin_test/bindings/kotlin.dart, pkgs/jnigen/test/simple_package_test/generate.dart
Take interface implementation out of experimental and publish 0.12.0.
=> [jni][jnigen] Publish 0.12.0

pkgs/native_assets_builder/test_data/drop_dylib_link/hook/link.dart, pkgs/native_assets_builder/test_data/no_asset_for_link/hook/link.dart
A hook author doesn't know the transitive dart files. The bundling tool should already take care of re-building & re-running hooks if their source changes.
=> [hooks] Remove explicit adding of source dependency in `hook/link.dart` scripts

pkgs/native_assets_builder/CHANGELOG.md, pkgs/native_assets_builder/lib/src/build_runner/build_runner.dart, pkgs/native_assets_builder/lib/src/model/link_result.dart, pkgs/native_assets_builder/test/build_runner/conflicting_dylib_test.dart, pkgs/native_assets_builder/test/build_runner/link_test.dart
Before this change a bundling tool would
* call `buildResult = nativeAssetsBuildRunner.build(...)`
* call `linkResult = nativeAssetsBuildRunner.link(buildResult: buildResult, ...)
* get all assets via `allAssets = [...buildResult.assets, ...linkResult.assets]`
=> This PR makes the `link()` command produce a `LinkResult` containing
all assets of the final application.
=> One could view this as the assets from `build()` without a linker to go to
a default linker that just emits all of it's inputs.
=> This allows the `link()` step to also perform the application-wide
validation steps (not just over all linker outputs but across build &
link outputs)
Bundling tools now only have to deal with
* `buildResult` in JIT mode (where linking is not enabled)
* `linkResult` in AOT mode (where linking …
=> Ensure the NativeAssetsBuildRunner.link() produces a BuildResult with all assets

.github/workflows/ffigen_weekly.yml
The weekly bot failed again https://github.com/dart-lang/native/actions/runs/11197253228/job/31126969184. Fixes:
- Updated the workflow so that it also runs on any PR that alters that file
- Updated the version of flutter
- Pass the new `--main-thread-dispatcher` flag to setup.dart
Fixes https://github.com/dart-lang/native/issues/1617
=> [ffigen] Fix the weekly bot

pkgs/jnigen/CHANGELOG.md, pkgs/jnigen/lib/src/bindings/excluder.dart, pkgs/jnigen/pubspec.yaml
Show a warning and exclude all the identifiers that are currently malformed for whatever reason! Kotlin generates dashes in the names of the methods that have arguments with inline class types, until we correctly support them, let's exclude them so that because of one potentially unused method the entire generated bindings are not unusable.
=> [jnigen] Exclude invalid Dart identifiers by default

pkgs/jnigen/README.md
=> [jnigen] Fix readme links

pkgs/jni/CHANGELOG.md, pkgs/jni/java/src/main/java/com/github/dart_lang/jni/JniUtils.java, pkgs/jni/pubspec.yaml
Somehow I did not add this even though the C code existed. This is useful when trying to reconstruct an object from the its pointer's address in Java after sending the address through method channels.
=> [jnigen] Add a helper for sending jobjects through method channels

pkgs/jnigen/CHANGELOG.md, pkgs/jnigen/example/in_app_java/jnigen.yaml, pkgs/jnigen/example/in_app_java/lib/android_utils.dart, pkgs/jnigen/java/src/main/java/com/github/dart_lang/jnigen/apisummarizer/util/ClassFinder.java
For each package `x.y`, android also generates `x.y.R` in another jar file. Previously the APISummarizer code was written in a way to stop the search once a single class from `x.y` is found. This however means that sometimes only the `R` class is generated when we generate the entire `x.y` package. Changing the code to add all the classes in different jars that share the same package.
=> [jnigen] Fix generating packages in Android

pkgs/objective_c/lib/src/ns_input_stream.dart
- [X ] I’ve reviewed the contributor guide and applied the relevant portions to this PR.
<details> …
=> Fix a bug where toNSInputStream would leak if the stream is closed before being fully read

pkgs/ffigen/pubspec.yaml, pkgs/ffigen/test/native_objc_test/isolate_test.dart, pkgs/objective_c/pubspec.yaml
Now that https://github.com/dart-lang/tools/issues/520 is fixed we can use `Isolate.run` in tests with coverage.
=> [ffigen] Switch tests to Isolate.run

.github/workflows/objective_c.yaml, pkgs/ffigen/CHANGELOG.md, pkgs/ffigen/lib/src/code_generator/objc_built_in_functions.dart, pkgs/ffigen/lib/src/code_generator/objc_protocol.dart, pkgs/ffigen/pubspec.yaml, pkgs/ffigen/test/native_objc_test/protocol_config.yaml, pkgs/ffigen/test/native_objc_test/protocol_test.dart, pkgs/ffigen/test/native_objc_test/protocol_test.h, pkgs/objective_c/CHANGELOG.md, pkgs/objective_c/lib/src/objective_c_bindings_generated.dart, pkgs/objective_c/pubspec.yaml, pkgs/objective_c/src/objective_c_bindings_generated.m, pkgs/objective_c/test/setup.dart
Protocol objects are only available at runtime if they're actually used in native code. So add some dummy functions to the ObjC bindings that use each protocol.
Fixes https://github.com/dart-lang/native/issues/1672
=> [ffigen] Make sure all protocols are used

pkgs/ffigen/CHANGELOG.md, pkgs/ffigen/lib/src/code_generator/imports.dart, pkgs/ffigen/lib/src/code_generator/objc_interface.dart, pkgs/ffigen/lib/src/code_generator/objc_methods.dart, pkgs/ffigen/lib/src/header_parser/sub_parsers/objcinterfacedecl_parser.dart, pkgs/ffigen/lib/src/visitor/apply_config_filters.dart, pkgs/ffigen/test/native_objc_test/block_config.yaml, pkgs/ffigen/test/native_objc_test/block_test.dart, pkgs/ffigen/test/native_objc_test/block_test.h, pkgs/ffigen/test/native_objc_test/block_test.m, pkgs/ffigen/test/native_objc_test/method_filtering_test.dart, pkgs/ffigen/test/native_objc_test/method_filtering_test.m, pkgs/ffigen/test/native_objc_test/protocol_test.dart, pkgs/ffigen/test/native_objc_test/protocol_test.h, pkgs/ffigen/test/native_objc_test/protocol_test.m, pkgs/objective_c/lib/src/objective_c_bindings_generated.dart
The [main change](https://github.com/dart-lang/native/pull/1684/commits/06d86a1f27f4c1a9f27a1be3572c1938513ce5f3) is simple enough. Fixes #1595. Fixes #1594.
But this change altered the order that methods are filtered in, which means the randomized large_objc_test.dart now selects different APIs. So a few new bugs were exposed:
- We don't support [class methods on protocols](https://github.com/dart-lang/native/issues/1149), but interfaces copy all the methods from the protocols they implement, including class methods. There was a bug in `@optional` class methods that were copied from a protocol to a class.
- Protocols were still codegenning these class methods, even though they're not supported. They were generating them as if they were instance methods.
- Listener blocks that take …
=> [ffigen] Migrate method filtering to the visitor

pkgs/ffigen/example/shared_bindings/generate.dart, pkgs/ffigen/example/shared_bindings/pubspec.yaml, pkgs/ffigen/pubspec.yaml, pkgs/ffigen/test/header_parser_tests/dart_handle_test.dart
`getSdkPath()` is deprecated, which is causing CI failures: https://github.com/dart-lang/native/actions/runs/11583599790/job/32249077936
=> [ffigen] Replace cli_util's `getSdkPath()` with `sdkPath`

pkgs/ffigen/example/objective_c/avf_audio_bindings.dart, pkgs/ffigen/example/objective_c/play_audio.dart, pkgs/ffigen/example/objective_c/pubspec.yaml, pkgs/ffigen/example/swift/example.dart, pkgs/ffigen/example/swift/pubspec.yaml, pkgs/ffigen/example/swift/swift_api_bindings.dart, pkgs/ffigen/pubspec.yaml, pkgs/objective_c/pubspec.yaml, pkgs/objective_c/test/setup.dart
Since the ObjC/Swift examples depend on package:objective_c, and are Dart command line scripts, not flutter apps, they need to build and load package:objective_c's dylib. I updated the examples to directly invoke package:objective_c's test setup script, which does the job. I also had to update the setup script so it doesn't make assumptions about what directory it's being run in.
https://github.com/dart-lang/native/issues/1671
=> [ffigen] Fix ObjC/Swift examples

pkgs/ffigen/lib/src/code_generator/objc_protocol.dart, pkgs/ffigen/test/native_objc_test/protocol_test.dart, pkgs/ffigen/test/native_objc_test/protocol_test.h, pkgs/ffigen/test/native_objc_test/protocol_test.m, pkgs/objective_c/CHANGELOG.md, pkgs/objective_c/ffigen_c.yaml, pkgs/objective_c/lib/src/c_bindings_generated.dart, pkgs/objective_c/lib/src/internal.dart, pkgs/objective_c/lib/src/objective_c_bindings_generated.dart, pkgs/objective_c/lib/src/protocol_builder.dart, pkgs/objective_c/src/objective_c_runtime.h
- Only throw an error if the user tries to *implement* a missing method.
- Make the thrown error more descriptive and useful
- Add `ObjCProtocolMethod.isAvailable`, to make it easier to implement fallback logic if a method is missing.
Fixes https://github.com/dart-lang/native/issues/1702
=> [objective_c] Handle missing protocol methods more gracefully

pkgs/jnigen/CHANGELOG.md, pkgs/jnigen/lib/src/generate_bindings.dart, pkgs/jnigen/lib/src/tools/android_sdk_tools.dart
The output looks like:
```
Gradle execution failed.
1. The most likely cause is that the Android build is not yet cached.
Run `flutter build apk` in example/ and try again.
2. If the Gradle output includes text like this:
* What went wrong:
Execution failed for task ':gradle:compileGroovy'.
> BUG! exception in phase 'semantic analysis' ...  Unsupported class file major version
Then the JDK versions used by jnigen and flutter are not compatible. Try
changing the default JDK version e.g. with `export JAVA_VERSION=11` on macOS and
`sudo update-alternatives --config java` on Ubuntu.
GRADLE OUTPUT:
--------------------------------------------------------------------------------
Gradle stub cannot find JAR libraries. This might be because no APK build has happened yet.
If you are seeing this …
```
=> Fix the diagnostics where there is a JDK version mismatch

pkgs/ffigen/lib/src/code_generator/objc_interface.dart, pkgs/ffigen/lib/src/code_generator/objc_methods.dart, pkgs/ffigen/lib/src/code_generator/type.dart, pkgs/ffigen/lib/src/header_parser/sub_parsers/objcinterfacedecl_parser.dart, pkgs/ffigen/lib/src/visitor/fix_overridden_methods.dart, pkgs/ffigen/test/native_objc_test/bad_override_config.yaml, pkgs/ffigen/test/native_objc_test/bad_override_test.dart, pkgs/ffigen/test/native_objc_test/bad_override_test.m
Fix one of the bad override bugs: conflicts between methods and getters.
In ObjC, supertypes and subtypes can have a method that's an ordinary method in some classes of the heirarchy, and a property in others. This isn't allowed in Dart, so we change all such conflicts to properties. This change could cause more conflicts in the heirarchy, so first we walk up to find the root of the subtree that has this method, then we walk down the subtreee to change all conflicting methods to properties.
Why change them all to properties, not methods? If a method can sensibly be made into a getter, that's always preferable. And we know these methods are reasonable candidates to be made into getters, since some of them already are. Also, if we changed the getters into methods, we'd have to worry about …
=> [ffigen] Fix method vs getter conflicts

pkgs/ffigen/lib/src/code_generator/enum_class.dart, pkgs/ffigen/lib/src/code_generator/writer.dart
Example of the new warning:
```
[SEVERE] : The integer type used for enums is implementation-defined. FFIgen tries to mimic the integer sizes chosen by the most common compilers for the various OS and architecture combinations. To prevent any crashes, remove the enums from your API surface. To rely on the (unsafe!) mimicking, you can silence this warning by adding silence-enum-warning: true to the FFIgen config. Affected enums:
NSComparisonResult
NSDataBase64DecodingOptions
NSDataCompressionAlgorithm
NSDataReadingOptions
NSItemProviderFileOptions
NSItemProviderRepresentationVisibility
NSStreamEvent
NSStreamStatus
NSStringCompareOptions
NSStringEncodingConversionOptions
NSURLBookmarkCreationOptions
NSURLBookmarkResolutionOptions
```
Fixes #1715
=> [ffigen] Improve enum warning

pkgs/ffigen/CHANGELOG.md, pkgs/ffigen/lib/src/code_generator/objc_nullable.dart, pkgs/ffigen/test/native_objc_test/nullable_test.dart, pkgs/ffigen/test/native_objc_test/nullable_test.m, pkgs/objective_c/lib/src/objective_c_bindings_generated.dart, pkgs/objective_c/src/objective_c_bindings_generated.m
The line in extractor.dart that wraps nullable types in `ObjCNullable` looks like this:
```Dart
return isNullable && ObjCNullable.isSupported(innerType) ? ObjCNullable(innerType) : innerType;
```
That is, it only actually wraps the type in `ObjCNullable` if it's one of the supported nullable types, such as `ObjCInterface`.
There was a long standing bug in this line that meant nullable typealiases were treated as non-null. This almost never came up before #1681 because typedefs were only included in the AST if they were explicitly included by the config, and their aliased type would be substituted.
The `isSupported` assert in `ObjCNullable` correctly checks the aliased type, but this line in extractor.dart doesn't. One fix would be to change the check in extractor.dart to …
=> [ffigen] Fix nullable typealias bug

pkgs/ffigen/lib/src/code_generator/objc_methods.dart
While investigating #1137, which was already fixed, I found that all the remaining "duplicate method" log spam is for methods like this:
```
[SEVERE] : Duplicate methods with different signatures: NSMenu.isAccessibilityFocused: @optional bool isAccessibilityFocused() vs bool isAccessibilityFocused()
[SEVERE] : Duplicate methods with different signatures: NSMenuItem.isAccessibilityFocused: @optional bool isAccessibilityFocused() vs bool isAccessibilityFocused()
[SEVERE] : Duplicate methods with different signatures: NSCell.isAccessibilityFocused: @optional bool isAccessibilityFocused() vs bool isAccessibilityFocused()
[SEVERE] : Duplicate methods with different signatures: NSWindow.isAccessibilityFocused: @optional bool isAccessibilityFocused() vs bool isAccessibilityFocused()
[SEVERE] : …
```
=> [ffigen] Fix last bit of log spam

pkgs/ffigen/lib/src/code_generator/objc_methods.dart, pkgs/ffigen/lib/src/code_generator/objc_protocol.dart, pkgs/ffigen/lib/src/visitor/fix_overridden_methods.dart, pkgs/ffigen/test/large_integration_tests/large_objc_test.dart
- Make large_objc_test.dart's random includer deterministic, regardless of AST iteration order
- Fix a bug where `_fixMethodsVsProperties` was affecting setters as well as getters
- Fix a bug where protocol properties were being renamed according to class-style getter/setter rules, even though they're not code-genned as getters/setters
=> [ffigen] Fix CI failure

pkgs/swift2objc/lib/src/ast/_core/shared/parameter.dart, pkgs/swift2objc/lib/src/ast/_core/shared/referred_type.dart, pkgs/swift2objc/lib/src/ast/declarations/compounds/members/method_declaration.dart, pkgs/swift2objc/lib/src/config.dart, pkgs/swift2objc/lib/src/parser/_core/utils.dart, pkgs/swift2objc/lib/src/parser/parsers/declaration_parsers/parse_compound_declaration.dart, pkgs/swift2objc/lib/src/parser/parsers/parse_declarations.dart, pkgs/swift2objc/lib/src/transformer/transformers/const.dart, pkgs/swift2objc/lib/src/transformer/transformers/transform_compound.dart, pkgs/swift2objc/lib/src/transformer/transformers/transform_function.dart, pkgs/swift2objc/lib/src/transformer/transformers/transform_variable.dart
- The `ModuleInputConfig` symbolgraph command should use `swift`, not `swiftc`
- Dedupe class methods by ID, to fix multiple definition issues
- Also dedupe methods by their full name (name + arg names), to work around [this buggy API](https://developer.apple.com/documentation/avfaudio/avaudioengine/3012856-disconnectmidi) conflicting with [this other API](https://developer.apple.com/documentation/avfaudio/avaudioengine/3012855-disconnectmidi)
- Hard code a list of methods that we don't try to wrap, such as `hashValue`, because these are special cased in Swift, and we're not allowed to override them
I don't really have a way of testing these changes, since they're mostly dealing with bugs in the apple APIs that I'm not sure how to replicate in Swift source without compile errors. Once I …
=> [swift2objc] More little fixes

pkgs/swift2objc/lib/src/ast/declarations/compounds/members/initializer_declaration.dart, pkgs/swift2objc/lib/src/generator/generators/class_generator.dart, pkgs/swift2objc/lib/src/parser/_core/json.dart, pkgs/swift2objc/lib/src/parser/_core/utils.dart, pkgs/swift2objc/lib/src/parser/parsers/declaration_parsers/parse_initializer_declaration.dart, pkgs/swift2objc/lib/src/transformer/_core/unique_namer.dart, pkgs/swift2objc/lib/src/transformer/_core/utils.dart, pkgs/swift2objc/lib/src/transformer/transformers/transform_compound.dart, pkgs/swift2objc/lib/src/transformer/transformers/transform_initializer.dart, pkgs/swift2objc/test/integration/classes_and_initializers_input.swift, pkgs/swift2objc/test/integration/classes_and_initializers_output.swift, pkgs/swift2objc/test/integration/integration_test.dart, pkgs/swift2objc/test/integration/structs_and_initializers_input.swift, pkgs/swift2objc/test/integration/structs_and_initializers_output.swift, pkgs/swift2objc/test/unit/parse_initializer_param_test.dart
A failable initializer in Swift is an initializer that can return nil:
```Swift
public class MyClass {
public let someInt: Int
public init?(outerLabel x: Int) {
if x == 0 {
return nil
} else {
self.someInt = x
}
}
}
```
They show up in the symbolgraph with a `?(` token in their second fragment instead of a `(`:
```json
"declarationFragments": [
{
"kind": "keyword",
"spelling": "init"
},
{
"kind": "text",
"spelling": "?("
},
```
When wrapping these constructors, we have to declare the wrapper initializer as failable, and check if the wrapped initializer returned `nil`.
```Swift
@objc public class MyClassWrapper: NSObject {
var wrappedInstance: MyClass
@objc init?(outerLabel x: Int) {
if let instance = MyClass(outerLabel: x) {
wrappedInstance = instance
} else {
return nil
}
}
}
```
=> [swift2objc] Support failable initializers

pkgs/swift2objc/lib/src/parser/parsers/declaration_parsers/parse_variable_declaration.dart, pkgs/swift2objc/test/integration/global_variables_and_functions_input.swift, pkgs/swift2objc/test/integration/global_variables_and_functions_output.swift
Before this change, variables with an explicit getter but no setter would be wrapped by a getter/setter pair, and the setter was causing compile errors.
=> [swift2objc] Support globals with explicit getters/setters

pkgs/native_toolchain_c/CHANGELOG.md, pkgs/native_toolchain_c/lib/src/cbuilder/run_cbuilder.dart, pkgs/native_toolchain_c/test/cbuilder/cbuilder_cross_android_test.dart, pkgs/native_toolchain_c/test/helpers.dart
Closes: https://github.com/dart-lang/native/issues/1611
=> [native_toolchain_c] Use 16 kb pages for Android by default

pkgs/native_toolchain_c/CHANGELOG.md, pkgs/native_toolchain_c/lib/native_toolchain_c.dart, pkgs/native_toolchain_c/lib/src/cbuilder/cbuilder.dart, pkgs/native_toolchain_c/lib/src/cbuilder/clinker.dart, pkgs/native_toolchain_c/lib/src/cbuilder/ctool.dart, pkgs/native_toolchain_c/lib/src/cbuilder/optimization_level.dart, pkgs/native_toolchain_c/lib/src/cbuilder/run_cbuilder.dart, pkgs/native_toolchain_c/test/cbuilder/cbuilder_cross_android_test.dart, pkgs/native_toolchain_c/test/cbuilder/cbuilder_cross_ios_test.dart, pkgs/native_toolchain_c/test/cbuilder/cbuilder_cross_linux_host_test.dart, pkgs/native_toolchain_c/test/cbuilder/cbuilder_cross_macos_host_test.dart, pkgs/native_toolchain_c/test/cbuilder/cbuilder_cross_windows_host_test.dart
Closes: https://github.com/dart-lang/native/issues/1267
=> [native_toolchain_c] Compile with `-Os` by default

pkgs/native_toolchain_c/CHANGELOG.md, pkgs/native_toolchain_c/lib/src/cbuilder/cbuilder.dart, pkgs/native_toolchain_c/lib/src/cbuilder/clinker.dart
[Not all linkers support `-Os`](https://logs.chromium.org/logs/dart/buildbucket/cr-buildbucket/8730301908709004769/+/u/test_results/new_test_failures__logs_), so defaulting to `-O3` is more portable.
Issue:
* https://github.com/dart-lang/native/issues/1267
=> [native_toolchain_c] Compile with `-O3` by default

pkgs/native_assets_builder/lib/src/build_runner/build_runner.dart, pkgs/native_assets_cli/lib/src/config.dart
https://github.com/dart-lang/native/pull/1643 accidentally made the output directory of link hooks change when different assets are passed in for linking.
=> [native_assets_builder] Keep `outputDirectory` if `LinkConfig.assets` changes

pkgs/native_assets_builder/test_data/transformer/hook/build.dart, pkgs/native_assets_builder/test_data/wrong_linker/hook/build.dart, pkgs/native_assets_builder/test_data/wrong_namespace_asset/hook/build.dart, pkgs/native_assets_cli/example/build/local_asset/hook/build.dart, pkgs/native_assets_cli/lib/src/code_assets/code_asset.dart, pkgs/native_assets_cli/lib/src/code_assets/config.dart, pkgs/native_assets_cli/lib/src/code_assets/link_mode.dart, pkgs/native_assets_cli/lib/src/code_assets/validation.dart, pkgs/native_assets_cli/lib/src/config.dart, pkgs/native_assets_cli/lib/src/data_assets/data_asset.dart, pkgs/native_assets_cli/lib/src/data_assets/validation.dart, pkgs/native_toolchain_c/lib/src/cbuilder/cbuilder.dart
This deprecates `BuildConfig.dryRun`.
We will be able to remove it after Dart 3.7 is released and we can increase the SDK bound in `native_assets_cli` to that version.
For now, add some ignores to suppress to suppress the deprecation lints.
Bug:
* https://github.com/dart-lang/native/issues/1485
=> [native_x] Deprecate `dryRun`

pkgs/native_assets_cli/lib/src/api/build.dart, pkgs/native_assets_cli/lib/src/api/link.dart
Closes: https://github.com/dart-lang/native/issues/33
The behavior is already tested by pkgs/native_assets_builder/test/build_runner/build_runner_build_output_format_test.dart.
=> [native_assets_cli] Document hook exit code behavior

pkgs/native_assets_builder/lib/src/build_runner/build_runner.dart, pkgs/native_assets_builder/lib/src/dependencies_hash_file/dependencies_hash_file.dart, pkgs/native_assets_builder/test/build_runner/build_runner_caching_test.dart, pkgs/native_assets_builder/test/dependencies_hash_file/dependencies_hash_file_test.dart
Addresses the remaining comments on https://github.com/dart-lang/native/pull/1750.
I'm unsure how to test the recompiling of the kernel file if Dart changes without writing a test that downloads a different Dart SDK.
=> [native_assets_builder] Recompile hook kernel if Dart changes

pkgs/native_assets_cli/test/build_output_test.dart, pkgs/native_assets_cli/test/link_output_test.dart
Closes: https://github.com/dart-lang/native/issues/1745
=> Update build output test to use .compareTo()/.isSameMomentAs() as operators don't exist on DateTime

pkgs/swift2objc/lib/src/transformer/_core/utils.dart, pkgs/swift2objc/test/integration/optional_input.swift, pkgs/swift2objc/test/integration/optional_output.swift
The wrapper for
```Swift
public func funcOptionalStrings(str: String?) -> String? { return str; }
```
was being generated as
```Swift
@objc static public func funcOptionalStringsWrapper(str: String?) -> String? {
return funcOptionalStrings(str: str?)
}
```
The `str?` is generated by `maybeUnwrapValue`, which was inserting `?` because in most cases it's expecting to unwrap a wrapper type, which would add a `.wrappedInstance` to get `str?.wrappedInstance`. But strings don't need to be wrapped, because they bridge directly to `NSString`. So we end up with `str?`, with this unnecessary `?` at the end, which causes compile errors.
The fix is just to drop the `?` if the nested `maybeUnwrapValue` call didn't do anything.
=> [swift2objc] Fix bug with optional string params

pkgs/swift2objc/lib/src/ast/_core/interfaces/can_throw.dart, pkgs/swift2objc/lib/src/ast/_core/interfaces/function_declaration.dart, pkgs/swift2objc/lib/src/ast/_core/interfaces/variable_declaration.dart, pkgs/swift2objc/lib/src/ast/declarations/compounds/members/initializer_declaration.dart, pkgs/swift2objc/lib/src/ast/declarations/compounds/members/method_declaration.dart, pkgs/swift2objc/lib/src/ast/declarations/compounds/members/property_declaration.dart, pkgs/swift2objc/lib/src/ast/declarations/globals/globals.dart, pkgs/swift2objc/lib/src/generator/generators/class_generator.dart, pkgs/swift2objc/lib/src/parser/_core/json.dart, pkgs/swift2objc/lib/src/parser/_core/token_list.dart, pkgs/swift2objc/lib/src/parser/_core/utils.dart, pkgs/swift2objc/lib/src/parser/parsers/declaration_parsers/parse_function_declaration.dart, pkgs/swift2objc/lib/src/parser/parsers/declaration_parsers/parse_initializer_declaration.dart, pkgs/swift2objc/lib/src/parser/parsers/declaration_parsers/parse_variable_declaration.dart, pkgs/swift2objc/lib/src/parser/parsers/parse_type.dart, pkgs/swift2objc/lib/src/transformer/transformers/transform_compound.dart, pkgs/swift2objc/lib/src/transformer/transformers/transform_function.dart, pkgs/swift2objc/lib/src/transformer/transformers/transform_initializer.dart, pkgs/swift2objc/lib/src/transformer/transformers/transform_variable.dart, pkgs/swift2objc/pubspec.yaml, pkgs/swift2objc/test/integration/integration_test.dart, pkgs/swift2objc/test/integration/throws_input.swift, pkgs/swift2objc/test/integration/throws_output.swift, pkgs/swift2objc/test/unit/parse_function_info_test.dart, pkgs/swift2objc/test/unit/token_list_test.dart, pkgs/swiftgen/pubspec.yaml
Methods and functions in Swift that can throw an exception must be annotated with `throws`. When you call one of these functions, you have to either handle the exception, or forward it by prefixing the call with `try` (in which case your function must also be marked `throws`).
So when we're wrapping one of these methods we need to add `try` and `throws` keywords, like this:
```Swift
@objc public class MyClassWrapper: NSObject {
var wrappedInstance: MyClass
@objc public func voidMethod() throws {
return try wrappedInstance.voidMethod()
}
}
```
`throws` shows up in the `declarationFragments` of the function, after the `)` but before the `->`. Getters can also throw, but supporting them is a [little more complicated](https://github.com/dart-lang/native/issues/1765).
- I didn't realize about …
=> [swift2objc] Support `throws` annotation

pkgs/swift2objc/lib/src/ast/_core/interfaces/can_async.dart, pkgs/swift2objc/lib/src/ast/_core/interfaces/function_declaration.dart, pkgs/swift2objc/lib/src/ast/_core/interfaces/variable_declaration.dart, pkgs/swift2objc/lib/src/ast/declarations/compounds/members/initializer_declaration.dart, pkgs/swift2objc/lib/src/ast/declarations/compounds/members/method_declaration.dart, pkgs/swift2objc/lib/src/ast/declarations/compounds/members/property_declaration.dart, pkgs/swift2objc/lib/src/ast/declarations/globals/globals.dart, pkgs/swift2objc/lib/src/generator/_core/utils.dart, pkgs/swift2objc/lib/src/generator/generators/class_generator.dart, pkgs/swift2objc/lib/src/parser/parsers/declaration_parsers/parse_function_declaration.dart, pkgs/swift2objc/lib/src/parser/parsers/declaration_parsers/parse_initializer_declaration.dart, pkgs/swift2objc/lib/src/parser/parsers/declaration_parsers/parse_variable_declaration.dart, pkgs/swift2objc/lib/src/transformer/transformers/transform_compound.dart, pkgs/swift2objc/lib/src/transformer/transformers/transform_function.dart, pkgs/swift2objc/lib/src/transformer/transformers/transform_initializer.dart, pkgs/swift2objc/lib/src/transformer/transformers/transform_variable.dart, pkgs/swift2objc/test/integration/async_input.swift, pkgs/swift2objc/test/integration/async_output.swift, pkgs/swift2objc/test/unit/parse_function_info_test.dart
This is implemented in pretty much exactly the same way as `throws`. Added a `CanAsync` interface, started parsing the annotation in `parseFunctionInfo`, and added the annotation to the generated code. The wrapper method gets an `async` annotation, and when invoking the wrapped method it must `await` the result.
Also like `throws`, there are edge cases where `async` APIs can't be marked with `@objc`. Support for these edge cases will be implemented later. See https://github.com/dart-lang/native/issues/1778
Fixes https://github.com/dart-lang/native/issues/1773
=> [swift2objc] Support the `async` annotation

.github/workflows/native.yaml, pkgs/native_assets_builder/lib/src/build_runner/build_runner.dart, pkgs/native_assets_builder/lib/src/dependencies_hash_file/dependencies_hash_file.dart, pkgs/native_assets_builder/lib/src/model/hook_result.dart, pkgs/native_assets_builder/test/build_runner/build_dependencies_test.dart, pkgs/native_assets_builder/test/build_runner/build_runner_caching_test.dart, pkgs/native_assets_builder/test/build_runner/build_runner_failure_test.dart, pkgs/native_assets_builder/test/build_runner/build_runner_non_root_package_test.dart, pkgs/native_assets_builder/test/build_runner/parse_dep_file_test.dart
Closes: https://github.com/dart-lang/native/issues/1770
This PR adds the Dart sources to the dependencies in `HookResult`.
It also fixes the dep-file parsing w.r.t. to escapes.
We're passing around `HookOutput`s which is the deserialized `output.json`. We could add the Dart sources as dependencies to it _after_ deserializing, but then the correspondence to the json is lost. So instead I've added an extra return value to the places where we pass `HookOutput` around.
=> [native_assets_builder] Report dart sources as dependencies of hooks

pkgs/jnigen/CHANGELOG.md, pkgs/jnigen/doc/java_differences.md, pkgs/jnigen/example/in_app_java/lib/android_utils.dart, pkgs/jnigen/lib/src/bindings/renamer.dart, pkgs/jnigen/lib/src/elements/elements.dart, pkgs/jnigen/test/jackson_core_test/third_party/bindings/com/fasterxml/jackson/core/JsonFactory.dart, pkgs/jnigen/test/jackson_core_test/third_party/bindings/com/fasterxml/jackson/core/JsonParser.dart, pkgs/jnigen/test/kotlin_test/bindings/kotlin.dart, pkgs/jnigen/test/kotlin_test/runtime_test_registrant.dart, pkgs/jnigen/test/renamer_test.dart, pkgs/jnigen/test/simple_package_test/bindings/simple_package.dart, pkgs/jnigen/test/simple_package_test/runtime_test_registrant.dart, pkgs/jnigen/test/summary_test.dart
The `Bar` class defined inside the `Foo` class in Java like `class Foo { class Bar {} }` used to be generated as `Foo_Bar`, but we can have a class named `Foo_Bar`, now we generate it as `Foo$Bar`.
We can (although very rare – rarer than using underscores) have a class named `Foo$Bar` that is not nested, this will be generated as `Foo$$Bar` as all dollar signs that are pre-existing in Java code will be replaced by 2 dollar signs. So we continue not to have any collisions.
I should mention that it's impossible to have both a nested `Bar` inside `Foo` and a class named `Foo$Bar` in the same package in Java because they will share the same binary name of `com.package.Foo$Bar`, so choosing `$` is better than `_` because of this as well.
Closes #1516.
=> [jnigen] Use dollar signs for nested class name separator

pkgs/jni/CHANGELOG.md, pkgs/jni/lib/_internal.dart, pkgs/jni/lib/jni.dart, pkgs/jni/lib/src/jarray.dart, pkgs/jni/lib/src/jprimitives.dart, pkgs/jni/lib/src/method_invocation.dart, pkgs/jni/lib/src/nio/jbyte_buffer.dart, pkgs/jni/lib/src/types.dart, pkgs/jni/test/jarray_test.dart, pkgs/jni/test/jbyte_buffer_test.dart, pkgs/jni/test/type_test.dart, pkgs/jnigen/example/pdfbox_plugin/lib/src/third_party/org/apache/pdfbox/pdmodel/PDDocument.dart, pkgs/jnigen/lib/src/bindings/dart_generator.dart, pkgs/jnigen/test/jackson_core_test/third_party/bindings/com/fasterxml/jackson/core/JsonFactory.dart, pkgs/jnigen/test/jackson_core_test/third_party/bindings/com/fasterxml/jackson/core/JsonParser.dart, pkgs/jnigen/test/jackson_core_test/third_party/bindings/com/fasterxml/jackson/core/JsonToken.dart, pkgs/jnigen/test/simple_package_test/bindings/simple_package.dart
Closes #1792.
As mentioned in https://github.com/dart-lang/native/issues/1792#issuecomment-2531316325 it was not possible to implement Dart's `Iterable` in a generic way for both primitive arrays and object arrays. This led me to separate them like how it's done in Kotlin.
=> Separate java primitive arrays and implement Iterable

pkgs/ffigen/CHANGELOG.md, pkgs/ffigen/example/shared_bindings/headers/a.h, pkgs/ffigen/example/shared_bindings/headers/base.h, pkgs/ffigen/example/shared_bindings/lib/generated/a_gen.dart, pkgs/ffigen/example/shared_bindings/lib/generated/a_shared_b_gen.dart, pkgs/ffigen/example/shared_bindings/lib/generated/base_gen.dart, pkgs/ffigen/example/shared_bindings/lib/generated/base_symbols.yaml, pkgs/ffigen/lib/src/code_generator/imports.dart, pkgs/ffigen/lib/src/code_generator/typealias.dart, pkgs/ffigen/lib/src/code_generator/writer.dart, pkgs/ffigen/lib/src/config_provider/spec_utils.dart, pkgs/ffigen/lib/src/strings.dart
Closes #1776
- Adds a `dart-name` field to the symbol map if required (currently only for typedefs)
- Nested typedefs have been handled by using the dart name for the root one.
- Updated changelog and shared_bindings test.
---
<details>
- Most changes should add an entry to the changelog and may need to [rev the pubspec package version](https://github.com/dart-lang/sdk/blob/main/docs/External-Pack …
=> Handle dart typedefs in import/export of symbol files.

pkgs/jni/CHANGELOG.md, pkgs/jni/java/src/main/java/com/github/dart_lang/jni/PortProxyBuilder.java, pkgs/jnigen/test/simple_package_test/runtime_test_registrant.dart
Closes #1801.
`toString`, `equals`, and `hashCode` of interfaces now just call their default object implementation when implementing them in Dart.
=> [jnigen] Run object default methods for interfaces

pkgs/native_assets_builder/test/build_runner/helpers.dart, pkgs/native_assets_builder/test/helpers.dart, pkgs/native_assets_cli/lib/src/code_assets/c_compiler_config.dart, pkgs/native_assets_cli/lib/src/code_assets/config.dart, pkgs/native_assets_cli/lib/src/code_assets/validation.dart, pkgs/native_assets_cli/test/code_assets/config_test.dart, pkgs/native_assets_cli/test/helpers.dart, pkgs/native_toolchain_c/lib/src/cbuilder/compiler_resolver.dart, pkgs/native_toolchain_c/test/cbuilder/compiler_resolver_test.dart, pkgs/native_toolchain_c/test/helpers.dart
Addressing:
* https://github.com/dart-lang/native/issues/1738#issuecomment-2535959430
Currently on Flutter and the Dart CI provide this information, and they always provide all 3. So this should not be a breaking change on the protocol level.
It is a breaking change on the API level.
=> [native_assets_cli] Make `CCompilerConfig` fields less nullable

pkgs/native_assets_builder/CHANGELOG.md, pkgs/native_assets_builder/lib/src/build_runner/build_planner.dart, pkgs/native_assets_builder/lib/src/build_runner/build_runner.dart, pkgs/native_assets_builder/lib/src/dependencies_hash_file/dependencies_hash_file.dart, pkgs/native_assets_builder/lib/src/locking/locking.dart, pkgs/native_assets_builder/lib/src/package_layout/package_layout.dart, pkgs/native_assets_builder/lib/src/utils/file.dart, pkgs/native_assets_builder/lib/src/utils/run_process.dart, pkgs/native_assets_builder/lib/src/utils/uri.dart, pkgs/native_assets_builder/pubspec.yaml, pkgs/native_assets_builder/test/build_runner/build_planner_test.dart, pkgs/native_assets_builder/test/build_runner/build_runner_reusability_test.dart, pkgs/native_assets_builder/test/build_runner/build_runner_test.dart, pkgs/native_assets_builder/test/build_runner/concurrency_shared_test_helper.dart, pkgs/native_assets_builder/test/build_runner/concurrency_test_helper.dart, pkgs/native_assets_builder/test/build_runner/helpers.dart, pkgs/native_assets_builder/test/build_runner/package_layout_test.dart, pkgs/native_assets_builder/test/dependencies_hash_file/dependencies_hash_file_test.dart, pkgs/native_assets_builder/test/helpers.dart, pkgs/native_assets_builder/test/locking/locking_test_helper.dart
The main motivation for this change is to make `package:native_assets_builder` cleanly usable in flutter tools. Right now flutter tools operates on a `FileSystem` and checks whether `.dart_tool/package_config.json` exists using that `FileSystem` but then reads the file with this packagag's code which uses `dart:io`.
This inconsistency causes issues in flutter tools. Using `package:file` should solve this and would also
allow injecting mocks. To be fully mockable the implementation would also need to make process invocations
mockable via `package:process`. That's a future task.
See also https://github.com/dart-lang/native/issues/90
=> [native_assets_builder] Use ` package:file`s `FileSystem` abstraction

pkgs/native_assets_builder/CHANGELOG.md, pkgs/native_assets_builder/lib/native_assets_builder.dart, pkgs/native_assets_builder/lib/src/build_runner/build_runner.dart, pkgs/native_assets_builder/pubspec.yaml, pkgs/native_assets_builder/test/build_runner/build_runner_caching_test.dart, pkgs/native_assets_builder/test/build_runner/helpers.dart
Make the environment used to invoke hooks configurable.
The flutter roll is failing currently, and I suspect it has to do with our change to tie down the environment variables. The execution of the `dart` executable fails. https://github.com/dart-lang/native/issues/1847
We can't easily troubleshoot which env key is missing currently, because the environment is not configurable from the embedder.
Since we'd like the embedder to be able to configure the environment anyways (e.g. Flutter might want to pass in `ANDROID_HOME` but Dart not), make the change now.
Hopefully, we can then trouble-shoot what's going on. (At the very least we can try passing the full environment in flutter_tools to see if that fixes the issue.)
=> [native_assets_builder] Make hook environment configurable

pkgs/native_assets_builder/CHANGELOG.md, pkgs/native_assets_builder/lib/native_assets_builder.dart, pkgs/native_assets_builder/pubspec.yaml
The health workflow is disabled currently, and https://github.com/dart-lang/native/pull/1853 accidentally hid too many public types.
=> [native_assets_builder] Make hook environment configurable - fix

pkgs/ffigen/lib/src/config_provider/yaml_config.dart
This warning is only relevant on Windows, so we don't need it for ObjC, which is only supported on iOS/macOS.
Fixes #1817
=> [ffigen] Disable enum warning for ObjC

pkgs/native_assets_builder/test_data/wrong_build_output_3/hook/build.dart, pkgs/native_assets_cli/lib/src/code_assets/config.dart, pkgs/native_assets_cli/lib/src/config.dart, pkgs/native_assets_cli/lib/src/json_utils.dart, pkgs/native_assets_cli/test/build_config_test.dart, pkgs/native_assets_cli/test/build_output_test.dart, pkgs/native_assets_cli/test/checksum_test.dart, pkgs/native_assets_cli/test/code_assets/config_test.dart, pkgs/native_assets_cli/test/link_config_test.dart, pkgs/native_assets_cli/test/link_output_test.dart
This changes the `BuildInputBuilder` to make a json with hierarchy.
The old JSON structure is also emitted in addition to prevent breaking the world.
The checksum is changed to only consume `config`.
The new JSON hierarchy with code config looks as follows:
```dart
Map<String, Object> inputJson({
String hookType = 'build',
OS targetOS = OS.android,
}) =>
{
'out_dir_shared': outputDirectoryShared.toFilePath(),
'out_dir': outDirUri.toFilePath(),
'package_name': packageName,
'package_root': packageRootUri.toFilePath(),
'version': '1.7.0',
'config': {
'build_asset_types': ['native_code'],
if (hookType == 'build') 'linking_enabled': false,
'code': {
'target_architecture': 'arm64',
'target_os': targetOS.name,
'link_mode_preference': 'prefer-static',
'c_compiler': {
'ar': fakeAr.toFilePath(), …
```
=> [native_assets_cli] Make `BuildInput` JSON hierarchical

pkgs/native_toolchain_c/lib/src/cbuilder/compiler_resolver.dart, pkgs/native_toolchain_c/lib/src/cbuilder/run_cbuilder.dart, pkgs/native_toolchain_c/test/cbuilder/compiler_resolver_test.dart
We'd like `flutter_tools` to invoke the `hook/build.dart` with the environment for `cl.exe` already set up and stop passing in `input.config.code.cCompiler.envScript`.
Therefore, `package:native_toolchain_c` should not go search for an vcvars batch script if the compiler has been provided in the code config but a vcvars script has not been provided.
Issue:
* https://github.com/dart-lang/native/issues/1606
=> [native_toolchain_c] Support environment for `cl.exe` already set up

pkgs/native_assets_builder/test_data/transformer/README.md, pkgs/native_assets_cli/example/build/README.md, pkgs/native_assets_cli/example/build/local_asset/README.md
Add READMEs for the current set of supported use cases.
I added a cross-link to the transformer test case so it doubles as example.
Closes: https://github.com/dart-lang/native/issues/1375
=> [native_assets_cli] [doc] Add READMEs for examples

.github/workflows/native.yaml, pkgs/native_assets_builder/test/build_runner/system_library_test.dart, pkgs/native_assets_builder/test_data/manifest.yaml, pkgs/native_assets_builder/test_data/system_library/hook/build.dart, pkgs/native_assets_builder/test_data/system_library/lib/memory_executable.dart, pkgs/native_assets_builder/test_data/system_library/lib/memory_process.dart, pkgs/native_assets_builder/test_data/system_library/lib/memory_system.dart, pkgs/native_assets_builder/test_data/system_library/pubspec.yaml, pkgs/native_assets_builder/test_data/system_library/test/memory_test.dart, pkgs/native_assets_cli/example/build/README.md, pkgs/native_assets_cli/example/build/system_library/README.md, pkgs/native_assets_cli/example/build/system_library/hook/build.dart, pkgs/native_assets_cli/example/build/system_library/lib/memory.dart, pkgs/native_assets_cli/example/build/system_library/pubspec.yaml, pkgs/native_assets_cli/example/build/system_library/test/memory_test.dart, pkgs/native_assets_cli/lib/src/code_assets/validation.dart
Closes: https://github.com/dart-lang/native/issues/940
Closes: https://github.com/dart-lang/native/issues/1879
=> [native_assets_cli] Fix system libraries and add documentation

pkgs/native_assets_builder/test_data/system_library/lib/memory_executable.dart, pkgs/native_assets_builder/test_data/system_library/lib/memory_process.dart, pkgs/native_assets_builder/test_data/system_library/lib/memory_system.dart, pkgs/native_assets_cli/example/build/system_library/lib/memory.dart
I addressed the lint to have lower-case method names, but forgot that the native symbol in Windows is upper case.
Because the fix for using system/process/executable is not yet in Dart, this wasn't caught by the integration test on this repo running `dart test` because it's disabled until the fix rolls into dev.
[log](https://logs.chromium.org/logs/dart/buildbucket/cr-buildbucket/8726092053135135713/+/u/test_results/new_test_failures__logs_)
```
00:55 [32m+3[0m: package:system_library dart test[0m
00:00 +0: loading test\memory_test.dart
00:00 +0: test\memory_test.dart: executable
00:00 +0 -1: test\memory_test.dart: executable [E]
Invalid argument(s): Couldn't resolve native function 'coTaskMemAlloc' in 'package:system_library/memory_executable.dart' : Failed to lookup symbol …
```
=> [native_assets_cli] Fix system libraries and add documentation - fix test

pkgs/native_assets_builder/test_data/system_library/lib/memory_executable.dart, pkgs/native_assets_builder/test_data/system_library/test/memory_test.dart
If only I knew how to write code for Windows. 🤓 
Fixing:
```
00:00 +0 -1: test\memory_test.dart: executable [E]
Invalid argument(s): Couldn't resolve native function 'CoTaskMemAlloc' in 'package:system_library/memory_executable.dart' : Failed to lookup symbol 'CoTaskMemAlloc': The specified procedure could not be found.
(error code: 127).
```
[log](https://logs.chromium.org/logs/dart/buildbucket/cr-buildbucket/8725836200960091649/+/u/test_results/new_test_failures__logs_)
The executable doesn't have access to `CoTaskMemAlloc`. It's in a win32 library that's loaded into the process. So, only `process` and `system` link mode work.
=> [native_assets_cli] Fix system libraries and add documentation - fix test 2

pkgs/native_assets_builder/lib/src/build_runner/build_runner.dart, pkgs/native_assets_builder/test/build_runner/build_runner_test.dart, pkgs/native_assets_builder/test_data/native_add/hook/build.dart
Write the stdout and stderr from hook invocations to disk.
The directory structure of the native assets builder now is as follows:
* `.dart_tool/`
* `native_assets_builder/`
* `$packageName/`
* `$checksum/`
* `input.json`
* `output.json`
* `out/`
* `stderr.txt`
* `stdout.txt`
Closes: https://github.com/dart-lang/native/issues/97
=> [native_assets_builder] Write hook stdout and stderr to disk

pkgs/native_assets_cli/lib/src/code_assets/config.dart, pkgs/native_assets_cli/lib/src/config.dart
Document the behavior of multiple invocations of hooks.
Closes: https://github.com/dart-lang/native/issues/1739
We could keep `buildAssetTypes` as a list of strings for now. We might want to make link hooks work with multiple asset types later as a non-breaking change.
Both Dart and Flutter only pass `[CodeAsset.type]`, so they are already satisfying that every asset type has its own invocation.
=> [native_assets_cli] [doc] Document multiple invocation behavior

pkgs/native_toolchain_c/lib/src/cbuilder/run_cbuilder.dart, pkgs/native_toolchain_c/lib/src/native_toolchain/clang.dart, pkgs/native_toolchain_c/test/cbuilder/cbuilder_cross_windows_host_test.dart, pkgs/native_toolchain_c/test/cbuilder/testfiles/add/src/add.c, pkgs/native_toolchain_c/test/native_toolchain/clang_test.dart
Bug: https://github.com/dart-lang/native/issues/1892
It seems that both Clang via https://github.com/llvm/llvm-project/releases/tag/llvmorg-19.1.0, and Clang via the MSVC installer come with batteries included and link to the windows headers (added an use of `wprintf`).
(The Clang-for-Windows on the Dart CI does not come with batteries included: see https://github.com/dart-lang/native/issues/1892#issuecomment-2590974368.)
Does not add support for arm64 (neither msvc nor clang): https://github.com/dart-lang/native/issues/170
=> [native_toolchain_c] Support Clang on Windows

pkgs/native_toolchain_c/lib/src/cbuilder/compiler_resolver.dart, pkgs/native_toolchain_c/lib/src/cbuilder/run_cbuilder.dart
Closes: https://github.com/dart-lang/native/issues/1892
Using clang on Windows requires being run with the windows dev environment _or_ an MSVC toolchain installed which is discoverable on the system.
On the GitHub bots, MSVC comes pre-installed, so we can't reproduce the case where Clang cannot find the MSVC dev environment.
I've tested this locally by (1) uninstalling visual studio, (2) seeing that the build with Clang fails, (3) hardcoding in a dev environment (from depot_tools) in `native_toolchain_c`, and (4) seeing that that the tests pass.
=> [native_toolchain_c] Support Clang on Windows 2

pkgs/jnigen/CHANGELOG.md, pkgs/jnigen/lib/src/bindings/dart_generator.dart, pkgs/jnigen/lib/src/bindings/linker.dart, pkgs/jnigen/lib/src/elements/elements.dart, pkgs/jnigen/test/kotlin_test/bindings/kotlin.dart, pkgs/jnigen/test/kotlin_test/kotlin/src/main/kotlin/com/github/dart_lang/jnigen/Nullability.kt
Closes #1906.
Keep the original nullability of a type argument `T extends Foo`, so that even if the type provided is not explicitly identified as nullable or non-nullable (due to a missing annotation or being a kotlin wildcard), it's still generated with regards to the constraints of the top-type `Foo`.
=> [jnigen] Respect top-type nullability of type arguments

pkgs/native_assets_builder/CHANGELOG.md, pkgs/native_assets_builder/lib/src/build_runner/build_planner.dart, pkgs/native_assets_builder/lib/src/build_runner/build_runner.dart, pkgs/native_assets_builder/lib/src/package_layout/package_layout.dart, pkgs/native_assets_builder/test/build_runner/build_planner_test.dart, pkgs/native_assets_builder/test/build_runner/build_runner_reusability_test.dart, pkgs/native_assets_builder/test/build_runner/build_runner_test.dart, pkgs/native_assets_builder/test/build_runner/concurrency_shared_test_helper.dart, pkgs/native_assets_builder/test/build_runner/concurrency_test_helper.dart, pkgs/native_assets_builder/test/build_runner/helpers.dart, pkgs/native_assets_builder/test/build_runner/package_layout_test.dart, pkgs/native_assets_builder/test/build_runner/pub_workspace_test.dart, pkgs/native_assets_builder/test/helpers.dart, pkgs/native_assets_builder/test_data/cyclic_package_1/pubspec.yaml, pkgs/native_assets_builder/test_data/cyclic_package_2/pubspec.yaml, pkgs/native_assets_builder/test_data/dart_app/pubspec.yaml, pkgs/native_assets_builder/test_data/fail_on_os_sdk_version_link/pubspec.yaml, pkgs/native_assets_builder/test_data/native_add/pubspec.yaml, pkgs/native_assets_builder/test_data/native_add_version_skew/hook/build.dart, pkgs/native_assets_builder/test_data/native_add_version_skew/pubspec.yaml, pkgs/native_assets_builder/test_data/native_add_version_skew/test/native_add_test.dart, pkgs/native_assets_builder/test_data/native_subtract/pubspec.yaml, pkgs/native_assets_builder/test_data/wrong_linker/pubspec.yaml
Bug: https://github.com/dart-lang/native/issues/1905
* `.dart_tool/package_config.json` is possibly in a ancestor directory
* `runPackageName` argument is now required for build/link hooks.
* Only native assets that are a dependency are built (instead of all packages in the package resolution of the whole workspace).
* Don't crash if the root package directory name is not identical to the package name.
* Native assets are now shared for the whole workspace. (The package resolution is identical, so the native assets should be identical.
Doesn't yet address:
* `runPackageName` argument should be required for "if there are packages with native assets", the native assets experiment only has to be enabled if a dependency has a hook. (requires a bigger refactoring)
=> [native_assets_builder] Support pub workspaces

pkgs/native_assets_builder/lib/src/build_runner/build_runner.dart, pkgs/native_assets_builder/lib/src/package_layout/package_layout.dart, pkgs/native_assets_builder/test/build_runner/build_planner_test.dart, pkgs/native_assets_builder/test/build_runner/build_runner_reusability_test.dart, pkgs/native_assets_builder/test/build_runner/concurrency_shared_test_helper.dart, pkgs/native_assets_builder/test/build_runner/concurrency_test_helper.dart, pkgs/native_assets_builder/test/build_runner/helpers.dart, pkgs/native_assets_builder/test/build_runner/package_layout_test.dart
We don't ever invoke the native assets builder with a different `runPackageName` and the same `packageConfig`. All Dart and Flutter commands have a single runPackageName` in mind.
In a subsequent refactoring, the `PackageLayout` will move to the native assets builder constructor so that the build planner can cache the package graph fully.
(Part of a larger refactoring that will make the `NativeAssetsBuildRunner` take more arguments in the constructor such as the package config, and reduces the number of arguments to the `build` and `link` methods.)
=> [native_assets_builder] Move `runPackageName` into `PackageLayout`

pkgs/native_assets_builder/lib/src/build_runner/build_runner.dart, pkgs/native_assets_builder/test/build_runner/build_runner_reusability_test.dart, pkgs/native_assets_builder/test/build_runner/concurrency_shared_test_helper.dart, pkgs/native_assets_builder/test/build_runner/concurrency_test_helper.dart, pkgs/native_assets_builder/test/build_runner/helpers.dart
All Dart and Flutter commands have a single package config and runPackageName.
Part of a larger refactoring that will make the `NativeAssetsBuildRunner` take more arguments in the constructor such as the package config, and reduces the number of arguments to the `build` and `link` methods.
This will enable:
* Caching `BuildPlanner` logic (only one `runPackageName`)
* Changing `packagesWithAssets` to take `runPackageName` into account (and possibly moving it to the native assets builder instead). https://github.com/dart-lang/native/issues/1905
=> [native_assets_builder] Move `packageLayout` to builder constructor

pkgs/native_assets_builder/lib/native_assets_builder.dart, pkgs/native_assets_builder/lib/src/build_runner/build_planner.dart, pkgs/native_assets_builder/lib/src/build_runner/build_runner.dart, pkgs/native_assets_builder/lib/src/package_layout/package_layout.dart, pkgs/native_assets_builder/pubspec.yaml, pkgs/native_assets_builder/test/build_runner/build_planner_test.dart, pkgs/native_assets_builder/test/build_runner/pub_workspace_test.dart, pkgs/native_assets_builder/test_data/manifest.yaml, pkgs/native_assets_builder/test_data/no_hook/lib/no_hook.dart, pkgs/native_assets_builder/test_data/no_hook/manifest.yaml, pkgs/native_assets_builder/test_data/no_hook/pubspec.yaml
Closes: https://github.com/dart-lang/native/issues/1905
This does a bigger refactoring to take `runPackageName` into account when checking for "if there are packages with native assets".
It changes the public API in the following way:
* `PackageLayout` no longer has methods for if packages have hooks, as it does not take into account the dependency graph
* `NativeAssetsBuildRunner` now exposes a method to query whether any packages in the dependencies have build hooks
* (The implementation is in the `BuildPlanner`, and this class stays internal.)
This means that `PackageLayout` has the API to provide the right package layout to the `NativeAssetsBuildRunner`, and the `NativeAssetsBuildRunner` has the methods to be queried by embedders/launchers.
=> [native_assets_builder] Support pub workspaces 2

pkgs/jni/lib/src/nio/jbuffer.dart
Closes #1920.
Clarifies that the `arrayOffset` is needed when extracting the elements from the `array` of a `JBuffer`.
=> [jni] Clarify `JBuffer.array` docs

.github/workflows/native.yaml, pkgs/native_assets_builder/lib/src/build_runner/build_runner.dart, pkgs/native_assets_builder/pubspec.yaml, pkgs/native_assets_builder/test/build_runner/version_skew_test.dart, pkgs/native_assets_builder/test_data/manifest.yaml, pkgs/native_assets_builder/test_data/native_add_version_skew_2/hook/build.dart, pkgs/native_assets_builder/test_data/native_add_version_skew_2/manifest.yaml, pkgs/native_assets_builder/test_data/native_add_version_skew_2/pubspec.yaml, pkgs/native_assets_cli/lib/native_assets_cli_internal.dart
Since we know the `PackageConfig`, we can check in the native assets builder what version of `native_assets_cli` is used in the hook implementations.
Since we know the `PackageConfig`, we also know the package root of `native_assets_cli` and try to find the version of the protocol it's using.
If we find that the protocol version is no longer supported, give an error message early and stop building native assets instead of actually invoking the hook.
=> [native_assets_builder] Fail early on too old `native_assets_cli`

pkgs/native_assets_builder/CHANGELOG.md, pkgs/native_assets_builder/lib/src/build_runner/build_runner.dart, pkgs/native_assets_builder/pubspec.yaml
The `package_config.json` can update with irrelevant information (such as the timestamp). Don't recompile the hooks if only the timestamp changed.
Testing: The existing tests started failing. Possibly after `dartdev` started running `pub get` more often automatically after https://dart-review.googlesource.com/c/sdk/+/404583.
=> [native_assets_builder] Fix hook compile caching 

pkgs/jni/CHANGELOG.md, pkgs/jni/lib/src/jarray.dart, pkgs/jni/test/jarray_test.dart
Allows a JArray to be constructed from an iterable of elements.
---
<details>
- Changes to packages require [corresponding tests](https://github.com/dart-lang/.github/blob/main/CONTRIBUTING.md#Testing …
=> [jni] Add support for JArray.of()

pkgs/ffigen/lib/src/code_generator/library.dart, pkgs/ffigen/pubspec.yaml
Was hitting an issue in some of my projects that `ffigen: ^16.0.0` depends on `dart_style: <3.0.0` which depends on `analyzer: <7.0.0`, but analyzer `7.0.0` is being used by some other packages, which makes ffigen the bottleneck. This PR fixes that by simply bumping `dart_style` from `^2.3.7` to `^3.0.0`.
The biggest change from `dart_style` (see [the changelog](https://pub.dev/packages/dart_style/changelog)) is the _mandatory_ inclusion of the language version, in order to facilitate the new 3.7 formatter. Luckily, ffigen already passed this parameter voluntarily, so no code change was necessary. 
---
<details>
- …
=> [ffigen] Bumped dart_style to 3.0

pkgs/jni/CHANGELOG.md, pkgs/jni/lib/src/jobject.dart, pkgs/jni/test/jobject_test.dart
<details>
Note that many Dart repos have a weekly cadence for reviewing …
=> [jni] Add the ability to check if a `JObject` is a subclass of a Java class.

.github/workflows/publish.yaml
I believe it would be good if we were to add tags for FFIgen and JNIgen, but autopublishing currently doesn't work. So we should skip the workflow for those.
=> [infra] Skip autopublishing for Flutter SDK packages

.github/workflows/publish.yaml
Aparently autosubmit wasn't stopped by https://github.com/dart-lang/native/actions/runs/13030317922 🙈 
Documentation on how to use this correctly:
* https://docs.github.com/en/actions/writing-workflows/workflow-syntax-for-github-actions#example-including-branches-and-tags (It doesn't detail what a "pattern" is, apparently not really a regex?
* https://docs.github.com/en/actions/writing-workflows/workflow-syntax-for-github-actions#filter-pattern-cheat-sheet (apparently underscore patterns are not supported. However, the autopublisher has been working just fine for `native_assets_cli-v0.11.0`...)
=> [infra] Skip autopublishing for Flutter SDK packages - 2

pkgs/jni/lib/src/jni.dart
Closes #1952.
A regression that happened after https://github.com/dart-lang/native/pull/1916.
This further highlights the fact that #1155 is needed.
=> [jni] Fix jni on Android

pkgs/jni/CHANGELOG.md, pkgs/jni/lib/src/jarray.dart, pkgs/jni/test/jarray_test.dart
- Much of the documentation is taken from `Int8List` and `List`.
- The difference between the `of`, `from` and `fromList` factories might be confusing. `from` and `fromList` are consistent with Dart. `of` is an extra method for converting Java objects stored in Dart lists into Java arrays.
---
<details>
- Most changes should add an entry to the changelog and may need to [rev the pubspec package …
=> [jni] Add `JByteArray.from`

pkgs/jni/CHANGELOG.md, pkgs/jnigen/CHANGELOG.md, pkgs/jnigen/java/src/main/java/com/github/dart_lang/jnigen/apisummarizer/doclet/ElementBuilders.java, pkgs/jnigen/pubspec.yaml, pkgs/jnigen/test/simple_package_test/generate.dart, pkgs/jnigen/test/simple_package_test/generated_files_test.dart, pkgs/jnigen/test/summary_test.dart
The doclet parser (unlike asm) would not deeply parse all of the type parameters in nested classes. For example in `Foo<T>.Bar<U>.Baz<S>`, it'd only have `[S]` instead of `[T, U, S]`.
This is not a breaking change. Bumped the version of jnigen to 0.14.0 only to match jni's to prepare for today's publishing.
Closes #1901.
=> [jnigen] Fix doclet type parameter parsing

pkgs/swift2objc/lib/src/parser/parsers/declaration_parsers/parse_initializer_declaration.dart, pkgs/swift2objc/lib/src/parser/parsers/declaration_parsers/parse_variable_declaration.dart, pkgs/swift2objc/lib/src/transformer/transformers/transform_compound.dart, pkgs/swift2objc/lib/src/transformer/transformers/transform_initializer.dart, pkgs/swift2objc/lib/src/transformer/transformers/transform_variable.dart, pkgs/swift2objc/test/integration/async_init_input.swift, pkgs/swift2objc/test/integration/async_init_output.swift, pkgs/swift2objc/test/integration/async_prop_input.swift, pkgs/swift2objc/test/integration/async_prop_output.swift
- Closes #1778 
---
<details>
Note that many Dart repos have a weekly …
=> [swift2objc] Support async initializers and properties

pkgs/ffigen/CHANGELOG.md, pkgs/ffigen/lib/src/code_generator/global.dart, pkgs/ffigen/test/code_generator_tests/expected_bindings/_expected_global_bindings.dart, pkgs/ffigen/test/header_parser_tests/globals.h, pkgs/ffigen/test/header_parser_tests/globals_test.dart, pkgs/ffigen/test/native_test/_expected_native_test_bindings.dart, pkgs/ffigen/test/native_test/native_test.c, pkgs/ffigen/test/native_test/native_test.dart, pkgs/ffigen/test/native_test/native_test.def
Closes #1922
- Handled ConstantArray declaration (`a[3]`) in global variables to remove extra Pointer reference.
- Updated tests, changelog
---
<details> …
=> [ffigen] Handle ConstantArray in Global

.github/dependabot.yaml
Trying https://docs.github.com/en/code-security/dependabot/working-with-dependabot/dependabot-options-reference#prefix to satisfy our PR title checker.
=> [infra] Configure dependabot commit messages

pkgs/jnigen/CHANGELOG.md, pkgs/jnigen/java/src/main/java/com/github/dart_lang/jnigen/apisummarizer/elements/KotlinFunction.java, pkgs/jnigen/lib/src/bindings/dart_generator.dart, pkgs/jnigen/lib/src/bindings/kotlin_processor.dart, pkgs/jnigen/lib/src/bindings/linker.dart, pkgs/jnigen/lib/src/elements/elements.dart, pkgs/jnigen/lib/src/elements/elements.g.dart, pkgs/jnigen/pubspec.yaml, pkgs/jnigen/test/kotlin_test/bindings/kotlin.dart, pkgs/jnigen/test/kotlin_test/kotlin/src/main/kotlin/com/github/dart_lang/jnigen/Operators.kt, pkgs/jnigen/test/kotlin_test/runtime_test_registrant.dart
Generate `+`, `-`, `*`, `/`, `%`, `[]`, `[]=` operators in Dart. Some of Dart operators don't exist in Kotlin and vice-versa. These are the group of operators that make sense. Also we only generate them if they fit the Dart model (For example, `[]` can take multiple parameters in Kotlin, while in Dart it can only get 1). If there are multiple overloads, only generate the first matching one as an operator.
We still generate the original method, this is consistent with Kotlin, as `a.add(b)` and `a + b` are equivalent.
=> [jnigen] Support Kotlin operators

pkgs/jnigen/lib/src/bindings/renamer.dart, pkgs/jnigen/lib/src/elements/j_elements.dart, pkgs/jnigen/test/user_visitors.dart
- small fix for renaming constructors.
---
<details>
Note that many Dart …
=> [jnigen] small fix for renaming constructors

pkgs/objective_c/CHANGELOG.md, pkgs/objective_c/ffigen_c.yaml, pkgs/objective_c/lib/objective_c.dart, pkgs/objective_c/lib/src/c_bindings_generated.dart, pkgs/objective_c/lib/src/os_version.dart, pkgs/objective_c/pubspec.yaml, pkgs/objective_c/src/objective_c.h, pkgs/objective_c/src/objective_c.m, pkgs/objective_c/src/os_version.h, pkgs/objective_c/test/os_version_test.dart
Add a `osVersion` getter to package:objective_c that returns the current MacOS/iOS version.
Related bugs: https://github.com/dart-lang/native/issues/1422 and https://github.com/dart-lang/native/issues/300
=> [objective_c] `osVersion` API

pkgs/objective_c/CHANGELOG.md, pkgs/objective_c/ffigen_c.yaml, pkgs/objective_c/lib/src/c_bindings_generated.dart, pkgs/objective_c/lib/src/internal.dart, pkgs/objective_c/pubspec.yaml, pkgs/objective_c/src/objective_c.c, pkgs/objective_c/src/objective_c.h
`Dart_InitializeApiDL` stores function pointers for various Dart API methods in static variables. Those variables are global per dylib. There may be multiple dylibs in an app that contain `Dart_InitializeApiDL`, thus multiple copies of the static variables. If we're not careful about which `Dart_InitializeApiDL` we're invoking, we'll initialize the wrong static variables, causing NPEs when we later try to invoke those Dart API functions.
Wrapping `Dart_InitializeApiDL` in `DOBJC_InitializeApi` (a wrapper function that only exists in our dylib) ensures that we're invoking the correct copy of `Dart_InitializeApiDL`.
Also, prepare to immediately publish package:objective_c v5.0.0
Fixes https://github.com/dart-lang/native/issues/1978
=> [objective_c] Wrap `Dart_InitializeApiDL` in `DOBJC_InitializeApi`

pkgs/ffigen/CHANGELOG.md, pkgs/ffigen/lib/src/code_generator/compound.dart, pkgs/ffigen/lib/src/code_generator/constant.dart, pkgs/ffigen/lib/src/code_generator/enum_class.dart, pkgs/ffigen/lib/src/code_generator/func.dart, pkgs/ffigen/lib/src/code_generator/global.dart, pkgs/ffigen/lib/src/code_generator/objc_category.dart, pkgs/ffigen/lib/src/code_generator/objc_interface.dart, pkgs/ffigen/lib/src/code_generator/objc_methods.dart, pkgs/ffigen/lib/src/code_generator/objc_protocol.dart, pkgs/ffigen/lib/src/code_generator/typealias.dart, pkgs/ffigen/lib/src/code_generator/writer.dart, pkgs/ffigen/lib/src/config_provider/config_types.dart, pkgs/ffigen/lib/src/config_provider/spec_utils.dart, pkgs/ffigen/lib/src/header_parser/parser.dart, pkgs/ffigen/lib/src/header_parser/sub_parsers/api_availability.dart, pkgs/ffigen/lib/src/header_parser/sub_parsers/compounddecl_parser.dart, pkgs/ffigen/lib/src/header_parser/sub_parsers/enumdecl_parser.dart, pkgs/ffigen/lib/src/header_parser/sub_parsers/functiondecl_parser.dart, pkgs/ffigen/lib/src/header_parser/sub_parsers/objccategorydecl_parser.dart, pkgs/ffigen/lib/src/header_parser/sub_parsers/objcinterfacedecl_parser.dart, pkgs/ffigen/lib/src/header_parser/sub_parsers/objcprotocoldecl_parser.dart, pkgs/ffigen/lib/src/header_parser/sub_parsers/unnamed_enumdecl_parser.dart, pkgs/ffigen/lib/src/header_parser/utils.dart, pkgs/ffigen/lib/src/strings.dart, pkgs/ffigen/lib/src/visitor/apply_config_filters.dart, pkgs/ffigen/lib/src/visitor/list_bindings.dart, pkgs/ffigen/test/native_objc_test/deprecated_test.dart, pkgs/ffigen/test/unit_tests/api_availability_test.dart, pkgs/objective_c/lib/src/objective_c_bindings_generated.dart
Add a `max` field to the `external-versions` config, and extend the API versioning checks to check the max version vs the version that the API was introduced. Also, if an API is available in some versions, but not all of them, generate documentation describing the versions.
The main changes are in api_availability.dart. Instead of just returning a bool for whether the API is available, we now return an `Availability` enum, to also represent partial availability.
The version check itself has also become more complicated, since we're now checking the overlap of two ranges, instead of just checking one version vs a range. Broadly speaking, if `apiMin <= configMin && apiMax >= configMax`, the API is `Availability.all`, and if `apiMin <= confMax && apiMax > confMin` then the API is …
=> [ffigen] Add external-versions.*.max

pkgs/ffigen/CHANGELOG.md, pkgs/ffigen/lib/src/code_generator/objc_built_in_functions.dart, pkgs/ffigen/lib/src/code_generator/objc_interface.dart, pkgs/ffigen/lib/src/code_generator/objc_methods.dart, pkgs/ffigen/lib/src/code_generator/objc_protocol.dart, pkgs/ffigen/lib/src/header_parser/sub_parsers/api_availability.dart, pkgs/ffigen/lib/src/header_parser/sub_parsers/compounddecl_parser.dart, pkgs/ffigen/lib/src/header_parser/sub_parsers/enumdecl_parser.dart, pkgs/ffigen/lib/src/header_parser/sub_parsers/functiondecl_parser.dart, pkgs/ffigen/lib/src/header_parser/sub_parsers/objccategorydecl_parser.dart, pkgs/ffigen/lib/src/header_parser/sub_parsers/objcinterfacedecl_parser.dart, pkgs/ffigen/lib/src/header_parser/sub_parsers/objcprotocoldecl_parser.dart, pkgs/ffigen/lib/src/header_parser/sub_parsers/unnamed_enumdecl_parser.dart, pkgs/ffigen/pubspec.yaml, pkgs/ffigen/test/native_objc_test/runtime_version_config.yaml, pkgs/ffigen/test/native_objc_test/runtime_version_test.dart, pkgs/ffigen/test/native_objc_test/runtime_version_test.m, pkgs/ffigen/test/unit_tests/api_availability_test.dart, pkgs/ffigen/test/unit_tests/subtyping_test.dart, pkgs/objective_c/CHANGELOG.md, pkgs/objective_c/lib/src/objective_c_bindings_generated.dart, pkgs/objective_c/lib/src/os_version.dart, pkgs/objective_c/pubspec.yaml
Add a runtime check that the OS version is >= the version that an API was introduced. Do this check in interface constructors, interface methods, and category methods.
Fixes https://github.com/dart-lang/native/issues/300
=> [ffigen] Runtime version checks

pkgs/native_toolchain_c/lib/src/native_toolchain/android_ndk.dart
NDK directories can be empty (apart from `.installer/`) after uninstalling NDK directories.
=> [native_toolchain_c] Don't fail on uninstalled NDKs

pkgs/ffigen/CHANGELOG.md, pkgs/ffigen/README.md, pkgs/ffigen/lib/src/config_provider/config.dart, pkgs/ffigen/pubspec.yaml
Unlike `typedefTypeMappings`, `structTypeMappings`, `unionTypeMappings`, and `nativeTypeMappings`, `usrTypeMappings` is keyed by the USR, which is not a field on `ImportedType`. So `usrTypeMappings` can't be constructed from a `List<ImportedType>`, and we have to take the `Map<String, ImportedType>` as an input instead.
Also, add the changelog and readme entries that I forgot to add in #2007
Fixes https://github.com/dart-lang/native/issues/1999
=> [ffigen] Fix `usrTypeMappings` field of `Config` factory constructor

pkgs/ffigen/test/native_objc_test/block_test.dart, pkgs/ffigen/test/native_objc_test/protocol_test.dart
Looks like the tests added in https://github.com/dart-lang/native/pull/2017 are slightly flaky: https://github.com/dart-lang/native/actions/runs/13424159867/job/37503744811#step:7:838
=> [ffigen] Fix flaky test

pkgs/ffigen/lib/src/config_provider/yaml_config.dart
The next release of ffigen, v18, is the "Feature Readiness" version, so it's probably time to remove the experimental warning. We will still have breaking changes from time to time, but we've been doing major version bumps for such changes for a while. So it's not really true that "the API may change in a breaking way without notice" anymore.
Fixes https://github.com/dart-lang/native/issues/2000
=> [ffigen] Remove experimental ObjC warning

pkgs/jni/CHANGELOG.md, pkgs/jni/java/src/main/java/com/github/dart_lang/jni/PortProxyBuilder.java, pkgs/jni/src/dartjni.c
Closes #1908 using the proposed method in https://github.com/dart-lang/native/issues/1908#issuecomment-2651104303.
I tested this locally, but we don't have the setup to automate Android tests on CI: #1155.
=> [jni] Fix interface implementation deadlock on the main thread

pkgs/jnigen/CHANGELOG.md, pkgs/jnigen/lib/src/bindings/renamer.dart, pkgs/jnigen/pubspec.yaml
=> [jnigen] `factory` can be used as a method name without renaming

pkgs/native_toolchain_c/test/cbuilder/cbuilder_test.dart
The builder API is rather error prone (https://github.com/dart-lang/native/issues/2059).
Here is one wrong invocation.
=> [native_toolchain_c] Correctly set up hook input

pkgs/ffigen/lib/src/code_generator/objc_built_in_functions.dart, pkgs/ffigen/lib/src/code_generator/objc_protocol.dart, pkgs/ffigen/test/native_objc_test/protocol_config.yaml, pkgs/ffigen/test/native_objc_test/protocol_test.dart, pkgs/ffigen/test/native_objc_test/protocol_test.h, pkgs/ffigen/test/native_objc_test/protocol_test.m, pkgs/ffigen/test/native_objc_test/util.dart, pkgs/objective_c/ffigen_c.yaml, pkgs/objective_c/lib/src/c_bindings_generated.dart, pkgs/objective_c/lib/src/internal.dart, pkgs/objective_c/lib/src/objective_c_bindings_generated.dart, pkgs/objective_c/lib/src/protocol_builder.dart, pkgs/objective_c/src/objective_c_runtime.h, pkgs/objective_c/src/protocol.h, pkgs/objective_c/src/protocol.m
Clean up the class object when the implementation object and the builder have been destroyed, by wrapping it in a `DOBJCDartProtocolClass` object that calls `objc_disposeClassPair` in its `dispose` method, and having the builder and instances hold a reference to this object.
Also, since we're not allowing adding more methods after building the protocol, we don't have to copy the method table during instantiation anymore.
Finally, re-add a bunch of other GC tests that I accidentally deleted.
Fixes #2042
=> [ffigen] Protocol polish

pkgs/native_assets_builder/lib/src/build_runner/build_runner.dart
Closes: #2077 
As @dcharkes suggested, this PR add `WINDIR` and `SYSTEMDRIVE` to `hookEnvironmentVariablesFilter` at https://github.com/dart-lang/native/blob/318f841b7520ae29d93f4678f3b759849369f5c1/pkgs/native_assets_builder/lib/src/build_runner/build_runner.dart#L426-L436
---
<details>
- Contributions to our repos should follow the [Dart …
=> [native_assets_builder] add `WINDIR` and `SYSTEMDRIVE` to allowed env list

.github/workflows/hook.yaml, pkgs/hook/tool/generate.dart, pkgs/native_assets_cli/lib/src/code_assets/architecture.dart, pkgs/native_assets_cli/lib/src/code_assets/c_compiler_config.dart, pkgs/native_assets_cli/lib/src/code_assets/code_asset.dart, pkgs/native_assets_cli/lib/src/code_assets/config.dart, pkgs/native_assets_cli/lib/src/code_assets/link_mode.dart, pkgs/native_assets_cli/lib/src/code_assets/link_mode_preference.dart, pkgs/native_assets_cli/lib/src/code_assets/os.dart, pkgs/native_assets_cli/lib/src/code_assets/syntax.g.dart, pkgs/native_assets_cli/lib/src/config.dart, pkgs/native_assets_cli/lib/src/data_assets/data_asset.dart, pkgs/native_assets_cli/lib/src/data_assets/syntax.g.dart, pkgs/native_assets_cli/lib/src/encoded_asset.dart, pkgs/native_assets_cli/lib/src/hook/syntax.g.dart, pkgs/native_assets_cli/lib/src/metadata.dart, pkgs/native_assets_cli/test/build_config_test.dart
Bug:
* https://github.com/dart-lang/native/issues/1826
This PR generates a Dart syntax from the JSON schemas for hooks and the extensions.
Moreover, it uses the generated syntax in in `package:native_assets_cli` to replace the manually written JSON serialization and deserialization.
This PR is meant to be behavior preserving for the current implementation. Any issues with the existing implementation are carried forward, and will be addressed later.
_(It is a non-goal of this PR to change the current state.)_
Before this PR, the semantic API immediately had a `toJson` and `fromJson` that took care of any migrations in progress from old to new syntax.
After this PR, the semantic API produces and consumes syntax object (and takes care of migrations in progress), and the syntax does `toJson` …
=> [native_assets_cli] Generate syntax from schemas

pkgs/ffigen/CHANGELOG.md, pkgs/ffigen/lib/src/code_generator/objc_built_in_functions.dart, pkgs/ffigen/pubspec.yaml, pkgs/objective_c/CHANGELOG.md, pkgs/objective_c/lib/src/objective_c_bindings_generated.dart, pkgs/objective_c/lib/src/os_version.dart, pkgs/objective_c/pubspec.yaml, pkgs/objective_c/test/os_version_test.dart
I also added a `checkOsVersion` function to package:objective_c that makes it easier to write version checks.
=> [ffigen] Prepare to publish v18

pkgs/native_toolchain_c/lib/src/cbuilder/cbuilder.dart, pkgs/native_toolchain_c/lib/src/cbuilder/clinker.dart, pkgs/native_toolchain_c/lib/src/cbuilder/ctool.dart, pkgs/native_toolchain_c/lib/src/cbuilder/run_cbuilder.dart, pkgs/native_toolchain_c/test/cbuilder/cbuilder_cross_windows_host_test.dart, pkgs/native_toolchain_c/test/cbuilder/cbuilder_test.dart, pkgs/native_toolchain_c/test/cbuilder/testfiles/defines/src/defines.c, pkgs/native_toolchain_c/test/cbuilder/testfiles/defines/src/forcedInclude.c
Fix #2095 
- This PR addresses the issue https://github.com/dart-lang/native/issues/2095 where defines that include double quotation marks would break the command-line execution using `CL.EXE`
**How it works**
`CBuilder.libaray` and `CBuilder.executable` take a new optional argument `forcedIncludes` which is a list of file paths to source files, these source files, if defined will be prepended by the compiler to each source.
In `clang`, this uses the `-include<file>` argument, in `CL.exe` this uses the `/FI<file>` argument. See the related issue: https://github.com/dart-lang/native/issues/2095
I'm currently on OSX so I haven't run the test on windows yet
---
<details>
- See our [contributor …
=> [native_toolchain_c] Forced includes

pkgs/json_syntax_generator/lib/src/generator/helper_library.dart, pkgs/json_syntax_generator/lib/src/generator/normal_class_generator.dart, pkgs/json_syntax_generator/lib/src/generator/property_generator.dart, pkgs/native_assets_cli/lib/src/code_assets/c_compiler_config.dart, pkgs/native_assets_cli/lib/src/code_assets/code_asset.dart, pkgs/native_assets_cli/lib/src/code_assets/config.dart, pkgs/native_assets_cli/lib/src/code_assets/syntax.g.dart, pkgs/native_assets_cli/lib/src/config.dart, pkgs/native_assets_cli/lib/src/data_assets/syntax.g.dart, pkgs/native_assets_cli/lib/src/encoded_asset.dart, pkgs/native_assets_cli/lib/src/hook/syntax.g.dart, pkgs/native_assets_cli/test/build_input_test.dart, pkgs/native_assets_cli/test/code_assets/config_test.dart, pkgs/native_assets_cli/test/code_assets/validation_test.dart, pkgs/native_assets_cli/test/helpers.dart, pkgs/native_assets_cli/test/link_input_test.dart
Bug: https://github.com/dart-lang/native/issues/1826
This PR adds the path that was navigated through the JSON to the syntax classes. This makes syntax errors more descriptive: `Unexpected value '123' for 'target_os'. Expected a String.` -> `Unexpected value '123' (int) for 'config.code.target_os'. Expected a String.`.
Because the data asset and code asset extensions don't know the internals of the base protocol extension, the extension points now expose both a `json` and a `jsonPath`. That path is then used to instantiate the syntax view of the extension, so it can give more precise error messages.
* For `CodeConfig` this comes naturally, it's a clean view.
* For `EncodedAsset` this is somewhat weird because it is half-used as value class: https://github.com/dart-lang/native/issues/2045 …
=> [native_assets_cli] Add paths to syntax views

pkgs/native_assets_cli/lib/src/code_assets/validation.dart, pkgs/native_assets_cli/lib/src/data_assets/validation.dart
We were missing some validation for assets for linking:
* `BuildOutput` both code and data assets.
* `LinkInput` for code assets.
Code assets for linking should not have their link mode checked.
=> [native_assets_cli] Validate assets for linking

pkgs/json_syntax_generator/lib/src/generator/helper_library.dart, pkgs/json_syntax_generator/lib/src/generator/normal_class_generator.dart, pkgs/json_syntax_generator/lib/src/generator/property_generator.dart, pkgs/json_syntax_generator/lib/src/model/property_info.dart, pkgs/native_assets_cli/lib/src/code_assets/syntax.g.dart, pkgs/native_assets_cli/lib/src/code_assets/validation.dart, pkgs/native_assets_cli/lib/src/data_assets/syntax.g.dart, pkgs/native_assets_cli/lib/src/data_assets/validation.dart, pkgs/native_assets_cli/lib/src/extension.dart, pkgs/native_assets_cli/lib/src/hook/syntax.g.dart, pkgs/native_assets_cli/lib/src/validation.dart
Bug: https://github.com/dart-lang/native/issues/1826
This PR adds generated `validate` functions on the syntax classes that check the type and nullability of the required fields.
This PR does not separate syntax and semantic validation in the `ProtocolExtension` as proposed in https://github.com/dart-lang/native/issues/2088. The inputs/outputs classes expose the underlying JSON and are lazy. So, they don't fail on syntax errors unless traversed.
This PR does not yet address:
* https://github.com/dart-lang/native/issues/2039 (follow up PR)
* Non-local syntax (e.g. `file` is required if `link_mode` is x).
To prevent crashes in the semantic validation, the semantic validation is not run when when syntactic errors are found. To prevent confusion for users, an extra error message is added that …
=> [native_assets_cli] Syntax validation

pkgs/code_assets/doc/schema/shared/shared_definitions.schema.json, pkgs/code_assets/test/schema/schema_test.dart, pkgs/native_assets_cli/lib/src/code_assets/code_asset.dart, pkgs/native_assets_cli/lib/src/code_assets/config.dart, pkgs/native_assets_cli/lib/src/code_assets/syntax.g.dart, pkgs/native_assets_cli/lib/src/code_assets/validation.dart, pkgs/native_assets_cli/test/code_assets/validation_test.dart
Closes https://github.com/dart-lang/native/issues/2039
Makes fields required in the syntax instead of semantic errors. The code for the semantic errors is simply deleted now.
=> [native_assets_cli] Fix syntax required fields

pkgs/hook/tool/generate_syntax.dart, pkgs/json_syntax_generator/lib/src/generator/normal_class_generator.dart, pkgs/json_syntax_generator/lib/src/model/class_info.dart, pkgs/json_syntax_generator/lib/src/model/property_info.dart, pkgs/json_syntax_generator/lib/src/parser/schema_analyzer.dart, pkgs/native_assets_cli/lib/src/code_assets/syntax.g.dart, pkgs/native_assets_cli/lib/src/data_assets/syntax.g.dart, pkgs/native_assets_cli/test/code_assets/validation_test.dart
Bug: https://github.com/dart-lang/native/issues/1826
Changes the constructors of tagged union super classes to be factories and to branch on the known sub classes. This fixes the syntax validation for tagged unions.
This PR also:
1. splits the `ClassInfo` to only support subclassing in `NormalClassInfo` (the enum classes don't allow subclassing),and
2. refactors the `NormalClassGenerator` in multiple methods for better readability, and
3. adds a `-d` (dump) parameter to the generator to dump the representation halfway in the pipeline as a text file.
=> [native_assets_cli] Validate tagged union syntax

pkgs/json_syntax_generator/lib/src/generator/helper_library.dart, pkgs/json_syntax_generator/lib/src/generator/normal_class_generator.dart, pkgs/json_syntax_generator/lib/src/generator/property_generator.dart, pkgs/json_syntax_generator/lib/src/model/class_info.dart, pkgs/json_syntax_generator/lib/src/model/property_info.dart, pkgs/json_syntax_generator/lib/src/parser/schema_analyzer.dart, pkgs/native_assets_cli/lib/src/code_assets/syntax.g.dart, pkgs/native_assets_cli/lib/src/data_assets/syntax.g.dart, pkgs/native_assets_cli/lib/src/hook/syntax.g.dart, pkgs/native_assets_cli/test/code_assets/validation_test.dart
Closes: https://github.com/dart-lang/native/issues/1826
This PR adds the final step to the generated syntax validation: conditionally required fields:
1. If target OS is `x`, then require `x` config in code config.
2. If target OS is `windows`, then require `windows` in the c compiler config (more info https://github.com/dart-lang/native/pull/1913).
3. If link mode is dynamic library bundled or static library, then require a file in a code asset.
We could consider trying to nest the fields under the condition, but that has other downsides:
RE 1: Then the OS is no longer an enum usable in the code-asset as OS field. (We could consider this if we remove the OS/arch from code asset outputs. We should be able to do this due to the code config always having a single OS and architecture anyway. …
=> [native_assets_cli] Validate conditionally required fields

pkgs/code_assets/doc/schema/shared/shared_definitions.generated.schema.json, pkgs/code_assets/doc/schema/shared/shared_definitions.schema.json, pkgs/code_assets/test/data/build_output_macos.json, pkgs/code_assets/test/schema/schema_test.dart, pkgs/data_assets/doc/schema/shared/shared_definitions.generated.schema.json, pkgs/data_assets/test/data/build_output.json, pkgs/data_assets/test/schema/schema_test.dart, pkgs/hook/doc/schema/hook/shared_definitions.schema.json, pkgs/hook/doc/schema/sdk/shared_definitions.schema.json, pkgs/hook/doc/schema/shared/shared_definitions.schema.json, pkgs/hook/test/data/build_output.json, pkgs/hook/test/schema/helpers.dart, pkgs/hook/tool/generate_schemas.dart, pkgs/hook/tool/generate_syntax.dart, pkgs/json_syntax_generator/lib/src/parser/schema_analyzer.dart, pkgs/native_assets_cli/lib/src/code_assets/link_mode_preference.dart, pkgs/native_assets_cli/lib/src/code_assets/syntax.g.dart, pkgs/native_assets_cli/lib/src/config.dart, pkgs/native_assets_cli/lib/src/hook/syntax.g.dart, pkgs/native_assets_cli/test/build_output_test.dart, pkgs/native_assets_cli/test/code_assets/config_test.dart
Closes: https://github.com/dart-lang/native/issues/2037
Closes: https://github.com/dart-lang/native/issues/2038
Fixes spelling in the JSON format:
* `prefer-dynamic` -> `prefer_dynamic`
* `prefer-static` -> `prefer_static`
* `assetsForLinking` -> `assets_for_linking`
* `pkgs/hook`, `pkgs/code_assets`, and `pkgs/data_assets`
* Introduces new schemas in the non-generated `.schema.json` files
* Updates the generated schemas to pick up on the new spelling for `assets_for_linking`.
* Adds test data for the new spelling.
* Added JSON schema tests for the new spelling.
* `package:native_assets_cli`
* Generated the syntax classes
* Deal with version skew in the mapping between syntax classes and semantic API
* For https://github.com/dart-lang/native/issues/2037
* Backwards compatibility older …
=> [native_assets_cli] Fix snake casing in JSON

pkgs/code_assets/doc/schema/shared/shared_definitions.schema.json, pkgs/json_syntax_generator/lib/src/parser/schema_analyzer.dart
Enums in JSON schemas are more concise and more apt than a list of consts.
Thanks @jonasfj for the tip!
(Also updates the schema analyzer to recognize them.)
=> [native_assets_cli] Use JSON enums where applicable

pkgs/hook/doc/schema/hook/shared_definitions.schema.json, pkgs/hook/doc/schema/sdk/shared_definitions.schema.json, pkgs/native_assets_builder/lib/src/build_runner/build_runner.dart, pkgs/native_assets_builder/test/build_runner/build_runner_caching_test.dart, pkgs/native_assets_builder/test/build_runner/build_runner_test.dart, pkgs/native_assets_builder/test/test_data/native_dynamic_linking_test.dart, pkgs/native_assets_cli/lib/src/config.dart, pkgs/native_assets_cli/test/build_input_test.dart, pkgs/native_assets_cli/test/code_assets/config_test.dart, pkgs/native_assets_cli/test/link_input_test.dart, pkgs/native_toolchain_c/test/cbuilder/cbuilder_cross_android_test.dart, pkgs/native_toolchain_c/test/cbuilder/cbuilder_cross_ios_test.dart, pkgs/native_toolchain_c/test/cbuilder/cbuilder_cross_linux_host_test.dart, pkgs/native_toolchain_c/test/cbuilder/cbuilder_cross_macos_host_test.dart, pkgs/native_toolchain_c/test/cbuilder/cbuilder_cross_windows_host_test.dart, pkgs/native_toolchain_c/test/cbuilder/cbuilder_test.dart, pkgs/native_toolchain_c/test/cbuilder/objective_c_test.dart
Closes: https://github.com/dart-lang/native/issues/2058
Implements `input.outputDirectory` on top of `input.outputDirectoryShared` in the hook API.
* `.dart_tool/`
* `native_assets_builder/`
* `<package_name>/`
* `<config-checksum>/`
* `input.json`
* `output.json`
* `dependencies.dependencies_hash_file.json`
* `package_config_hashable.json`
* `hook.dill`
* `hook.dill.d`
* `stderr.txt`
* `stdout.txt`
* `out/` <- old output directory, created by SDK (stays here for backwards compatibility purposes)
* `shared/`
* `<package_name>/`
* `build/` (`input.outputDirectoryShared`)
* `<config-checksum>/` <- new output directory, created by the hook
* `link/` (`input.outputDirectoryShared`)
* `<config-checksum>/` <- new output directory, created by the hook
The `out_dir` in the JSON is still emitted …
=> [native_assets_cli] Deprecate `output_directory`

pkgs/native_assets_cli/lib/src/config.dart, pkgs/native_assets_cli/lib/src/encoded_asset.dart, pkgs/native_assets_cli/lib/src/metadata.dart, pkgs/native_assets_cli/test/build_input_test.dart, pkgs/native_assets_cli/test/model/metadata_test.dart
Closes: https://github.com/dart-lang/native/issues/2045
We have two types of classes in the semantic API:
1. Pure views on top of a JSON.
These classes are mirrored by a builder class.
Objects from these classes cannot be passed from input to output in hooks.
These classes do not override `hashCode` and `operator ==`.
Examples: `CodeConfig`, `BuildInput`.
2. Data classes that eagerly copy all fields out of the JSON.
These classes have a public constructor with it's constituent fields.
Objects from these classes may be passed from input to output in hooks.
These classes do override `hashCode` and `operator ==`.
Examples: `CodeAsset`, `Architecture`, `OS`, `DataAsset`.
This changes `Metadata` and `EncodedAsset` to follow pattern 2 fully:
* All data is copied on construction.
* The map …
=> [native_assets_cli] Prevent `EncodedAsset` and `Metadata` hashcode changing

pkgs/native_assets_builder/test_data/add_asset_link/hook/link.dart, pkgs/native_assets_cli/lib/src/code_assets/code_asset.dart, pkgs/native_assets_cli/lib/src/code_assets/validation.dart
Bug: https://github.com/dart-lang/native/issues/2127
We want to remove these fields as they are redundant with the `CodeConfig`.
This PR does not yet change anything in the protocol, but removes all the uses of the fields.
When rolling this PR into Dart and Flutter, we'll need take the OS and architecture from the `CodeConfig` passed into a hook build.
=> [native_assets_cli] Remove `CodeAsset` `os` and `architecture` getters

pkgs/code_assets/CHANGELOG.md, pkgs/code_assets/LICENSE, pkgs/code_assets/README.md, pkgs/code_assets/pubspec.yaml, pkgs/data_assets/CHANGELOG.md, pkgs/data_assets/LICENSE, pkgs/data_assets/README.md, pkgs/data_assets/pubspec.yaml
Add the required files to publish packages on pub. (Validated with `dart pub publish --dry-run`.)
=> [native_assets_cli] `code_assets` and `data_assets` packages

pkgs/json_syntax_generator/lib/src/generator/helper_library.dart, pkgs/json_syntax_generator/lib/src/generator/normal_class_generator.dart, pkgs/json_syntax_generator/lib/src/model/dart_type.dart, pkgs/json_syntax_generator/lib/src/parser/schema_analyzer.dart, pkgs/native_assets_cli/lib/src/code_assets/config.dart, pkgs/native_assets_cli/lib/src/code_assets/syntax.g.dart, pkgs/native_assets_cli/lib/src/config.dart, pkgs/native_assets_cli/lib/src/data_assets/syntax.g.dart, pkgs/native_assets_cli/lib/src/encoded_asset.dart, pkgs/native_assets_cli/lib/src/hooks/syntax.g.dart
This PR introduce a common base class for all `JsonObject`s. This reduces code size.
Moreover, the properties that are an JSON object are now exposed as such. This makes a generated class a valid override of such property.
=> [native_assets_cli] Introduce `JsonObject` base class for syntax

pkgs/json_syntax_generator/lib/src/generator/normal_class_generator.dart, pkgs/json_syntax_generator/lib/src/model/dart_type.dart, pkgs/json_syntax_generator/lib/src/parser/schema_analyzer.dart, pkgs/native_assets_cli/lib/src/hooks/syntax.g.dart
This PR refactors field overrides in the syntax generator.
The analysis of overrides is now done on the `PropertyInfo` and `DartType` rather than on the `JsonSchema`.
If a field is overridden with a more specific type, generate the more specific type in the default constructor and pass it to the more general parameter in the super constructor invocation. (See the single change in the generated file.)
=> [native_assets_cli] Refactor overrides in syntax classes

pkgs/ffigen/CHANGELOG.md, pkgs/ffigen/lib/src/code_generator/writer.dart, pkgs/ffigen/pubspec.yaml, pkgs/objective_c/CHANGELOG.md, pkgs/objective_c/pubspec.yaml, pkgs/objective_c/src/objective_c_bindings_generated.m
Disable the `undeclared-selector` warning in generated ObjC code. The warning is triggered by references to the `getDOBJCDartProtocolMethodForSelector:` method, which is defined in package:objective_c, and there's no good way of importing the header that defines it.
Another approach would be to change `@selector(getDOBJCDartProtocolMethodForSelector:)` to `sel_registerName("getDOBJCDartProtocolMethodForSelector:")`. But presumably clang is doing some sort of caching or compile time evaluation of `@selector`, so `sel_registerName` would be a slight performance regression.
Fixes https://github.com/dart-lang/native/issues/2094
=> [ffigen] Fix clang warning

pkgs/code_assets/doc/schema/shared/shared_definitions.generated.schema.json, pkgs/code_assets/doc/schema/shared/shared_definitions.schema.json, pkgs/code_assets/test/data/build_input_macos.json, pkgs/code_assets/test/data/build_output_macos.json, pkgs/code_assets/test/schema/schema_test.dart, pkgs/data_assets/doc/schema/shared/shared_definitions.generated.schema.json, pkgs/data_assets/test/data/build_input.json, pkgs/data_assets/test/data/build_output.json, pkgs/data_assets/test/schema/schema_test.dart, pkgs/hooks/doc/schema/shared/shared_definitions.schema.json, pkgs/hooks/test/data/build_input.json, pkgs/hooks/test/data/build_output.json, pkgs/hooks/test/data/link_input.json, pkgs/hooks/test/schema/helpers.dart, pkgs/hooks/test/schema/schema_test.dart, pkgs/hooks/tool/generate_schemas.dart, pkgs/json_syntax_generator/lib/src/parser/schema_analyzer.dart, pkgs/native_assets_cli/lib/src/config.dart, pkgs/native_assets_cli/lib/src/hooks/syntax.g.dart
Bug: https://github.com/dart-lang/native/issues/1251
This PR contains the JSON spec for:
* https://github.com/dart-lang/native/pull/2164
For more details see that PR.
This PR adds the syntax for passing assets from build hooks to build hooks.
build output `assets_for_build`:
```json
{
"assets": [],
"assets_for_build": [
{
"encoding": {
"a_key": "some_value"
},
"some_key": "some_value",
"type": "some_asset_type"
}
],
"assets_for_linking": {},
}
```
build input `assets` per package name:
```json
{
"assets": {
"some_package": [
{
"some_key": "some_value",
"type": "some_asset_type"
}
]
},
"config": {},
}
```
Secondly, this PR adds a syntax for metadata assets (assets that cannot be bundled but just ferry information between different hooks).
```json
{
"encoding": {
"key": "foo",
"value": …
```
=> [native_assets_cli] Syntax for `assets_for_build` and `hooks/metadata`

.github/workflows/native.yaml, pkgs/code_assets/test/data/build_input_macos.json, pkgs/code_assets/test/data/link_input_macos.json, pkgs/data_assets/test/data/build_input.json, pkgs/data_assets/test/data/link_input.json, pkgs/hooks/doc/schema/shared/shared_definitions.schema.json, pkgs/hooks/test/data/build_input.json, pkgs/hooks/test/data/link_input.json, pkgs/hooks/test/schema/helpers.dart, pkgs/native_assets_builder/lib/src/build_runner/build_runner.dart, pkgs/native_assets_builder/test/build_runner/helpers.dart, pkgs/native_assets_builder/test/test_data/user_defines_test.dart, pkgs/native_assets_builder/test_data/manifest.yaml, pkgs/native_assets_builder/test_data/user_defines/hook/build.dart, pkgs/native_assets_cli/lib/src/config.dart, pkgs/native_assets_cli/lib/src/hooks/syntax.g.dart
Bug: https://github.com/dart-lang/native/issues/39
Note passing in the user-defines should be done by the Dart and Flutter SDK, they need to decide where to take the command-line arguments, and how to read from the `pubspec.yaml`.
The `NativeAssetsBuildRunner` provides a suggestion about where to put user-defines in the `pubspec.yaml`:
```yaml
hooks:
user_defines:
my_package:
user_define_key: user_define_value
user_define_key2:
foo: bar
some_other_package:
user_define_key3: user_define_value3
```
Moreover, it provides a helper function that can be reused in SDKs after the pubspec yaml is parsed.
(According to the discussion on the bug.)
* User-defines are name-spaced per package, we don't want new user-defines to invalidate the cache for other packages.
* User-defines can be provided for …
=> [native_assets_cli] Add `user_defines`

pkgs/native_assets_builder/test_data/manifest.yaml, pkgs/native_assets_builder/test_data/user_defines/bin/user_defines.dart, pkgs/native_assets_builder/test_data/user_defines/pubspec.yaml, pkgs/native_assets_builder/test_data/user_defines/test/user_defines_test.dart
Making the test project have a `bin/` and `test/` file so we can test the dartdev commands.
https://dart-review.googlesource.com/c/sdk/+/420700
(The hook exits with non-0 exit code if the build fails. The assets are not used in the bin and test scripts.)
=> [native_assets_builder] Test project for user-defines in dartdev

.github/workflows/jnigen.yaml, pkgs/jnigen/test/simple_package_test/runtime_test_registrant.dart
=> [jnigen] Add Android emulator to CI

pkgs/jni/lib/src/jobject.dart
Closes #1033. Added a warning to let users know about the possible false-positives of the `JObject.isA` method as specified in the issue.
=> [jni] Add type erasure warning for `isA` doc

pkgs/code_assets/doc/schema/shared/shared_definitions.generated.schema.json, pkgs/code_assets/test/data/build_output_macos.json, pkgs/code_assets/test/schema/schema_test.dart, pkgs/data_assets/doc/schema/shared/shared_definitions.generated.schema.json, pkgs/data_assets/test/data/build_output.json, pkgs/data_assets/test/schema/schema_test.dart, pkgs/hooks/doc/schema/hook/shared_definitions.schema.json, pkgs/hooks/doc/schema/sdk/shared_definitions.schema.json, pkgs/hooks/doc/schema/shared/shared_definitions.schema.json, pkgs/hooks/test/data/build_output.json, pkgs/hooks/test/schema/helpers.dart, pkgs/hooks/test/schema/schema_test.dart, pkgs/hooks/tool/generate_schemas.dart, pkgs/hooks/tool/generate_syntax.dart, pkgs/native_assets_cli/lib/src/config.dart, pkgs/native_assets_cli/lib/src/hooks/syntax.g.dart, pkgs/native_assets_cli/lib/src/validation.dart, pkgs/native_assets_cli/test/build_output_test.dart
Bug:
Cleanup of:
* https://github.com/dart-lang/native/issues/2037
=> [native_assets_cli] Cleanup JSON: `assetsForLinking`

pkgs/code_assets/doc/schema/shared/shared_definitions.schema.json, pkgs/code_assets/test/data/build_input_windows.json, pkgs/code_assets/test/schema/schema_test.dart, pkgs/native_assets_cli/lib/src/code_assets/c_compiler_config.dart, pkgs/native_assets_cli/lib/src/code_assets/syntax.g.dart, pkgs/native_assets_cli/test/code_assets/config_test.dart
Bug:
Cleanup of:
* https://github.com/dart-lang/native/issues/1606
=> [native_assets_cli] Cleanup JSON: `env_script` and `env_script_arguments`

pkgs/code_assets/test/data/build_input_macos.json, pkgs/code_assets/test/data/link_input_macos.json, pkgs/data_assets/test/data/build_input.json, pkgs/data_assets/test/data/link_input.json, pkgs/hooks/test/data/build_input.json, pkgs/hooks/test/data/link_input.json, pkgs/hooks/test/schema/helpers.dart, pkgs/native_assets_cli/lib/src/user_defines.dart
Bug:
Cleanup of:
* https://github.com/dart-lang/native/issues/2187
The old JSON encoding was only replaced one week ago, but it was only in the SDK for a week. So remove the fallback encoding now anyways. If anyone adopted it last week, they know where to update it.
This PR also adds tests for the JSON schema, that were missing:
* `user_defines` is optional, there might not be any
* `pub_workspace` is optional, there might be SDKs without a pubspec.
* `base_path` is required. If there are any user-defines, they might have relative paths in them.
* `defines` is required. If there are no defines, then the whole `pub_workspace` should be omitted. (Or simply add an empty map.)
=> [native_assets_cli] Cleanup JSON: old user defines

pkgs/native_assets_builder/lib/src/build_runner/build_planner.dart, pkgs/native_assets_builder/lib/src/build_runner/build_runner.dart, pkgs/native_assets_builder/test_data/use_all_api/hook/build.dart, pkgs/native_assets_cli/lib/src/model/hook.dart
* `$package/build.dart` has been migrated to `$package/hooks/build.dart` a long time ago, remove the fallback.
* `out_file` has been part of the protocol for a long time, remove the fallback.
=> [native_assets_builder] Cleanup old file fallbacks

pkgs/json_syntax_generator/lib/src/generator/normal_class_generator.dart, pkgs/native_assets_builder/test_data/complex_link/hook/build.dart, pkgs/native_assets_builder/test_data/complex_link_helper/hook/build.dart, pkgs/native_assets_builder/test_data/simple_link/hook/build.dart, pkgs/native_assets_cli/example/build/download_asset/hook/build.dart, pkgs/native_assets_cli/example/build/download_asset/pubspec.yaml, pkgs/native_assets_cli/example/link/package_with_assets/hook/build.dart, pkgs/native_assets_cli/lib/src/config.dart, pubspec.yaml
* We now have user-defines, so use them in the example for downloading assets.
* Remove todos that we decided we're not going to address.
=> [native_assets_cli] Cleanup TODOs

pkgs/json_syntax_generator/lib/src/generator/enum_class_generator.dart, pkgs/json_syntax_generator/lib/src/generator/helper_library.dart, pkgs/json_syntax_generator/lib/src/generator/normal_class_generator.dart, pkgs/json_syntax_generator/lib/src/generator/property_generator.dart, pkgs/json_syntax_generator/lib/src/model/class_info.dart, pkgs/json_syntax_generator/lib/src/model/dart_type.dart, pkgs/native_assets_cli/lib/src/code_assets/architecture.dart, pkgs/native_assets_cli/lib/src/code_assets/c_compiler_config.dart, pkgs/native_assets_cli/lib/src/code_assets/code_asset.dart, pkgs/native_assets_cli/lib/src/code_assets/config.dart, pkgs/native_assets_cli/lib/src/code_assets/link_mode.dart, pkgs/native_assets_cli/lib/src/code_assets/link_mode_preference.dart, pkgs/native_assets_cli/lib/src/code_assets/os.dart, pkgs/native_assets_cli/lib/src/code_assets/syntax.g.dart, pkgs/native_assets_cli/lib/src/code_assets/validation.dart, pkgs/native_assets_cli/lib/src/config.dart, pkgs/native_assets_cli/lib/src/data_assets/data_asset.dart, pkgs/native_assets_cli/lib/src/data_assets/syntax.g.dart, pkgs/native_assets_cli/lib/src/data_assets/validation.dart, pkgs/native_assets_cli/lib/src/encoded_asset.dart, pkgs/native_assets_cli/lib/src/hooks/syntax.g.dart, pkgs/native_assets_cli/lib/src/metadata.dart, pkgs/native_assets_cli/lib/src/user_defines.dart, pkgs/native_assets_cli/lib/src/validation.dart
Having classes with the same name makes autocomplete in the IDE annoying.
Instead of having `syntax.$name` with an import `as syntax`, use `${name}Syntax` as class name for the syntax classes.
Note, the extensions converting between semantic and syntax classes were called `${name}Syntax`. These have been renamed to `${name}SyntaxExtension`.
=> [native_assets_cli] Rename syntax classes to `${name}Syntax`

pkgs/native_assets_cli/lib/src/code_assets/c_compiler_config.dart, pkgs/native_assets_cli/lib/src/code_assets/code_asset.dart, pkgs/native_assets_cli/lib/src/code_assets/config.dart, pkgs/native_assets_cli/lib/src/code_assets/ios_sdk.dart, pkgs/native_assets_cli/lib/src/code_assets/link_mode.dart, pkgs/native_assets_cli/lib/src/code_assets/link_mode_preference.dart, pkgs/native_assets_cli/lib/src/code_assets/os.dart, pkgs/native_assets_cli/lib/src/data_assets/config.dart, pkgs/native_assets_cli/lib/src/data_assets/data_asset.dart
This PR tries the curate the classes which are in the public API of what will be `package:code_assets` and `package:data_assets`.
The Dart docs can be inspected by `pkgs/native_assets_cli$ dart doc .`.
TODOs:
* This PR does not yet curate extension types, extensions, and top level functions.
Context:
* Work before splitting up the package: https://github.com/dart-lang/native/issues/999
=> [native_assets_cli] Curate public classes - part 2

pkgs/native_assets_builder/lib/src/build_runner/build_runner.dart, pkgs/native_assets_cli/lib/native_assets_cli.dart, pkgs/native_assets_cli/lib/src/api/build.dart, pkgs/native_assets_cli/lib/src/api/link.dart, pkgs/native_assets_cli/lib/src/code_assets/testing.dart, pkgs/native_assets_cli/lib/src/extension.dart, pkgs/native_assets_cli/lib/src/test.dart, pkgs/native_assets_cli/lib/src/validation.dart, pkgs/native_assets_cli/test/validation_test.dart
This PR tries the curate the toplevel functions which are in the public API of what will be `package:hooks`,   `package:code_assets` and `package:data_assets`.
The validate functions for the base protocol are moved into a `ProtocolBase` class. (These need to be public because `package:native_assets_builder` uses them. And these need to be in `package:native_assets_cli` because the `test` methods use them.)
The Dart docs can be inspected by `pkgs/native_assets_cli$ dart doc .`.
TODOs:
* This PR does not yet curate extension types, and extensions.
Context:
* Work before splitting up the package: https://github.com/dart-lang/native/issues/999
=> [native_assets_cli] Curate public toplevel functions

pkgs/jni/lib/src/jobject.dart, pkgs/jni/test/jobject_test.dart
The `use` method makes it really easy to use jni and not worry about memory management (even if the nesting get's ugly)
However this PR allows you to use `use` on nullable `JObject?`s too.
This is a very small pr which would allow you to do this.
```
someFunc(JObject? obj){
obj.use(...);
}
```
The extension was only on `JObject` previosly.
---
<details>
- Most changes should add an entry to the …
=> [jnigen] Support `use` arenas on nullable JObjects

pkgs/ffigen/CHANGELOG.md, pkgs/ffigen/lib/src/header_parser/type_extractor/extractor.dart, pkgs/ffigen/pubspec.yaml, pkgs/ffigen/test/native_objc_test/property_config.yaml, pkgs/ffigen/test/native_objc_test/property_test.dart, pkgs/ffigen/test/native_objc_test/property_test.h, pkgs/ffigen/test/native_objc_test/property_test.m, pkgs/objective_c/CHANGELOG.md, pkgs/objective_c/lib/src/objective_c_bindings_generated.dart, pkgs/objective_c/pubspec.yaml
There's a rareish bug where a specific interface type can be codegenned as a generic `ObjCObjectBase`. It can happen in methods or properties, in arguments or returns.
I'm not 100% sure what causes it, but it seems to happen when the interface has type params, and is forward declared. Eg, I was able to repro it in the test by writing a method that returns an `NSArray<NSString*>*`, and forward declaring `NSArray` and `NSString` instead of `#import`ing their headers.
The bug is that in the AST these types show up as a `CXType_ObjCObject` instead of a `CXType_ObjCInterface`. Their structure is exactly the same as any other interface, but the different kind enum value means that they fall through our parsing switch and default to the generic object type. So the fix is just to add this enum …
=> [ffigen] Fix #1268

.github/workflows/package_download_asset.yaml
`package:native_assets_cli` was renamed to `package:hook`. So the example was moved.
=> [infra] Fix package_download_asset workflow

pkgs/code_assets/pubspec.yaml, pkgs/data_assets/pubspec.yaml, pkgs/hooks/pubspec.yaml, pkgs/hooks_runner/CHANGELOG.md, pkgs/hooks_runner/lib/src/build_runner/build_planner.dart, pkgs/hooks_runner/pubspec.yaml, pkgs/json_syntax_generator/pubspec.yaml, pkgs/native_toolchain_c/pubspec.yaml
Both Dart and Flutter using this are on a version of pub that emits the `package_graph.json`.
=> [hooks_runner] Remove `package_graph.json` fallback

pkgs/jnigen/CHANGELOG.md, pkgs/jnigen/lib/src/bindings/linker.dart, pkgs/jnigen/test/simple_package_test/bindings/simple_package.dart, pkgs/jnigen/test/simple_package_test/generate.dart, pkgs/jnigen/test/simple_package_test/java/com/github/dart_lang/jnigen/regressions/R2250.java, pkgs/jnigen/test/simple_package_test/runtime_test_registrant.dart
Closes #2250. Classes that inherited a generic without specifying all type parameters were not generated. Filling the ones not specified with `JObject?`.
=> [jnigen] Fix generic subinterfaces not specifying full type params

pkgs/hooks/test/helpers.dart, pkgs/hooks/test/schema/helpers.dart, pkgs/hooks_runner/test/helpers.dart, pkgs/native_toolchain_c/test/helpers.dart
This enables running tests with `dart test` from the workspace root.
```
$ dart test pkgs/code_assets/test/ pkgs/data_assets/test/ pkgs/hooks/test/ pkgs/hooks_runner/test/ pkgs/native_toolchain_c/test/
```
This is significantly faster than running multiple `dart test` commands in each package in sequence.
(I'll attempt to make the CI use this afterwards.)
=> [infra] Enable running tests from root

pkgs/hooks_runner/test_data/native_add_version_skew/analysis_options.yaml, pkgs/hooks_runner/test_data/native_add_version_skew/pubspec.yaml, pkgs/hooks_runner/test_data/native_add_version_skew_2/analysis_options.yaml, pkgs/hooks_runner/test_data/native_add_version_skew_2/pubspec.yaml
If no analysis options exist in a project the ancestor directories are checked.
However, then the packages referred to in the analysis options must actually be dependencies in the pubspec.
This makes the two projects that are _not_ part of the workspace have valid `analysis_options.yaml`.
These fixes make the following commands succeed:
```
$ dart format --output=none --set-exit-if-changed pkgs/code_assets pkgs/data_assets pkgs/hooks pkgs/hooks_runner 
$ dart analyze --fatal-infos pkgs/code_assets pkgs/data_assets pkgs/hooks pkgs/hooks_runner pkgs/json_syntax_generator pkgs/native_toolchain_c pkgs/repo_lint_rules
```
=> [hooks_runner] Fix analysis in test projects

.github/workflows/native.yaml, pkgs/code_assets/pubspec.yaml, pkgs/data_assets/pubspec.yaml, pkgs/hooks/pubspec.yaml, pkgs/hooks/tool/generate_schemas.dart, pkgs/hooks/tool/generate_syntax.dart, pkgs/hooks/tool/normalize.dart, pkgs/hooks_runner/pubspec.yaml, pkgs/hooks_runner/test/helpers.dart, pkgs/json_syntax_generator/pubspec.yaml, pkgs/native_toolchain_c/pubspec.yaml, tool/ci.dart
Move a bunch of CI checks into `tool/ci.dart` to enable running them locally.
Currently missing to run locally:
* Health checks: `dart pub global run firehose:health` cannot run locally at the moment due to a missing `GITHUB_TOKEN`.
* Coverage: We need to be able to get coverage and upload coverage for multiple packages at the same time (https://github.com/dart-lang/tools/issues/2083).
Other fixes:
* `dart analyze` with custom lints currently requires to use path dependencies in pub workspaces (https://github.com/invertase/dart_custom_lint/issues/329).
* Ignore line endings when checking diffs for code generators.
=> [infra] Enable running CI checks locally

pkgs/hooks_runner/lib/src/build_runner/build_planner.dart, pkgs/hooks_runner/test/build_runner/build_planner_test.dart
> If there are no hooks at all in the package graph, do [...] flutter commands not regress.
Bug: https://github.com/dart-lang/native/issues/2236
When there are no hooks, all packages in the dependencies must be checked for `hook/build.dart`.
This check for Flutter's `hello_world` takes 1 ms in isolation:
`INFO: 2025-05-14 08:30:08.854304: _runPackagesWithHook took 850 us. Checked 8 packages.`
Inside Flutter this check (in `dart_build`) happens concurrently with other code, so it shows up as taking longer:
```
[        ] [   +1 ms] gen_dart_plugin_registrant: Starting due to {InvalidatedReasonKind.inputChanged: The following inputs have updated contents: /Users/dacoharkes/flt/flutter/examples/hello_world/.dart_tool/package_config_subset} <-- does sync IO
[        ] [   +2 ms] dart_build: …
```
=> [hooks_runner] No hooks performance trace

pkgs/ffigen/lib/src/code_generator/objc_built_in_functions.dart, pkgs/objective_c/CHANGELOG.md, pkgs/objective_c/ffigen_objc.yaml, pkgs/objective_c/lib/objective_c.dart, pkgs/objective_c/lib/src/cf_string.dart, pkgs/objective_c/lib/src/objective_c_bindings_generated.dart, pkgs/objective_c/test/cf_string_test.dart
Toll-free bridging means we can directly cast `CFString*` to `NSString*`.
Fixes #1547
Fixes #1548
=> [objective_c] CFString conversions

tool/ci.dart
This adds a way to run coverage for multiple packages to the `tools/ci.dart` script. (Based on https://github.com/dart-lang/tools/issues/2083#issuecomment-2892543659.)
Not used yet in the actual coverage collection on the CI, as that will require massaging the coveralls setup.
Using this command means that the local coverage now includes coverage from integration tests from dependent packages. (E.g. the tests in `package:hooks_runner` now add coverage for `package:hooks` for example.)
=> [infra] Support collecting coverage for multiple packages at once

pkgs/jni/CHANGELOG.md, pkgs/jni/lib/src/util/jlist.dart, pkgs/jni/lib/src/util/jmap.dart, pkgs/jni/lib/src/util/jset.dart, pkgs/jni/pubspec.yaml, pkgs/jni/test/jlist_test.dart, pkgs/jni/test/jmap_test.dart, pkgs/jni/test/jset_test.dart, pkgs/jnigen/CHANGELOG.md, pkgs/jnigen/pubspec.yaml
After adding nullablities to collections, I didn't add tests to test collections with nullable types. Adding these tests uncovered some bugs that are now fixed.
Also `JList.lastIndexOf` was not tested at all, testing that uncovered another bug which is also fixed now.
@liamappelbe Overall it's probably best to have a unified test for all of our collection types to avoid duplicate work. I'll open an issue about that.
=> [jni] Fix nullable JCollections

pkgs/hooks_runner/CHANGELOG.md, pkgs/hooks_runner/lib/src/build_runner/build_planner.dart, pkgs/hooks_runner/lib/src/build_runner/build_runner.dart, pkgs/hooks_runner/lib/src/build_runner/tracing_file_system.dart, pkgs/hooks_runner/lib/src/dependencies_hash_file/dependencies_hash_file.dart, pkgs/hooks_runner/lib/src/utils/run_process.dart, pkgs/hooks_runner/pubspec.yaml
This PR adds timeline events to the `hooks_runner` package:
* All `FileSystem` calls. (With a `TracingFileSystem`.)
* All `Process` runs.
* The main methods.
This enables looking at the performance:
(First build compiles the hook and runs the hook. Second build doesn't compile the hook and doesn't run the hook. Side note: Compiling Dart takes longer than running the hook (compiling C)!)
Some quirks:
* The current approach only works for non-concurrent events. (The stdout and stderr file logging is concurrent to the process calls and therefore has to be excluded.) If we ever start doing things concurrently, we'll need to refactor this.
* There are a lot of possibilities to improve things when we have more than one hook in the system. Optimizing this only makes sense once we have more real …
=> [hooks_runner] Add `TimelineEvents`

pkgs/native_toolchain_c/CHANGELOG.md, pkgs/native_toolchain_c/lib/src/cbuilder/clinker.dart, pkgs/native_toolchain_c/lib/src/cbuilder/linker_options.dart, pkgs/native_toolchain_c/lib/src/cbuilder/run_cbuilder.dart, pkgs/native_toolchain_c/pubspec.yaml, pkgs/native_toolchain_c/test/cbuilder/cbuilder_cross_android_test.dart, pkgs/native_toolchain_c/test/clinker/build_testfiles.dart, pkgs/native_toolchain_c/test/clinker/objects_cross_android_test.dart, pkgs/native_toolchain_c/test/clinker/objects_cross_test.dart, pkgs/native_toolchain_c/test/clinker/objects_helper.dart, pkgs/native_toolchain_c/test/clinker/objects_test.dart, pkgs/native_toolchain_c/test/clinker/throws_test.dart, pkgs/native_toolchain_c/test/clinker/treeshake_cross_android_test.dart, pkgs/native_toolchain_c/test/clinker/treeshake_cross_test.dart, pkgs/native_toolchain_c/test/clinker/treeshake_helper.dart, pkgs/native_toolchain_c/test/clinker/treeshake_test.dart, pkgs/native_toolchain_c/test/helpers.dart
Towards https://github.com/dart-lang/native/issues/1376
This enables linking for MacOS targets on MacOS hosts.
=> [native_toolchain_c] Add linking for macOS

pkgs/native_toolchain_c/CHANGELOG.md, pkgs/native_toolchain_c/lib/src/cbuilder/clinker.dart, pkgs/native_toolchain_c/lib/src/cbuilder/linker_options.dart, pkgs/native_toolchain_c/pubspec.yaml, pkgs/native_toolchain_c/test/cbuilder/cbuilder_cross_ios_test.dart, pkgs/native_toolchain_c/test/clinker/build_testfiles.dart, pkgs/native_toolchain_c/test/clinker/objects_cross_android_test.dart, pkgs/native_toolchain_c/test/clinker/objects_cross_ios_test.dart, pkgs/native_toolchain_c/test/clinker/objects_helper.dart, pkgs/native_toolchain_c/test/clinker/throws_test.dart, pkgs/native_toolchain_c/test/clinker/treeshake_cross_android_test.dart, pkgs/native_toolchain_c/test/clinker/treeshake_cross_ios_test.dart, pkgs/native_toolchain_c/test/clinker/treeshake_cross_test.dart, pkgs/native_toolchain_c/test/clinker/treeshake_helper.dart, pkgs/native_toolchain_c/test/clinker/treeshake_test.dart, pkgs/native_toolchain_c/test/helpers.dart
Towards https://github.com/dart-lang/native/issues/1376
We were basically able re reuse all the macOS work from https://github.com/dart-lang/native/pull/2360 for iOS and just had to add iOS-specific Tests.
This PR also fixes an issue with the treeshaking tests, which were accidentally overwriting size results from other test cases. An `expect` has been added to guard against this issue in the future.
Hint for reviewers: `treeshake_helper.dart` is easier to review with github's `Hide whitespace` option turned on.
---
<details>
- …
=> [native_toolchain_c] Add linking for iOS

.github/pr-title-checker-config.json
It's a valid (new) package, it should be usable as a prefix in a PR title.
---
<details>
- Changes to packages require [corresponding tests](https://github.com/dart-lang/.github/blob/main/CONTRIBUTING …
=> [infra] add native_test_helpers to be a valid PR title prefix

pkgs/ffigen/lib/src/code_generator/library.dart, pkgs/ffigen/lib/src/code_generator/utils.dart
When formatting the generated Dart code using `dart format`, we can't assume that `Platform.resolvedExecutable` will be the dart executable. For flutter tests it's `flutter_tester`. In fact there's already a util in ffigen that solves this problem.
Fixes #2388
=> [ffigen] Fix flutter CI

pkgs/code_assets/analysis_options.yaml, pkgs/data_assets/analysis_options.yaml, pkgs/ffi/analysis_options.yaml, pkgs/ffigen/analysis_options.yaml, pkgs/hooks/analysis_options.yaml, pkgs/hooks/example/link/app_with_asset_treeshaking/analysis_options.yaml, pkgs/hooks_runner/analysis_options.yaml, pkgs/hooks_runner/test_data/native_add_version_skew/analysis_options.yaml, pkgs/hooks_runner/test_data/native_add_version_skew_2/analysis_options.yaml, pkgs/json_syntax_generator/analysis_options.yaml, pkgs/native_test_helpers/analysis_options.yaml, pkgs/native_toolchain_c/analysis_options.yaml, pkgs/objective_c/analysis_options.yaml, pkgs/objective_c/example/analysis_options.yaml, pkgs/repo_lint_rules/analysis_options.yaml, pkgs/swift2objc/analysis_options.yaml, pkgs/swiftgen/analysis_options.yaml
This removes the following from the analysis options files:
- boilerplate comments
- options that are already enabled by imported analysis options files
- the ignore for TODOs since the analyzer has been fixed to no longer complain about these.
Clean-up powered by Gemini CLI.
This PR cleans up all packages except for jni, jnigen and native_doc_dartifier. Those packages are dealt with in https://github.com/dart-lang/native/pull/2411 and https://github.com/dart-lang/native/pull/2412.
=> [infra] clean up analysis options files

pkgs/native_doc_dartifier/analysis_options.yaml
Follow-up to https://github.com/dart-lang/native/pull/2407
This removes the following from the analysis options files:
- boilerplate comments
- options that are already enabled by imported analysis options files
- the ignore for TODOs since the analyzer has been fixed to no longer complain about these.
Clean-up powered by Gemini CLI.
=> [native_doc_dartifier] Clean up analysis option file

pkgs/ffigen/CHANGELOG.md, pkgs/ffigen/pubspec.yaml, pkgs/objective_c/CHANGELOG.md, pkgs/objective_c/pubspec.yaml
#2409 is a breaking change, and I don't plan to release v20 for a while, so publish v19.1 first.
=> [ffigen] Prepare to publish v19.1.0

pkgs/jni/analysis_options.yaml, pkgs/jni/example/analysis_options.yaml, pkgs/jnigen/analysis_options.yaml, pkgs/jnigen/android_test_runner/analysis_options.yaml, pkgs/jnigen/example/in_app_java/analysis_options.yaml, pkgs/jnigen/example/kotlin_plugin/analysis_options.yaml, pkgs/jnigen/example/kotlin_plugin/example/analysis_options.yaml, pkgs/jnigen/example/notification_plugin/example/analysis_options.yaml, pkgs/jnigen/example/pdfbox_plugin/analysis_options.yaml, pkgs/jnigen/example/pdfbox_plugin/dart_example/analysis_options.yaml, pkgs/jnigen/example/pdfbox_plugin/example/analysis_options.yaml, pkgs/jnigen/example/pdfbox_plugin/lib/pdfbox_plugin.dart
Follow-up to https://github.com/dart-lang/native/pull/2407
This removes the following from the analysis options files:
- boilerplate comments
- options that are already enabled by imported analysis options files
- the ignore for TODOs since the analyzer has been fixed to no longer complain about these.
Clean-up powered by Gemini CLI.
=> [jnigen] clean up analysis option files

pkgs/hooks/tool/generate_syntax.dart, pkgs/json_syntax_generator/lib/src/model/property_info.dart, pkgs/json_syntax_generator/lib/src/parser/schema_analyzer.dart, pkgs/pub_formats/lib/src/pubspec_syntax.g.dart, pkgs/pub_formats/tool/generate.dart
For https://github.com/dart-lang/sdk/issues/60889, we need to be able to validate just the sections of the pubspec we want to use (the `executables` section and `hooks` section).
If any errors exist in other sections, the pieces of `pub` or `dartdev` using those should error, not any hooks related implementation.
The `hooks` section we could validate by doing `syntax.hooks.validate()` but `syntax.executables` returns simply a `Map` because the that part of the syntax has no structure with known fields, it's simply a map. So, this PR exposes a `syntax.validateExecutables()` method.
=> [json_syntax_generator] Add support for public validator methods

pkgs/hooks_runner/test_data/dart_app/pubspec.yaml
If a package can be `dart install`ed or `dart pub global activate`d, it needs to provide more guarantees than if it can only be `dart run`ned. (For example, the package cannot have access to its on source code.) Therefore, the `executables` section in the `pubspec.yaml` signals that a package can be `dart install`ed.
This PR makes our example app `dart install`able. It is standalone and provides those guarantees.
=> [hooks] Update example to be `dart install`able

pkgs/hooks/tool/generate_syntax.dart, pkgs/json_syntax_generator/lib/src/generator/normal_class_generator.dart, pkgs/json_syntax_generator/lib/src/generator/syntax_generator.dart, pkgs/pub_formats/lib/src/package_graph_syntax.g.dart, pkgs/pub_formats/lib/src/pubspec_lock_syntax.g.dart, pkgs/pub_formats/lib/src/pubspec_syntax.g.dart
For the generated syntax inside `package:hooks`, `code_assets`, and `data_assets` all nullable parameters are `required`. This is to help us ensure that we don't forget a param in the semantic API. (The generated syntax is wrapped with an API handcrafted to be nice for our users.)
However, in `package:pub_formats` we don't have a semantic API wrapping the syntax, we directly use the syntax classes in `dartdev` and friends. In such case it's unwanted to have to provide every param. (For example when constructing a `pubspec.yaml` we want to omit all the optional sections.)
So, we add a param to the generator to control this.
=> [pub_formats] Make nullable params optional

pkgs/swift2objc/lib/src/ast/_core/interfaces/compound_declaration.dart, pkgs/swift2objc/lib/src/ast/_core/interfaces/enum_declaration.dart, pkgs/swift2objc/lib/src/ast/_core/interfaces/nestable_declaration.dart, pkgs/swift2objc/lib/src/ast/_core/shared/referred_type.dart, pkgs/swift2objc/lib/src/ast/declarations/compounds/class_declaration.dart, pkgs/swift2objc/lib/src/ast/declarations/compounds/protocol_declaration.dart, pkgs/swift2objc/lib/src/ast/declarations/compounds/struct_declaration.dart, pkgs/swift2objc/lib/src/ast/declarations/enums/associated_value_enum_declaration.dart, pkgs/swift2objc/lib/src/ast/declarations/enums/normal_enum_declaration.dart, pkgs/swift2objc/lib/src/ast/declarations/enums/raw_value_enum_declaration.dart, pkgs/swift2objc/lib/src/parser/_core/utils.dart, pkgs/swift2objc/lib/src/parser/parsers/declaration_parsers/parse_compound_declaration.dart, pkgs/swift2objc/lib/src/transformer/transform.dart, pkgs/swift2objc/lib/src/transformer/transformers/transform_compound.dart
Split `NestableDeclaration` into `InnerNestableDeclaration` and `OuterNestableDeclaration`, since there are declarations that can be nested inside other declarations, but can't contain other declarations. Eg typealiases.
Part of #1775
=> [swift2objc] Split `NestableDeclaration`

pkgs/swift2objc/lib/src/ast/declarations/built_in/built_in_declaration.dart, pkgs/swift2objc/test/integration/bridging_input.swift, pkgs/swift2objc/test/integration/bridging_output.swift
There are a lot of "toll-free bridging" types in Swift. These are types that are special cased in the swift compiler to be `@objc` compatible, even though the declarations don't have `@objc` annotations. We also need to special case these types in the same way. The easiest way is to make them `BuiltInDeclaration`s.
Unfortunately, there's no canonical list of these bridged types that I can find. The closest thing is https://developer.apple.com/documentation/swift/working-with-foundation-types, but it's incomplete.
Note that the integration test tries to compile the generated wrapper code, which effectively tests that these types do bridge as expected. If any of these types were not `@objc` compatible, the compiler would complain and the test would fail.
=> [swift2objc] Add toll free bridged types

pkgs/hooks_runner/pubspec.yaml, pkgs/hooks_runner/test_data/manifest_generator.dart, tool/ci.dart
Addressing the fact we're not checking this automaticaly:
* https://github.com/dart-lang/native/pull/2417#discussion_r2235135012
=> [hooks_runner] Add the manifest generator to the ci checks

pkgs/hooks/example/build/native_dynamic_linking/test/add_test.dart, tool/ci.dart
Only run the tests once while running coverage.
On my local machine:
* `dart test` without coverage: 40 seconds
* `dart test` with coverage: 1 minute
* formatting the coverage: fast
So, this refactoring takes 40 seconds off `--all`. And `--none --test` is still 40 seconds.
=> [infra] CI script: don't run tests twice

pkgs/swift2objc/lib/src/transformer/_core/dependencies.dart, pkgs/swift2objc/lib/src/transformer/transform.dart, pkgs/swift2objc/test/unit/filter_test.dart, pkgs/swift2objc/test/unit/filter_test_input.swift, pkgs/swift2objc/test/unit/filter_test_output_b.swift, pkgs/swift2objc/test/unit/filter_test_output_e.swift, pkgs/swift2objc/test/unit/filter_test_output_f.swift, pkgs/swift2objc/test/unit/filter_test_output_g.swift, pkgs/swift2objc/test/unit/filter_test_output_h.swift
Found a bunch of edge cases where the stubbing doesn't work correctly, to do with nested types. Fixed them and added more tests. Also added a `--regen` option to the filtering test, to make development easier.
Fixes:
- Apply the include/exclude filter to nested types in `FindIncludesVisitation`, even if the parent type has been filtered out. If a child is included/stubbed but the parent is included, the parent should be stubbed.
- Don't visit children in `ListDeclsVisitation`. Doing so was causing nested types to be code genned even when the parent type was stubbed.
- Keep track of all the bindings that are included or stubbed. During the later transformation stages, if we try to transform a declaration that isn't included or stubbed, omit it (return null).
=> [swift2objc] Fix stubbing edge cases for nested types

pkgs/jni/src/include/analyze_snapshot_api.h, pkgs/jni/src/include/bin/dart_io_api.h, pkgs/jni/src/include/bin/native_assets_api.h, pkgs/jni/src/include/dart_api.h, pkgs/jni/src/include/dart_api_dl.c, pkgs/jni/src/include/dart_api_dl.h, pkgs/jni/src/include/dart_embedder_api.h, pkgs/jni/src/include/dart_native_api.h, pkgs/jni/src/include/dart_tools_api.h, pkgs/jni/src/include/dart_version.h, pkgs/objective_c/src/include/dart_api.h, pkgs/objective_c/src/include/dart_tools_api.h
The warnings were fixed in the SDK in https://github.com/dart-lang/sdk/commit/f3bbeb61f7da10ad538953b409c16b12ead9a086. There's no need to wait for these changes to be released to stable. This PR just copies the SDK's runtime/include directory into ffigen and jnigen.
Fixes https://github.com/dart-lang/native/issues/2482
=> [ffigen][jnigen] Update Dart API to resolve compiler warnings

pkgs/code_assets/README.md, pkgs/data_assets/README.md, pkgs/hooks/CONTRIBUTING.md, pkgs/hooks/tool/update_snippets.dart
Follow up of https://github.com/dart-lang/native/pull/2519 to add markdown support
Simplifies the regexes somewhat by splitting them up.
Funny side effect, we can't put incorrect examples in CONTRIBUTING.md 😆
=> [hooks] [code_assets] [data_assets] Fix markdown code snippets

tool/ci.dart
I find myself wanting to run `dart tools/ci.dart --coverage` and not wanting to write `dart tools/ci.dart --none --coverage`. Also, it's kinda hard to remember what tasks are run by default or not. So it's probably better to not run anything by default.
=> [infra] Default CI scrip tasks all to false

pkgs/code_assets/CHANGELOG.md, pkgs/code_assets/pubspec.yaml, pkgs/data_assets/CHANGELOG.md, pkgs/data_assets/pubspec.yaml, pkgs/hooks/CHANGELOG.md, pkgs/hooks/pubspec.yaml, pkgs/hooks_runner/CHANGELOG.md, pkgs/hooks_runner/pubspec.yaml
We have landed readme files and examples, publish versions so they become visible on pub.
The breaking change check is reporting `InvalidTypes` (https://github.com/dart-lang/native/issues/2361). I've checked manually, there are no breaking changes.
=> [code_assets] [hooks] [hooks_runner] [data_assets] Publish

pkgs/code_assets/test/example/pub_publish_size_test.dart, pkgs/hooks/test/example/pub_publish_size_test.dart
These tests were wrong assuming `dart` to be on `PATH`.
This doesn't fail on GitHub, but it does on the Dart CI: [https://logs.chromium.org/logs/dart/buildbucket/cr-buildbucket/8705372601376369393/+/u/test_results/new_test_failures__logs_](https://logs.chromium.org/logs/dart/buildbucket/cr-buildbucket/8705372601376369393/+/u/test_results/new_test_failures__logs_)
(No changelog or version bump, only needed for Dart CI.)
=> [code_assets] [hooks] Fix process run in test

pkgs/ffigen/lib/src/config_provider/config.dart, pkgs/ffigen/lib/src/config_provider/config_impl.dart, pkgs/ffigen/lib/src/config_provider/yaml_config.dart
It's only used by the `YamlConfig`. Fixes https://github.com/dart-lang/native/issues/2558
=> [ffigen] Remove `PackageConfig` from `FfiGen` config

pkgs/swift2objc/lib/src/parser/parsers/declaration_parsers/parse_built_in_declaration.dart, pkgs/swift2objc/lib/src/parser/parsers/parse_declarations.dart
Restrict `tryParseBuiltInDeclaration` to symbols that come from the built in `Foundation` module. There are symbols in other modules that have IDs starting with `c:objc(cs)`, so if we treat them all as built in, then users can't actually generate bindings for them.
=> [swift2objc] Built in declarations should only come from the built in module

pkgs/swift2objc/lib/src/ast/visitor.dart, pkgs/swift2objc/lib/src/config.dart, pkgs/swift2objc/lib/src/context.dart, pkgs/swift2objc/lib/src/generate_wrapper.dart, pkgs/swift2objc/lib/src/parser/_core/utils.dart, pkgs/swift2objc/lib/src/parser/parsers/declaration_parsers/parse_compound_declaration.dart, pkgs/swift2objc/lib/src/parser/parsers/declaration_parsers/parse_function_declaration.dart, pkgs/swift2objc/lib/src/parser/parsers/declaration_parsers/parse_initializer_declaration.dart, pkgs/swift2objc/lib/src/parser/parsers/declaration_parsers/parse_typealias_declaration.dart, pkgs/swift2objc/lib/src/parser/parsers/declaration_parsers/parse_variable_declaration.dart, pkgs/swift2objc/lib/src/parser/parsers/parse_declarations.dart, pkgs/swift2objc/lib/src/parser/parsers/parse_type.dart, pkgs/swift2objc/lib/src/transformer/transform.dart, pkgs/swift2objc/lib/swift2objc.dart, pkgs/swift2objc/test/integration/integration_test.dart, pkgs/swift2objc/test/unit/filter_test.dart, pkgs/swift2objc/test/unit/parse_function_info_test.dart, pkgs/swift2objc/test/unit/parse_type_test.dart
- Rename `Config` to `Swift2ObjCGenerator`.
- Make `generateWrapper` an extension method on `Swift2ObjCGenerator` and rename it `generate`.
- Take a `Logger` as input in `generate`.
- Pass the logger throughout the API in a `Context` object.
Fixes https://github.com/dart-lang/native/issues/1143
=> [swift2objc] Cleanup API for MVP

pkgs/ffigen/CHANGELOG.md, pkgs/ffigen/pubspec.yaml, pkgs/objective_c/CHANGELOG.md, pkgs/objective_c/pubspec.yaml
Let's publish a dev release so that the samples of `code_assets` can import that, but we can still iterate on the Dart API before we make a stable release.
=> [ffigen] [objective_c] Publish v20 and v9 dev releases

pkgs/native_doc_dartifier/lib/src/code_processor.dart, pkgs/native_doc_dartifier/lib/src/dartify_code.dart, pkgs/native_doc_dartifier/lib/src/prompts.dart
CI output: marshelino-maged/native#17
closes: #2490
closes: #2442
- Return the Dart code with the **fewest** analyzer errors from the loop  
- Updated fix prompt with clearer instructions.
- Switched to the Single-Prompt **Chain-of-Thought** Approach: model first **plans (think)**, then **applies the fix** — which is equivalent to making the LLM think in one prompt and fix in another ... it is like the Teacher Learner Model.
---
CC @HosseinYousefi
=> [native_doc_dartifier] Improve Fixing Dart Code

pkgs/ffigen/lib/src/config_provider/config.dart, pkgs/swiftgen/CHANGELOG.md, pkgs/swiftgen/lib/src/generator.dart, pkgs/swiftgen/pubspec.yaml
At the moment we ignore the user's `SwiftGenerator.ffigen.objectiveC.(interfaces|protocols).module` and just always assume the classes should be loaded from `SwiftGenerator.output.module`. Instead we should use their function if they set one.
Related to https://github.com/dart-lang/native/issues/2629. Tarrin wants to generate bindings for some Foundation classes that are missing from package:objective_c. He can generate those bindings, but at the moment it's trying to load them from the swift2objc output module, rather than the Foundation module.
=> [swiftgen] Allow user to use custom module function

pkgs/hooks_runner/CHANGELOG.md, pkgs/hooks_runner/lib/src/build_runner/build_runner.dart, pkgs/hooks_runner/pubspec.yaml, pkgs/hooks_runner/test/build_runner/build_runner_caching_test.dart
Allows environment variables starting with `NIX_` to pass through in `hooks_runner`. This fixes failing builds when using Nix-installed LLVM.
Fixes #2623
=> [hooks_runner] Pass `NIX_` environment variables through in hooks_runner

.gemini/settings.json
I am reluctant to commit any opinionated rule sets for AI to the repo, as I have no idea what's good or not. However, enabling the MCP server seems good always.
=> [infra] Enable the Dart MCP server by default in Gemini CLI

pkgs/native_toolchain_c/CHANGELOG.md, pkgs/native_toolchain_c/lib/src/cbuilder/compiler_resolver.dart, pkgs/native_toolchain_c/lib/src/native_toolchain/clang.dart
This change:
1. Also looks for `ld` and `ar` in the same directory as `clang`, since `llvm-ar` and `ld.lld` are not always the binary names in certain toolchain installations.
2. Adds tool fallback support in case the desired tool is not found (currently just `clang` is used as a fallback in case `appleClang` cannot be resolved on macOS).
Both of these changes are needed to support running in a Nix-like environment (on both Linux + macOS).
Fixes #2647
CC @dcharkes 
---
<details>
- Contributions to our repos should follow the [Dart …
=> [native_toolchain_c] Broaden compiler tool discovery
