pkgs/c_compiler/LICENSE
pkgs/native_assets_cli/LICENSE

add LICENSE files

---

pkgs/c_compiler/test/cbuilder/cbuilder_cross_windows_host_test.dart
pkgs/c_compiler/test/cbuilder/cbuilder_test.dart
pkgs/c_compiler/test/cbuilder/compiler_resolver_test.dart

Closes: https://github.com/dart-lang/native/issues/21

[c_compiler][Windows] Increase timeouts

---

pkgs/c_compiler/test/cbuilder/cbuilder_build_failure_test.dart
pkgs/c_compiler/test/cbuilder/cbuilder_cross_ios_test.dart
pkgs/c_compiler/test/cbuilder/cbuilder_cross_macos_host_test.dart
pkgs/c_compiler/test/cbuilder/cbuilder_cross_windows_host_test.dart
pkgs/c_compiler/test/cbuilder/cbuilder_test.dart
pkgs/c_compiler/test/cbuilder/compiler_resolver_test.dart
pkgs/c_compiler/test/native_toolchain/apple_clang_test.dart
pkgs/c_compiler/test/native_toolchain/xcode_test.dart
pkgs/native_assets_cli/test/example/native_add_test.dart

Test was timing out:
* https://github.com/dart-lang/native/actions/runs/4904280950/jobs/8757208574#step:10:57

Give tests on MacOS more time

---

.github/labeler.yml
.github/workflows/pull_request_label.yml

contribute a PR labeler

---

pkgs/native_assets_cli/lib/src/model/build_config.dart
pkgs/native_assets_cli/pubspec.yaml
pkgs/native_assets_cli/test/helpers.dart
pkgs/native_assets_cli/test/model/build_config_test.dart

Upstreaming from https://dart-review.googlesource.com/c/sdk/+/300203/14/pkg/native_assets_builder/lib/src/build_runner/build_runner.dart#205.

[native_assets_cli] Add `outDirName`

---

pkgs/c_compiler/test/cbuilder/cbuilder_cross_ios_test.dart

Also exercise the other tool mentioned in https://github.com/dart-lang/native/issues/54 in tests.

[c_compiler] test install_name_tool behavior

---

pkgs/c_compiler/lib/src/cbuilder/cbuilder.dart
pkgs/c_compiler/test/cbuilder/cbuilder_test.dart
pkgs/native_assets_cli/lib/src/model/build_config.dart
pkgs/native_assets_cli/test/example/native_add_test.dart
pkgs/native_assets_cli/test/model/build_config_test.dart
pkgs/native_assets_cli/test/model/target_test.dart

Addresses the remaining concerns in:
* https://github.com/dart-lang/native/issues/51

[native_asset_cli] Trim `dry_run` of architecture, build_mode, etc.

---

.github/workflows/dart.yaml
.github/workflows/no-response.yml
.github/workflows/publish.yaml
.github/workflows/pull_request_label.yml

This PR contains changes created by the blast repo tool.
- `auto-publish`
- `github-actions`
- `no-response`

blast repo changes: auto-publish, github-actions, no-response

---

pkgs/native_assets_builder/CHANGELOG.md
pkgs/native_assets_builder/lib/src/build_runner/build_runner.dart
pkgs/native_assets_builder/pubspec.yaml

Closes:
* https://github.com/dart-lang/native/issues/98

[native_assets_builder] Builder `out/` folder

---

pkgs/native_assets_builder/CHANGELOG.md
pkgs/native_assets_builder/lib/src/build_runner/build_runner.dart
pkgs/native_assets_builder/test/build_runner/build_runner_reusability_test.dart
pkgs/native_assets_builder/test/data/package_reading_metadata/build.dart
pkgs/native_assets_cli/CHANGELOG.md

Closes https://github.com/dart-lang/native/issues/102.

[native_assets_builder] Fix multiple invocations of the build runner

---

pkgs/native_assets_builder/lib/src/build_runner/build_runner.dart
pkgs/native_assets_builder/pubspec.yaml
pkgs/native_assets_builder/test/build_runner/build_runner_dry_run_test.dart
pkgs/native_assets_builder/test/build_runner/helpers.dart

https://github.com/dart-lang/native/issues/98 forgot to add the out subfolder to dry runs.

[native_assets_builder] Fix dry run directory structure

---

pkgs/native_assets_cli/CHANGELOG.md
pkgs/native_assets_cli/lib/src/model/asset.dart
pkgs/native_assets_cli/pubspec.yaml
pkgs/native_assets_cli/test/model/asset_test.dart
pkgs/native_assets_cli/test/model/build_output_test.dart

Closes https://github.com/dart-lang/native/issues/100.
Requires publishing, and then bumping this package as dependency in the other packages as follow up PR.

[native_assets_cli] Rename `Asset` `name` to `id`

---

pkgs/native_assets_builder/CHANGELOG.md
pkgs/native_assets_builder/lib/src/build_runner/build_runner.dart
pkgs/native_assets_builder/pubspec.yaml

Closes: https://github.com/dart-lang/native/issues/128

[native_assets_builder] Speedup builds for 0 or 1 packages with native assets

---

.github/workflows/native_toolchain_c.yaml

Addressing https://github.com/dart-lang/native/pull/135#pullrequestreview-1629314029

[infra] Fix name for ci config

---

pkgs/native_assets_builder/test/build_runner/helpers.dart

Closes: https://github.com/dart-lang/native/issues/149

[native_assets_builder] Fix pub warning in tests

---

pkgs/native_toolchain_c/lib/src/tool/tool_resolver.dart

Closes: https://github.com/dart-lang/native/issues/178

[native_toolchain_c] Fix NDK discovery

---

pkgs/native_assets_builder/lib/src/utils/run_process.dart
pkgs/native_toolchain_c/lib/src/utils/run_process.dart

Try to solve: https://github.com/dart-lang/native/issues/186

Preserve temp directory when running isolated test on Windows

---

pkgs/native_assets_cli/pubspec.yaml

To prevent issues such as https://github.com/dart-lang/native/issues/818.

[native_assets_cli] Add note to bump protocol version

---

pkgs/ffigen/lib/src/code_generator/library.dart

Fixed a typo in the warn if private log message.

---

.github/workflows/health.yaml
.github/workflows/post_summaries.yaml

A workflow which performs some basic checks on PRs, see https://github.com/dart-lang/ecosystem/tree/main/pkgs/firehose#health.
---
<details> …

Add `health.yaml` workflow

---

.github/workflows/health.yaml

---
<details>
Note that many Dart repos have a weekly cadence for reviewing PRs - …

Don't test web in `health.yaml`

---

pkgs/jnigen/example/in_app_java/lib/android_utils.dart
pkgs/jnigen/example/in_app_java/src/android_utils/android_utils.c

Oops! the one line change broke the CI for ubuntu. Hopefully the first Green JNIgen PR after #1011!

Fix JNIgen CI

---

pkgs/jni/lib/src/third_party/jni_bindings_generated.dart
pkgs/jni/src/dartjni.c
pkgs/jni/src/dartjni.h
pkgs/jnigen/example/in_app_java/src/android_utils/dartjni.h
pkgs/jnigen/example/kotlin_plugin/src/dartjni.h
pkgs/jnigen/example/notification_plugin/src/dartjni.h
pkgs/jnigen/example/pdfbox_plugin/src/third_party/dartjni.h
pkgs/jnigen/test/jackson_core_test/third_party/c_based/c_bindings/dartjni.h
pkgs/jnigen/test/kotlin_test/c_based/c_bindings/dartjni.h
pkgs/jnigen/test/simple_package_test/c_based/c_bindings/dartjni.h

Remove locks around method and field ID retrieval

---

README.md
pkgs/native_assets_builder/lib/src/package_layout/package_layout.dart
pkgs/native_assets_builder/test/build_runner/build_runner_caching_test.dart
pkgs/native_assets_cli/example/local_asset/build.dart
pkgs/native_assets_cli/lib/native_assets_cli.dart
pkgs/native_assets_cli/lib/native_assets_cli_internal.dart
pkgs/native_assets_cli/lib/src/api/build.dart
pkgs/native_assets_cli/lib/src/api/build_config.dart
pkgs/native_assets_cli/lib/src/api/build_mode.dart
pkgs/native_assets_cli/lib/src/api/build_output.dart
pkgs/native_assets_cli/lib/src/model/build_config.dart
pkgs/native_assets_cli/lib/src/model/build_output.dart

* https://github.com/dart-lang/native/issues/823

[native_assets_cli] Update terminology to "build hook"

---

pkgs/native_toolchain_c/CHANGELOG.md
pkgs/native_toolchain_c/pubspec.yaml

I updated the wrong package version in https://github.com/dart-lang/native/pull/1045 🤓

[native_toolchain_c] Release 0.4.0

---

pkgs/native_assets_cli/CHANGELOG.md
pkgs/native_assets_cli/lib/src/api/native_code_asset.dart
pkgs/native_assets_cli/pubspec.yaml

* https://github.com/dart-lang/native/issues/1049

[native_assets_cli] Document `NativeCodeAsset.file` requiredness

---

pkgs/native_assets_cli/CHANGELOG.md
pkgs/native_assets_cli/lib/src/model/build_output.dart
pkgs/native_assets_cli/lib/src/model/build_output_CHANGELOG.md
pkgs/native_assets_cli/pubspec.yaml
pkgs/native_assets_cli/test/model/build_output_test.dart

Closes: https://github.com/dart-lang/native/issues/1053

[native_assets_cli] Fix V1_0_0 backwards compatibility

---

pkgs/jni/CHANGELOG.md
pkgs/jni/pubspec.yaml
pkgs/jnigen/CHANGELOG.md
pkgs/jnigen/README.md
pkgs/jnigen/lib/src/bindings/excluder.dart
pkgs/jnigen/pubspec.yaml
pkgs/jnigen/test/simple_package_test/java/com/github/dart_lang/jnigen/simple_package/Example.java

Closes #1028.
And publishes 0.8.0.

Exclude clinit and publish 0.8.0

---

pkgs/jni/src/dartjni.c
pkgs/jni/test/boxed_test.dart
pkgs/jni/test/exception_test.dart
pkgs/jni/test/global_env_test.dart
pkgs/jni/test/isolate_test.dart
pkgs/jni/test/jarray_test.dart
pkgs/jni/test/jbyte_buffer_test.dart
pkgs/jni/test/jlist_test.dart
pkgs/jni/test/jmap_test.dart
pkgs/jni/test/jobject_test.dart
pkgs/jni/test/jset_test.dart
pkgs/jni/test/jstring_test.dart
pkgs/jni/test/load_test.dart
pkgs/jni/test/test_util/test_util.dart
pkgs/jni/test/type_test.dart
pkgs/jnigen/test/test_util/bindings_test_setup.dart

Use check:jni for tests and fix warnings

---

.github/workflows/ffigen.yml
.github/workflows/ffigen_weekly.yml
pkgs/ffigen/dart_test.yaml

https://github.com/dart-lang/native/issues/461
Check in the configuration so that `dart test` does not fail locally (because I always forget that we can't run with concurrency!)

[ffigen] dart test config

---

pkgs/ffigen/CHANGELOG.md
pkgs/ffigen/lib/src/header_parser/sub_parsers/compounddecl_parser.dart
pkgs/ffigen/test/config_tests/no_cursor_definition_warn_test.dart
pkgs/ffigen/test/header_parser_tests/expected_bindings/_expected_opaque_dependencies_bindings.dart
pkgs/ffigen/test/header_parser_tests/opaque_dependencies.h

Fetch compound cursor definition fetch only when required.

---

pkgs/native_assets_builder/pubspec.yaml
pkgs/native_assets_builder/test_data/add_asset_link/pubspec.yaml
pkgs/native_assets_builder/test_data/complex_link/pubspec.yaml
pkgs/native_assets_builder/test_data/complex_link_helper/pubspec.yaml
pkgs/native_assets_builder/test_data/cyclic_package_1/pubspec.yaml
pkgs/native_assets_builder/test_data/cyclic_package_2/pubspec.yaml
pkgs/native_assets_builder/test_data/drop_dylib_link/pubspec.yaml
pkgs/native_assets_builder/test_data/native_add/pubspec.yaml
pkgs/native_assets_builder/test_data/native_add_add_source/pubspec.yaml
pkgs/native_assets_builder/test_data/native_subtract/pubspec.yaml
pkgs/native_assets_builder/test_data/no_asset_for_link/pubspec.yaml
pkgs/native_assets_builder/test_data/package_reading_metadata/pubspec.yaml
pkgs/native_assets_builder/test_data/package_with_metadata/pubspec.yaml
pkgs/native_assets_builder/test_data/simple_link/pubspec.yaml
pkgs/native_assets_builder/test_data/wrong_build_output/pubspec.yaml
pkgs/native_assets_builder/test_data/wrong_build_output_2/pubspec.yaml
pkgs/native_assets_builder/test_data/wrong_build_output_3/pubspec.yaml
pkgs/native_assets_builder/test_data/wrong_namespace_asset/pubspec.yaml
pkgs/native_assets_cli/example/build/local_asset/pubspec.yaml
pkgs/native_assets_cli/example/build/native_add_library/pubspec.yaml
pkgs/native_assets_cli/example/build/use_dart_api/pubspec.yaml
pkgs/native_assets_cli/example/link/package_with_assets/pubspec.yaml
pkgs/native_toolchain_c/CHANGELOG.md
pkgs/native_toolchain_c/pubspec.yaml

We need a publishing round of the `native_*` packages for Flutter.
* https://github.com/flutter/flutter/issues/146263

[native_toolchain_c] Publish 0.4.2

---

.github/workflows/native.yaml

To work around:
* https://github.com/dart-lang/native/issues/1154

[infra] Use Dart 3.3.0 as stable on Windows

---

pkgs/native_assets_builder/CHANGELOG.md
pkgs/native_assets_builder/pubspec.yaml
pkgs/native_assets_builder/test_data/add_asset_link/pubspec.yaml
pkgs/native_assets_builder/test_data/drop_dylib_link/pubspec.yaml
pkgs/native_assets_builder/test_data/native_add/pubspec.yaml
pkgs/native_assets_builder/test_data/native_add_add_source/pubspec.yaml
pkgs/native_assets_builder/test_data/native_subtract/pubspec.yaml
pkgs/native_assets_cli/example/build/native_add_library/pubspec.yaml
pkgs/native_assets_cli/example/build/use_dart_api/pubspec.yaml

We need a publishing round of the `native_*` packages for Flutter.
* https://github.com/flutter/flutter/issues/146263

[native_assets_builder] Publish 0.7.0

---

pkgs/objective_c/CHANGELOG.md
pkgs/objective_c/lib/objective_c.dart
pkgs/objective_c/lib/src/ns_mutable_data.dart
pkgs/objective_c/test/ns_mutable_data_test.dart

- Add some extensions to `NSMutableData`
- Add a `List<int>` extension to create `NSMutableData`
Fixes https://github.com/dart-lang/native/issues/1181
---
<details> …

Add useful extensions to NSMutableData

---

pkgs/ffigen/lib/src/header_parser/sub_parsers/objcinterfacedecl_parser.dart
pkgs/ffigen/lib/src/header_parser/utils.dart
pkgs/objective_c/CHANGELOG.md
pkgs/objective_c/lib/src/objective_c_bindings_generated.dart
pkgs/objective_c/src/foundation.h

- Fixes a bug in the detection of class declarations introduced in #1162.
- Also fixes #1179. We simply hand't included the definition of `NSError` yet.

Fixes from #1175 that are not related to protocols

---

pkgs/jnigen/CHANGELOG.md
pkgs/jnigen/java/src/main/java/com/github/dart_lang/jnigen/apisummarizer/disasm/KotlinMetadataAnnotationVisitor.java
pkgs/jnigen/java/src/main/java/com/github/dart_lang/jnigen/apisummarizer/elements/ClassDecl.java
pkgs/jnigen/java/src/main/java/com/github/dart_lang/jnigen/apisummarizer/elements/KotlinPackage.java
pkgs/jnigen/lib/src/bindings/dart_generator.dart
pkgs/jnigen/lib/src/bindings/kotlin_processor.dart
pkgs/jnigen/lib/src/bindings/renamer.dart
pkgs/jnigen/lib/src/elements/elements.dart
pkgs/jnigen/lib/src/elements/elements.g.dart
pkgs/jnigen/pubspec.yaml
pkgs/jnigen/test/kotlin_test/bindings/kotlin.dart
pkgs/jnigen/test/kotlin_test/kotlin/src/main/kotlin/com/github/dart_lang/jnigen/TopLevel.kt
pkgs/jnigen/test/kotlin_test/runtime_test_registrant.dart

[jnigen] Add support for Kotlin top-level functions and fields

---

pkgs/ffi/CHANGELOG.md
pkgs/ffi/analysis_options.yaml
pkgs/ffi/example/main.dart
pkgs/ffi/lib/ffi.dart
pkgs/ffi/lib/src/allocation.dart
pkgs/ffi/lib/src/arena.dart
pkgs/ffi/lib/src/utf16.dart
pkgs/ffi/lib/src/utf8.dart
pkgs/ffi/pubspec.yaml
pkgs/ffi/test/allocation_test.dart
pkgs/ffi/test/arena_test.dart
pkgs/ffi/test/utf16_test.dart
pkgs/ffi/test/utf8_test.dart

---
<details>
Note that many Dart repos have a weekly cadence for …

Switch to `package:dart_flutter_team_lints`

---

pkgs/jni/CHANGELOG.md
pkgs/jni/analysis_options.yaml
pkgs/jni/example/pubspec.lock
pkgs/jni/lib/jni.dart
pkgs/jni/pubspec.yaml
pkgs/jni/test/load_test.dart
pkgs/jnigen/CHANGELOG.md
pkgs/jnigen/analysis_options.yaml
pkgs/jnigen/lib/tools.dart
pkgs/jnigen/pubspec.yaml
pkgs/objective_c/example/pubspec.lock

@HosseinYousefi You might want to enable the `strict-` analyzer options to ensure there's no bugs.

[jnigen] Switch to `package:dart_flutter_team_lints`

---

pkgs/native_assets_builder/CHANGELOG.md
pkgs/native_assets_builder/pubspec.yaml
pkgs/native_assets_builder/test_data/manifest.yaml
pkgs/native_assets_builder/test_data/simple_data_asset/bin/deep_modify_data_asset.dart.debug
pkgs/native_assets_builder/test_data/simple_data_asset/bin/modify_data_asset.dart.debug

---
<details>
Note that many Dart repos have a weekly cadence for …

Add more data asset test files

---

pkgs/jni/analysis_options.yaml
pkgs/jni/lib/src/jclass.dart
pkgs/jni/lib/src/lang/jboolean.dart
pkgs/jni/lib/src/lang/jbyte.dart
pkgs/jni/lib/src/lang/jcharacter.dart
pkgs/jni/lib/src/lang/jdouble.dart
pkgs/jni/lib/src/lang/jfloat.dart
pkgs/jni/lib/src/lang/jinteger.dart
pkgs/jni/lib/src/lang/jlong.dart
pkgs/jni/lib/src/lang/jnumber.dart
pkgs/jni/lib/src/lang/jshort.dart
pkgs/jni/lib/src/lang/jstring.dart
pkgs/jni/lib/src/nio/jbuffer.dart
pkgs/jni/lib/src/nio/jbyte_buffer.dart
pkgs/jni/test/load_test.dart
pkgs/jni/test/type_test.dart

**Stack**:
- #1317
- #1316 ⬅
- #1315
- #1314
- #1313
- #1312
- #1311
- #1310
- #1309
- #1308
- #1307
- #1306
- #1305
- #1304
⚠️ *Part of a stack created by [spr](https://github.com/ejoffe/spr). Do not merge manually using the UI - doing so may have unexpected results.*

[jni] 13 - `unreachable_from_main` lint

---

pkgs/jni/analysis_options.yaml
pkgs/jni/lib/src/jclass.dart
pkgs/jni/lib/src/lang/jboolean.dart
pkgs/jni/lib/src/lang/jbyte.dart
pkgs/jni/lib/src/lang/jcharacter.dart
pkgs/jni/lib/src/lang/jdouble.dart
pkgs/jni/lib/src/lang/jfloat.dart
pkgs/jni/lib/src/lang/jinteger.dart
pkgs/jni/lib/src/lang/jlong.dart
pkgs/jni/lib/src/lang/jnumber.dart
pkgs/jni/lib/src/lang/jshort.dart
pkgs/jni/lib/src/lang/jstring.dart
pkgs/jni/lib/src/nio/jbuffer.dart
pkgs/jni/lib/src/nio/jbyte_buffer.dart
pkgs/jni/test/load_test.dart
pkgs/jni/test/type_test.dart
pkgs/jni/tool/wrapper_generators/generate_c_extensions.dart

**Stack**:
- #1317
- #1316
- #1315 ⬅
- #1314
- #1313
- #1312
- #1311
- #1310
- #1309
- #1308
- #1307
- #1306
- #1305
- #1304
⚠️ *Part of a stack created by [spr](https://github.com/ejoffe/spr). Do not merge manually using the UI - doing so may have unexpected results.*

[jni] 12 - `unnecessary_parenthesis` lint

---

pkgs/jni/pubspec.yaml
pkgs/jnigen/pubspec.yaml

[jni] [jnigen] Actually change the version in pubspec!

---

pkgs/objective_c/analysis_options.yaml
pkgs/objective_c/example/pubspec.lock
pkgs/objective_c/lib/objective_c.dart
pkgs/objective_c/lib/src/internal.dart
pkgs/objective_c/lib/src/protocol_builder.dart
pkgs/objective_c/pubspec.yaml
pkgs/objective_c/test/generate_code_test.dart
pkgs/objective_c/test/interface_lists_test.dart
pkgs/objective_c/test/ns_mutable_data_test.dart
pkgs/objective_c/test/nsdata_test.dart
pkgs/objective_c/test/nsstring_test.dart

Fix lints in package:objective_c

---

pkgs/native_assets_builder/pubspec.yaml
pkgs/native_assets_builder/test_data/add_asset_link/pubspec.yaml
pkgs/native_assets_builder/test_data/complex_link/pubspec.yaml
pkgs/native_assets_builder/test_data/complex_link_helper/pubspec.yaml
pkgs/native_assets_builder/test_data/cyclic_package_1/pubspec.yaml
pkgs/native_assets_builder/test_data/cyclic_package_2/pubspec.yaml
pkgs/native_assets_builder/test_data/drop_dylib_link/pubspec.yaml
pkgs/native_assets_builder/test_data/fail_on_os_sdk_version/pubspec.yaml
pkgs/native_assets_builder/test_data/fail_on_os_sdk_version_link/pubspec.yaml
pkgs/native_assets_builder/test_data/fail_on_os_sdk_version_linker/pubspec.yaml
pkgs/native_assets_builder/test_data/native_add/pubspec.yaml
pkgs/native_assets_builder/test_data/native_add_add_source/pubspec.yaml
pkgs/native_assets_builder/test_data/native_subtract/pubspec.yaml
pkgs/native_assets_builder/test_data/no_asset_for_link/pubspec.yaml
pkgs/native_assets_builder/test_data/package_reading_metadata/pubspec.yaml
pkgs/native_assets_builder/test_data/package_with_metadata/pubspec.yaml
pkgs/native_assets_builder/test_data/simple_data_asset/pubspec.yaml
pkgs/native_assets_builder/test_data/simple_link/pubspec.yaml
pkgs/native_assets_builder/test_data/wrong_build_output/pubspec.yaml
pkgs/native_assets_builder/test_data/wrong_build_output_2/pubspec.yaml
pkgs/native_assets_builder/test_data/wrong_build_output_3/pubspec.yaml
pkgs/native_assets_builder/test_data/wrong_namespace_asset/pubspec.yaml
pkgs/native_assets_cli/example/build/local_asset/pubspec.yaml
pkgs/native_assets_cli/example/build/native_add_library/pubspec.yaml
pkgs/native_assets_cli/example/build/use_dart_api/pubspec.yaml
pkgs/native_assets_cli/example/link/package_with_assets/pubspec.yaml
pkgs/native_toolchain_c/pubspec.yaml

So we can roll to Flutter:
* https://github.com/dart-lang/native/issues/1256

[native_toolchain_c] Publish 0.5.2

---

pkgs/native_assets_builder/CHANGELOG.md
pkgs/native_assets_builder/pubspec.yaml
pkgs/native_assets_builder/test_data/add_asset_link/pubspec.yaml
pkgs/native_assets_builder/test_data/drop_dylib_link/pubspec.yaml
pkgs/native_assets_builder/test_data/native_add/pubspec.yaml
pkgs/native_assets_builder/test_data/native_add_add_source/pubspec.yaml
pkgs/native_assets_builder/test_data/native_subtract/pubspec.yaml
pkgs/native_assets_cli/example/build/native_add_library/pubspec.yaml
pkgs/native_assets_cli/example/build/use_dart_api/pubspec.yaml

So we can roll to Flutter:
* https://github.com/dart-lang/native/issues/1256

[native_assets_builder] Publish 0.8.1

---

.github/workflows/native.yaml

This reverts commit ae5aeca665e4a6ed4e07aa797d4e9a64d29e0916.
Closes: https://github.com/dart-lang/native/issues/1232

Revert "[infra] pin dev release for `package:native_x` (#1233)"

---

pkgs/native_toolchain_c/test/clinker/objects_test.dart

Closes: https://github.com/dart-lang/native/issues/1452

[native_toolchain_c] Fix test to not cross arch compile

---

pkgs/ffigen/test/code_generator_tests/code_generator_test.dart

Fix merge issue between #1476 and #1432 that broke code_generator_test.dart

[ffigen] Fix CI

---

pkgs/jnigen/example/in_app_java/jnigen.yaml
pkgs/jnigen/example/in_app_java/lib/android_utils.dart

Closes https://github.com/dart-lang/native/issues/1429.
Details: https://github.com/dart-lang/native/issues/1429#issuecomment-2324831255

[jnigen] Fix CI

---

pkgs/swift2objc/lib/src/ast/_core/interfaces/compound_declaration.dart
pkgs/swift2objc/lib/src/ast/declarations/compounds/class_declaration.dart
pkgs/swift2objc/lib/src/ast/declarations/compounds/members/initializer_declaration.dart
pkgs/swift2objc/lib/src/ast/declarations/compounds/protocol_declaration.dart
pkgs/swift2objc/lib/src/ast/declarations/compounds/struct_declaration.dart
pkgs/swift2objc/lib/src/generator/generators/class_generator.dart
pkgs/swift2objc/lib/src/parser/_core/utils.dart
pkgs/swift2objc/lib/src/parser/parsers/declaration_parsers/parse_compound_declaration.dart
pkgs/swift2objc/lib/src/parser/parsers/declaration_parsers/parse_initializer_declaration.dart
pkgs/swift2objc/lib/src/parser/parsers/declaration_parsers/parse_method_declaration.dart
pkgs/swift2objc/lib/src/parser/parsers/parse_declarations.dart
pkgs/swift2objc/lib/src/transformer/transformers/transform_compound.dart
pkgs/swift2objc/lib/src/transformer/transformers/transform_initializer.dart
pkgs/swift2objc/test/integration/classes_and_initializers_input.swift
pkgs/swift2objc/test/integration/classes_and_initializers_output.swift
pkgs/swift2objc/test/integration/structs_and_initializers_input.swift
pkgs/swift2objc/test/integration/structs_and_initializers_output.swift

Add support for initilializers

---

pkgs/jnigen/CHANGELOG.md
pkgs/jnigen/docs/java_differences.md
pkgs/jnigen/lib/src/bindings/excluder.dart
pkgs/jnigen/lib/src/bindings/renamer.dart
pkgs/jnigen/test/jackson_core_test/third_party/bindings/com/fasterxml/jackson/core/JsonFactory.dart
pkgs/jnigen/test/renamer_test.dart

[jnigen] Rename identifiers starting with underscore

---

pkgs/jni/CHANGELOG.md
pkgs/jni/lib/_internal.dart
pkgs/jni/lib/src/jvalues.dart
pkgs/jni/lib/src/types.dart
pkgs/jnigen/CHANGELOG.md
pkgs/jnigen/example/in_app_java/lib/android_utils.dart
pkgs/jnigen/example/kotlin_plugin/lib/kotlin_bindings.dart
pkgs/jnigen/example/notification_plugin/lib/notifications.dart
pkgs/jnigen/example/pdfbox_plugin/lib/src/third_party/org/apache/pdfbox/pdmodel/PDDocument.dart
pkgs/jnigen/example/pdfbox_plugin/lib/src/third_party/org/apache/pdfbox/pdmodel/PDDocumentInformation.dart
pkgs/jnigen/example/pdfbox_plugin/lib/src/third_party/org/apache/pdfbox/text/PDFTextStripper.dart
pkgs/jnigen/lib/src/bindings/dart_generator.dart
pkgs/jnigen/test/jackson_core_test/third_party/bindings/com/fasterxml/jackson/core/JsonFactory.dart
pkgs/jnigen/test/jackson_core_test/third_party/bindings/com/fasterxml/jackson/core/JsonParser.dart
pkgs/jnigen/test/jackson_core_test/third_party/bindings/com/fasterxml/jackson/core/JsonToken.dart
pkgs/jnigen/test/kotlin_test/bindings/kotlin.dart
pkgs/jnigen/test/simple_package_test/bindings/simple_package.dart

Part of issue #1238  
---
<details>
- Most changes should add an entry to the changelog and may need to [rev the pubspec package version](https://github.com/dart-lang/sdk/blob/main/docs/External-Package-Ma …

Rename internal_helpers_for_jnigen to _internal

---

pkgs/jni/src/CMakeLists.txt
pkgs/jnigen/example/in_app_java/lib/android_utils.dart
pkgs/jnigen/example/kotlin_plugin/lib/kotlin_bindings.dart
pkgs/jnigen/example/notification_plugin/lib/notifications.dart
pkgs/jnigen/example/pdfbox_plugin/lib/src/third_party/org/apache/pdfbox/pdmodel/PDDocument.dart
pkgs/jnigen/example/pdfbox_plugin/lib/src/third_party/org/apache/pdfbox/pdmodel/PDDocumentInformation.dart
pkgs/jnigen/example/pdfbox_plugin/lib/src/third_party/org/apache/pdfbox/text/PDFTextStripper.dart
pkgs/jnigen/lib/src/bindings/dart_generator.dart
pkgs/jnigen/test/jackson_core_test/third_party/bindings/com/fasterxml/jackson/core/JsonFactory.dart
pkgs/jnigen/test/jackson_core_test/third_party/bindings/com/fasterxml/jackson/core/JsonParser.dart
pkgs/jnigen/test/jackson_core_test/third_party/bindings/com/fasterxml/jackson/core/JsonToken.dart
pkgs/jnigen/test/kotlin_test/bindings/kotlin.dart
pkgs/jnigen/test/simple_package_test/bindings/simple_package.dart

[jni] set max-page-size=16kb

---

pkgs/objective_c/pubspec.yaml

- Removes `plugin_platform_interface`
- Moves `yaml` to `dev_dependencies`
---
<details>
- Changes to packages require [corresponding tests](https://github.com/dart-lang/.github/blob/main/CONTRIBUTING …

Remove unnecessary `dependencies`

---

pkgs/ffigen/CHANGELOG.md
pkgs/ffigen/lib/src/code_generator/objc_methods.dart
pkgs/ffigen/lib/src/visitor/fix_overridden_methods.dart
pkgs/ffigen/test/native_objc_test/method_test.dart
pkgs/ffigen/test/native_objc_test/method_test.m
pkgs/ffigen/test/native_objc_test/property_test.dart
pkgs/ffigen/test/native_objc_test/property_test.m
pkgs/objective_c/lib/src/objective_c_bindings_generated.dart

[ffigen] Allow static and instance methods/properties with the same name

---

pkgs/objective_c/src/objective_c.c

---
<details>
Note that many Dart repos have a weekly cadence for …

Include stdint.h for int64_t

---

pkgs/jni/CHANGELOG.md
pkgs/jni/pubspec.yaml
pkgs/jnigen/CHANGELOG.md
pkgs/jnigen/pubspec.yaml

Already published, syncing up.

[jni][jnigen] Publish 0.12.2

---

pkgs/objective_c/src/input_stream_adapter.m

<details>
Note that many Dart repos have a weekly cadence for reviewing …

Annotate variables used in `NSCAssert` as being possibly unused

---

pkgs/jni/CHANGELOG.md
pkgs/jni/pubspec.yaml
pkgs/jnigen/CHANGELOG.md
pkgs/jnigen/pubspec.yaml

[jnigen][jni] Publish 0.13.0

---

pkgs/ffigen/README.md

Fixes https://github.com/dart-lang/native/issues/1821

[ffigen] Fix nit in readme

---

pkgs/native_toolchain_c/lib/src/native_toolchain/msvc.dart

MSVC: support finding build tools even when Visual Studio IDE is not installed

---

pkgs/ffigen/lib/src/code_generator/objc_protocol.dart
pkgs/objective_c/src/objective_c_bindings_generated.m
pkgs/objective_c/src/objective_c_runtime.h

Fixes https://github.com/dart-lang/native/issues/1822

[ffigen] Fix some C warnings

---

pkgs/ffi/README.md

Fix: #1851 
---
<details>
- Most changes should add an entry to the changelog and may need to [rev the pubspec package version](https://github.com/dart-lang/sdk/blob/main/docs/External-Package-Maintenance. …

Fix old link in ffi readme

---

pkgs/native_assets_builder/test_data/transformer/hook/build.dart
pkgs/native_assets_builder/test_data/transformer/pubspec.yaml

Hopefully fixes https://github.com/dart-lang/native/issues/1810.

[native_assets_builder] Fix flaky test

---

.github/workflows/health.yaml
pkgs/ffigen/CHANGELOG.md
pkgs/ffigen/pubspec.yaml

https://github.com/dart-lang/native/issues/1857

[ffigen] Disable health check for ffigen

---

pkgs/ffigen/CHANGELOG.md
pkgs/ffigen/pubspec.yaml
pkgs/objective_c/CHANGELOG.md
pkgs/objective_c/pubspec.yaml

Prepare to publish package:ffigen 16.1.0 and package:objective_c 4.1.0

[ffigen] Prepare to publish ffigen 16.1.0

---

pkgs/jnigen/CHANGELOG.md
pkgs/jnigen/pubspec.yaml

Already published, updating the repo.

[jnigen] Publish 0.13.1

---

pkgs/native_assets_builder/lib/src/build_runner/build_runner.dart
pkgs/native_assets_builder/test/build_runner/pub_workspace_test.dart

Fix for 4282a79655f0ccdd198cbe1fe87e2723c2efa091, return a list of packages to facilitate useful error messages in dartdev and flutter tools.

[native_assets_builder] Support pub workspaces 3

---

pkgs/ffigen/test/header_parser_tests/globals.h

Upstreaming a patch from somewhere downstream

[ffigen] Avoid errors in C header file

---

pkgs/jni/CHANGELOG.md
pkgs/jni/pubspec.yaml
pkgs/jnigen/CHANGELOG.md
pkgs/jnigen/pubspec.yaml

[jnigen] [jni] 0.14.0

---

pkgs/ffigen/example/objective_c/avf_audio_bindings.dart
pkgs/ffigen/example/objective_c/avf_audio_bindings.dart.m
pkgs/ffigen/example/objective_c/play_audio.dart
pkgs/ffigen/example/swift/example.dart

Fixes https://github.com/dart-lang/native/issues/1987

[ffigen] Update examples after #1898 broke them

---

pkgs/ffigen/test/native_objc_test/protocol_test.dart
pkgs/objective_c/CHANGELOG.md
pkgs/objective_c/lib/src/protocol_builder.dart

This is just exposing the internals of method implementation for advanced use cases.
Fixes https://github.com/dart-lang/native/issues/1675

[ffigen] Direct protocol method implementation using blocks

---

pkgs/jni/example/android/settings.gradle
pkgs/jnigen/android_test_runner/android/settings.gradle
pkgs/jnigen/example/in_app_java/android/settings.gradle
pkgs/jnigen/example/kotlin_plugin/example/android/settings.gradle
pkgs/jnigen/example/notification_plugin/example/android/settings.gradle
pkgs/jnigen/example/pdfbox_plugin/example/android/settings.gradle

[jni][jnigen] Upgrade Kotlin version to 1.8.10

---

pkgs/jni/android/build.gradle
pkgs/jni/example/android/app/build.gradle
pkgs/jnigen/android_test_runner/android/app/build.gradle
pkgs/jnigen/example/in_app_java/android/app/build.gradle
pkgs/jnigen/example/kotlin_plugin/android/build.gradle
pkgs/jnigen/example/kotlin_plugin/example/android/app/build.gradle
pkgs/jnigen/example/notification_plugin/android/build.gradle
pkgs/jnigen/example/notification_plugin/example/android/app/build.gradle
pkgs/jnigen/example/pdfbox_plugin/android/build.gradle
pkgs/jnigen/example/pdfbox_plugin/example/android/app/build.gradle

[jni] [jnigen] Upgrade source and target compatibility to Java 11

---

pkgs/jni/CHANGELOG.md
pkgs/jni/java/.gitignore
pkgs/jni/pubspec.yaml
pkgs/jnigen/CHANGELOG.md
pkgs/jnigen/java/.gitignore
pkgs/jnigen/pubspec.yaml

[jni] [jnigen] Publish 0.14.1

---

pkgs/jnigen/lib/jnigen.dart

I have to actually use the categories for dartdoc to generate them as htmls in pub.dev. Using them all for the library.

[jnigen] Fix dartdoc topics

---

pkgs/native_assets_cli/test/code_assets/validation_test.dart

The current validation logic check both some syntactic and some semantic errors.
These missing field should be syntactic errors, and therefore should not be constructible by builders.
(Currently they have to be syntactically allowed to be able to check them as semantic errors. https://github.com/dart-lang/native/issues/2039 We should fix that in general and have a syntax validation pass and a semantic validation pass. If there are any syntax errors, we should not be doing semantic validation.)
This PR changes the test so it doesn't rely on being able to construct a syntactically faulty json with the builder API.

[native_assets_cli] Refactor syntax validation test

---

README.md

Closes: https://github.com/dart-lang/native/issues/2036

[infra] Mention native_toolchain_cmake in readme

---

.github/workflows/native.yaml
pkgs/native_assets_cli/example/build/download_asset/hook/build.dart

https://github.com/dart-lang/native/pull/2097#discussion_r1999148392

[native_assets_cli] Fix download_asset example

---

pkgs/native_assets_builder/lib/src/build_runner/build_runner.dart

Thanks for the report @MichealReed!

[native_assets_builder] Fix env var typo

---

pkgs/hook/tool/generate_syntax.dart
pkgs/native_assets_cli/lib/src/code_assets/syntax.g.dart

The manual sorting was to keep the diff small while iterating on the code generator, we should simply remove it now.

[native_assets_cli] Remove manual sorting

---

pkgs/native_assets_builder/lib/src/build_runner/build_runner.dart
pkgs/native_assets_builder/test/build_runner/link_test.dart

Closes: https://github.com/dart-lang/native/issues/2149
Requires a fix in SDKs when rolled.

[native_assets_builder] Fix 2149

---

pkgs/code_assets/doc/schema/shared/shared_definitions.schema.json
pkgs/hooks/tool/generate_syntax.dart
pkgs/native_assets_cli/lib/src/code_assets/link_mode_preference.dart
pkgs/native_assets_cli/lib/src/code_assets/syntax.g.dart

Bug:
Cleanup of:
* https://github.com/dart-lang/native/issues/2038

[native_assets_cli] Cleanup JSON: `prefer-static` and `prefer-dynamic`

---

pkgs/code_assets/test/data/build_input_macos.json
pkgs/data_assets/test/data/build_input.json
pkgs/hooks/doc/schema/shared/shared_definitions.schema.json
pkgs/hooks/test/data/build_output.json
pkgs/hooks/test/schema/helpers.dart
pkgs/native_assets_builder/lib/src/build_runner/build_runner.dart
pkgs/native_assets_builder/test_data/package_reading_metadata/hook/build.dart
pkgs/native_assets_builder/test_data/package_with_metadata/hook/build.dart
pkgs/native_assets_builder/test_data/wrong_build_output_3/hook/build.dart
pkgs/native_assets_cli/lib/src/config.dart
pkgs/native_assets_cli/lib/src/hooks/syntax.g.dart
pkgs/native_assets_cli/test/build_input_test.dart
pkgs/native_assets_cli/test/build_output_test.dart

Bug:
Cleanup of:
* https://github.com/dart-lang/native/issues/1251

[native_assets_cli] Cleanup JSON: old metadata

---

pkgs/objective_c/CHANGELOG.md
pkgs/objective_c/lib/objective_c.dart
pkgs/objective_c/lib/src/ns_number.dart
pkgs/objective_c/test/nsnumber_test.dart

Fixes https://github.com/dart-lang/native/issues/1445

[ffigen] Conversions from Dart numbers to NSNumber

---

pkgs/ffigen/pubspec.yaml

Fix pubspec validation error: https://github.com/dart-lang/native/actions/runs/14732825838/job/41351201326?pr=2255

[ffigen] Fix pubspec

---

pkgs/objective_c/CHANGELOG.md
pkgs/objective_c/lib/objective_c.dart
pkgs/objective_c/lib/src/ns_date.dart
pkgs/objective_c/test/nsdate_test.dart
pkgs/objective_c/test/nsnumber_test.dart

Fixes https://github.com/dart-lang/native/issues/285

[objective_c] Add conversions between `NSDate` and `DateTime`

---

pkgs/hooks/pubspec.yaml
pkgs/hooks/tool/generate_schemas.dart
pkgs/hooks/tool/generate_syntax.dart
pkgs/hooks/tool/normalize.dart

Unify the generators in this project to have a `--set-exit-if-changed` CLI argument.
```
$ dart pkgs/hooks/tool/generate_schemas.dart --set-exit-if-changed
Generated 32 files (0 changed) in 0.03 seconds.
$ dart pkgs/hooks/tool/generate_syntax.dart --set-exit-if-changed
Generated 3 files (0 changed) in 2.58 seconds.
$ dart pkgs/hooks/tool/normalize.dart --set-exit-if-changed
Normalized 61 files (0 changed) in 0.08 seconds.
```

[hooks] Unify the generators

---

pkgs/native_doc_dartifier/README.md

[native_doc_dartifier] initial readme

---

pkgs/hooks/lib/src/api/build_and_link.dart

<details>
Note that many Dart repos have a weekly cadence for reviewing …

[hooks] Clarify that a build/link hook *must* call `build`/`link`.

---

tool/ci.dart

Accounts for the changes in https://dart-review.googlesource.com/c/sdk/+/435123 having rolled into Flutter.

[infra] Fix CI

---

pkgs/jnigen/example/kotlin_plugin/lib/kotlin_bindings.dart
pkgs/jnigen/java/src/main/java/com/github/dart_lang/jnigen/apisummarizer/elements/KotlinFunction.java
pkgs/jnigen/lib/src/bindings/dart_generator.dart
pkgs/jnigen/lib/src/elements/elements.dart
pkgs/jnigen/lib/src/elements/elements.g.dart
pkgs/jnigen/test/kotlin_test/bindings/kotlin.dart
pkgs/jnigen/test/kotlin_test/kotlin/src/main/kotlin/com/github/dart_lang/jnigen/Nullability.kt

Fixes https://github.com/dart-lang/native/issues/1236#event-17450552708

[jnigen] Use Kotlin signature in the docs of Kotlin methods

---

pkgs/code_assets/pubspec.yaml
pkgs/native_toolchain_c/pubspec.yaml

.
---
<details>
Note that many Dart repos have a weekly cadence for …

[infra] Fix `code_assets` and `native_toolchain_c` versions

---

pkgs/ffigen/lib/src/header_parser/parser.dart
pkgs/ffigen/test/large_integration_tests/large_objc_test.dart

Still can't repro this locally, so this is just a hacky workaround. I'm leaving the issue open.
https://github.com/dart-lang/native/issues/2517

[ffigen] Fix CI failure

---

pkgs/ffigen/test/large_integration_tests/large_objc_test.dart
pkgs/ffigen/test/test_utils.dart

Closes: https://github.com/dart-lang/native/issues/2562

[ffigen] Use `printOnFailure` in tests

---

pkgs/code_assets/example/mini_audio/hook/build.dart
pkgs/code_assets/example/sqlite/hook/build.dart
pkgs/code_assets/example/stb_image/hook/build.dart

[code_assets] Tweak examples

---

pkgs/code_assets/CHANGELOG.md
pkgs/code_assets/pubspec.yaml
pkgs/hooks/pubspec.yaml

So that the examples will be visible on pub.dev.

[code_assets] Publish

---

pkgs/objective_c/CHANGELOG.md
pkgs/objective_c/ffigen_c.yaml
pkgs/objective_c/lib/objective_c.dart
pkgs/objective_c/lib/src/autorelease.dart
pkgs/objective_c/lib/src/c_bindings_generated.dart
pkgs/objective_c/lib/src/ns_input_stream.dart
pkgs/objective_c/src/objective_c_runtime.h
pkgs/objective_c/test/autorelease_test.dart
pkgs/objective_c/test/ns_input_stream_test.dart
pkgs/objective_c/test/observer_test.dart
pkgs/objective_c/test/util.dart

Fixes https://github.com/dart-lang/native/issues/1472
Related to https://github.com/dart-lang/sdk/issues/61129

[objective_c] Add `autoReleasePool` API
